/**
 * Nano Banana 2 tutorials — design assistant & Google launch — full copy for EXTRA_LOCALES (21).
 */
import type { ExtraLocaleTutorialArticle } from './tutorial-articles-extra-locales';

const NB_DESIGN_IMG = 'https://img.limaxai.com/aiweb/limaxai-4.png';
const NB_LAUNCH_IMG = 'https://img.limaxai.com/aiweb/limaxai-5.png';

type Nb2DesignExtra = {
  title: string;
  intro: string;
  st: string;
  s1: string;
  s2: string;
  s3: string;
  bt: string;
  b1: string;
  b2: string;
  mt: string;
  m1: string;
  m2: string;
  imgT: string;
  imgAlt: string;
  imgC: string;
  startT: string;
  startx: string;
  cta: string;
};

type Nb2LaunchExtra = {
  title: string;
  intro: string;
  rt: string;
  r1: string;
  ct: string;
  c1: string;
  tt: string;
  t1: string;
  imgT: string;
  imgAlt: string;
  imgC: string;
  startT: string;
  startx: string;
  cta: string;
};

const nanobanana2DesignExtraLocales: Record<string, Nb2DesignExtra> = {
  es: {
    title: 'Nano Banana 2 como asistente de diseño: storyboards, retoque por lotes y multi-formato',
    intro:
      'Trátalo como un asistente que entiende briefs en lenguaje natural: storyboards enteros, estilo unificado en lotes y adaptación de proporciones. Incluye plantillas listas para e-commerce en LimaxAI.',
    st: 'Storyboards de muchos paneles de una vez',
    s1: 'Indica cuántos paneles (12/24/48), público, dolor y qué vendes (beneficios clave). Pasas de «escribir prompts» a «dar briefing y revisar».',
    s2: 'Plantilla: storyboard publicitario fotorrealista en cuadrícula 24 para un portátil; variantes de color, primeros planos y detalle. Otro ejemplo: 12 paneles para un coche con noche urbana, interior tecnológico y foco en seguridad y autonomía.',
    s3: 'Pega una URL de referencia de marca y pide una página de producto en ese lenguaje visual. En marketplaces: «6 imágenes tipo Amazon» (principal, escena, puntos fuertes, materiales, medidas). Para camping: «6 imágenes para listing en Amazon EE. UU.».',
    bt: 'Retoque masivo de fotos de producto',
    b1: 'Con muchos SKU necesitas un look de estudio coherente. Sube muchas fotos y pide: misma dirección de sombra, reflejos más limpios, metal más duro, bordes más nítidos, fondo gris claro uniforme.',
    b2: 'Plantilla: retoque por lotes, fondo gris claro; conservar proporción y estructura; bordes más definidos; mejor textura metal/plástico; reflejos controlados; sombras coherentes; color estable; sin suavizado excesivo ni alterar el producto.',
    mt: 'Salida multi-tamaño',
    m1: 'Un creativo debe servir 1:1, 4:5, 16:9 u 8:1 sin reacomodar todo a mano.',
    m2: 'Plantilla: extiende a 8:1 sin deformar el sujeto ni recortar lo esencial; fondo naturalmente prolongado; texto legible; estilo igual al original. Igual para 16:9.',
    imgT: 'Muestra visual',
    imgAlt: 'Nano Banana 2 como asistente de diseño',
    imgC: 'Storyboard y multi-formato',
    startT: 'Empezar a crear',
    startx: 'En LimaxAI usa Nano Banana 2 como asistente de diseño, retoque y adaptación para subir el ritmo de creativos.',
    cta: 'Usar en LimaxAI',
  },
  ar: {
    title: 'نانو بانانا 2 كمساعد تصميم: ستوري بورد، تعديل دفعات، وأحجام متعددة',
    intro:
      'استخدمه كمساعد يفهم الموجز بلغة بسيطة: ستوري بورد كامل، توحيد المظهر على دفعات، وتكييف النسب. قوالب جاهزة للتجارة الإلكترونية على LimaxAI.',
    st: 'ستوري بورد بعدة لقطات دفعة واحدة',
    s1: 'حدد عدد اللقطات (12/24/48) والجمهور والمشكلة والمنتج (أهم الفوائد). تنتقل من «كتابة أوامر» إلى «موجز + مراجعة».',
    s2: 'قالب: ستوري بورد إعلاني واقعي 24 شبكة لجهاز محمول؛ ألوان متعددة ولقطات قريبة. أو 12 لوحة لسيارة: ليل المدينة، مقصورة تقنية، التركيز على الأمان والمدى.',
    s3: 'الصق رابط مرجعي لعلامة واطلب صفحة منتج بنفس الأسلوب البصري. للمتاجر: «6 صور على نمط أمازون». لمخيم: «6 صور لإدراج خيمة في أمازون الولايات المتحدة».',
    bt: 'تعديل دفعات لصور المنتج',
    b1: 'ارفع عدة صور واطلب بلغة واضحة: اتجاه ظل موحد، انعكاسات أنظف، معدن أصلب، حواف أوضح، خلفية رمادية فاتحة موحدة.',
    b2: 'قالب: تعديل دفعات، خلفية استوديو رمادية فاتحة؛ الحفاظ على النسب والهيكل؛ حواف أوضح؛ نسيج معدن/بلاستيك أفضل؛ انعكاسات نظيفة؛ ظلال متسقة؛ لون ثابت؛ دون تشويه تفاصيل المنتج.',
    mt: 'مخرجات متعددة المقاسات',
    m1: 'نفس التصميم لـ 1:1 و4:5 و16:9 و8:1 دون إعادة تخطيط يدوية كاملة.',
    m2: 'قالب: مدّد إلى 8:1 دون تشويه الموضوع أو قص العناصر المهمة؛ خلفية ممتدة بشكل طبيعي؛ نص مقروء؛ أسلوب مطابق للأصل. نفس الفكرة لـ 16:9.',
    imgT: 'صورة توضيحية',
    imgAlt: 'نانو بانانا 2 كمساعد تصميم',
    imgC: 'ستوري بورد وأحجام متعددة',
    startT: 'ابدأ الإنشاء',
    startx: 'على LimaxAI استخدم نانو بانانا 2 كمساعد تصميم وتعديل وتكييف لزيادة إنتاجية المخرجات.',
    cta: 'استخدام على LimaxAI',
  },
  pt: {
    title: 'Nano Banana 2 como assistente de design: storyboards, retoque em lote e multi-formato',
    intro:
      'Trate-o como um assistente que entende briefings em linguagem natural: storyboards completos, uniformização de estilo em lote e adaptação de proporções. Modelos prontos para e-commerce no LimaxAI.',
    st: 'Storyboards com muitos painéis de uma vez',
    s1: 'Indique quantos painéis (12/24/48), público, dor e o que vende (benefícios). Você passa de «escrever prompts» para «dar briefing e revisar».',
    s2: 'Modelo: storyboard publicitário fotorrealista em grelha 24 para um portátil; variantes de cor e closes. Ou 12 painéis para um carro: noite urbana, interior tech, foco em segurança e autonomia.',
    s3: 'Cole um URL de referência de marca e peça uma página de produto nesse visual. Para marketplaces: «6 imagens estilo Amazon». Para camping: «6 imagens para listagem na Amazon EUA».',
    bt: 'Retoque em lote de fotos de produto',
    b1: 'Com muitos SKUs precisa de um look de estúdio coerente. Envie várias fotos e peça: mesma direção de sombra, reflexos mais limpos, metal mais duro, bordas mais nítidas, fundo cinza claro uniforme.',
    b2: 'Modelo: retoque em lote, fundo cinza claro; manter proporção e estrutura; bordas mais definidas; melhor textura metal/plástico; reflexos controlados; sombras coerentes; cor estável; sem alisamento excessivo.',
    mt: 'Saída multi-tamanho',
    m1: 'O mesmo criativo para 1:1, 4:5, 16:9 e 8:1 sem recompor tudo à mão.',
    m2: 'Modelo: estenda para 8:1 sem distorcer o sujeito nem cortar o essencial; fundo prolongado de forma natural; texto legível; estilo igual ao original. Idem para 16:9.',
    imgT: 'Referência visual',
    imgAlt: 'Nano Banana 2 como assistente de design',
    imgC: 'Storyboard e multi-formato',
    startT: 'Começar a criar',
    startx: 'No LimaxAI use o Nano Banana 2 como assistente de design, retoque e adaptação para acelerar a produção de criativos.',
    cta: 'Usar no LimaxAI',
  },
  id: {
    title: 'Nano Banana 2 sebagai asisten desain: storyboard, edit massal, multi-ukuran',
    intro:
      'Anggap sebagai asisten yang memahami brief bahasa sehari-hari: storyboard penuh, penyatuan gaya secara batch, dan penyesuaian rasio. Template siap pakai untuk e-commerce di LimaxAI.',
    st: 'Storyboard banyak panel sekaligus',
    s1: 'Sebutkan jumlah panel (12/24/48), audiens, masalah, dan produk (manfaat utama). Anda beralih dari «menulis prompt» ke «memberi brief + meninjau».',
    s2: 'Contoh: storyboard iklan fotorealistik grid 24 untuk laptop; variasi warna dan close-up. Atau 12 panel mobil: malam kota, interior tech, fokus keselamatan dan jangkauan.',
    s3: 'Tempel URL referensi merek dan minta halaman produk dengan bahasa visual serupa. Untuk marketplace: «6 gambar gaya Amazon». Untuk tenda: «6 gambar untuk listing Amazon AS».',
    bt: 'Retus massal foto produk',
    b1: 'Dengan banyak SKU Anda butuh tampilan studio konsisten. Unggah banyak gambar dan minta: arah bayangan sama, refleksi lebih bersih, logam lebih keras, tepi lebih tajam, latar abu-abu terang seragam.',
    b2: 'Template: retus batch, latar studio abu-abu terang; pertahankan proporsi dan struktur; tepi lebih jelas; tekstur logam/plastik lebih baik; refleksi terkontrol; bayangan konsisten; warna stabil; tanpa oversmooth.',
    mt: 'Output multi-ukuran',
    m1: 'Satu kreatif untuk 1:1, 4:5, 16:9, dan 8:1 tanpa susun ulang manual penuh.',
    m2: 'Template: perpanjang ke 8:1 tanpa mendistorsi subjek atau memotong bagian penting; latar memanjang alami; teks tetap terbaca; gaya sama dengan aslinya. Sama untuk 16:9.',
    imgT: 'Contoh gambar',
    imgAlt: 'Nano Banana 2 sebagai asisten desain',
    imgC: 'Storyboard dan multi-ukuran',
    startT: 'Mulai membuat',
    startx: 'Di LimaxAI gunakan Nano Banana 2 sebagai asisten desain, retus, dan adaptasi untuk menaikkan throughput kreatif.',
    cta: 'Gunakan di LimaxAI',
  },
  ms: {
    title: 'Nano Banana 2 sebagai pembantu reka bentuk: storyboard, suntingan kelompok, pelbagai saiz',
    intro:
      'Anggap ia pembantu yang faham taklimat bahasa biasa: storyboard penuh, penyatuan gaya secara kelompok, dan penyesuaian nisbah. Templat siap untuk e-dagang di LimaxAI.',
    st: 'Storyboard banyak panel sekaligus',
    s1: 'Nyatakan bilangan panel (12/24/48), audiens, masalah, dan produk (faedah utama). Anda beralih daripada «menulis prompt» kepada «memberi taklimat + menyemak».',
    s2: 'Contoh: storyboard iklan fotorealistik grid 24 untuk komputer riba; variasi warna dan close-up. Atau 12 panel kereta: malam bandar, dalaman tech, fokus keselamatan dan jarak.',
    s3: 'Tampal URL rujukan jenama dan minta halaman produk dalam bahasa visual yang sama. Untuk marketplace: «6 imej gaya Amazon». Untuk khemah: «6 imej untuk penyenaraian Amazon AS».',
    bt: 'Suntingan kelompok imej produk',
    b1: 'Dengan banyak SKU anda perlukan rupa studio konsisten. Muat naik banyak imej dan minta: arah bayang sama, pantulan lebih bersih, logam lebih keras, tepi lebih tajam, latar kelabu terang seragam.',
    b2: 'Templat: suntingan kelompok, latar studio kelabu terang; kekalkan nisbah dan struktur; tepi lebih jelas; tekstur logam/plastik lebih baik; pantulan terkawal; bayang konsisten; warna stabil.',
    mt: 'Output pelbagai saiz',
    m1: 'Satu kreatif untuk 1:1, 4:5, 16:9, dan 8:1 tanpa susun semula manual penuh.',
    m2: 'Templat: panjangkan ke 8:1 tanpa herot subjek atau potong bahagian penting; latar memanjang semula jadi; teks kekal dibaca; gaya sama dengan asal. Sama untuk 16:9.',
    imgT: 'Imej rujukan',
    imgAlt: 'Nano Banana 2 sebagai pembantu reka bentuk',
    imgC: 'Storyboard dan pelbagai saiz',
    startT: 'Mula mencipta',
    startx: 'Di LimaxAI gunakan Nano Banana 2 sebagai pembantu reka bentuk, sunting, dan penyesuaian untuk meningkatkan output kreatif.',
    cta: 'Guna di LimaxAI',
  },
  fr: {
    title: 'Nano Banana 2 comme assistant design : storyboards, retouche par lots et multi-formats',
    intro:
      'Utilisez-le comme un assistant qui comprend des briefs en langage naturel : storyboards complets, harmonisation de style par lots et adaptation des ratios. Modèles prêts pour l’e-commerce sur LimaxAI.',
    st: 'Storyboards multi-panneaux en une fois',
    s1: 'Indiquez le nombre de panneaux (12/24/48), l’audience, la douleur et le produit (bénéfices clés). Vous passez de « rédiger des prompts » à « brief + relecture ».',
    s2: 'Modèle : storyboard publicitaire photoréaliste en grille 24 pour un ordinateur portable ; variantes de couleur et gros plans. Ou 12 panneaux pour une voiture : nuit urbaine, habitacle tech, focus sécurité et autonomie.',
    s3: 'Collez une URL de référence de marque et demandez une page produit dans ce langage visuel. Pour les marketplaces : « 6 images type Amazon ». Pour une tente : « 6 images pour une fiche Amazon US ».',
    bt: 'Retouche par lots des photos produit',
    b1: 'Avec de nombreux SKU, il faut un rendu studio cohérent. Uploadez plusieurs images et demandez : même direction d’ombre, reflets plus propres, métal plus dur, bords plus nets, fond gris clair uniforme.',
    b2: 'Modèle : retouche par lots, fond studio gris clair ; conserver proportions et structure ; bords plus nets ; meilleure texture métal/plastique ; reflets maîtrisés ; ombres cohérentes ; couleur stable ; pas de lissage excessif.',
    mt: 'Sortie multi-formats',
    m1: 'Un même visuel pour 1:1, 4:5, 16:9 et 8:1 sans tout recomposer à la main.',
    m2: 'Modèle : étendre à 8:1 sans déformer le sujet ni rogner l’essentiel ; fond prolongé naturellement ; texte lisible ; style identique à l’original. Idem pour 16:9.',
    imgT: 'Aperçu visuel',
    imgAlt: 'Nano Banana 2 comme assistant design',
    imgC: 'Storyboard et multi-formats',
    startT: 'Commencer à créer',
    startx: 'Sur LimaxAI, utilisez Nano Banana 2 comme assistant design, retouche et adaptation pour accélérer la production de créas.',
    cta: 'Utiliser sur LimaxAI',
  },
  ru: {
    title: 'Nano Banana 2 как ассистент дизайна: сториборды, пакетная ретушь, несколько форматов',
    intro:
      'Используйте как ассистента, который понимает брифы на естественном языке: целые сториборды, унификация стиля пакетами и адаптация пропорций. Шаблоны для e-commerce на LimaxAI.',
    st: 'Большие сториборды за один раз',
    s1: 'Укажите число кадров (12/24/48), аудиторию, боль и продукт (ключевые выгоды). Вы переходите от «писать промпты» к «бриф + ревью».',
    s2: 'Шаблон: фотореалистичный рекламный сториборд сеткой 24 для ноутбука; варианты цвета и крупные планы. Или 12 кадров для авто: ночной город, технологичный салон, акцент на безопасность и запас хода.',
    s3: 'Вставьте URL референса бренда и попросите карточку в том же визуальном языке. Для маркетплейсов: «6 изображений в стиле Amazon». Для палатки: «6 изображений для карточки на Amazon US».',
    bt: 'Пакетная ретушь фото товара',
    b1: 'При множестве SKU нужен единый студийный вид. Загрузите много снимков и опишите: одно направление тени, чище блики, жёстче металл, чётче края, ровный светло-серый фон.',
    b2: 'Шаблон: пакетная ретушь, светло-серый фон студии; сохранить пропорции и структуру; чётче края; лучше текстура металла/пластика; ровные блики; согласованные тени; стабильный цвет; без чрезмерного сглаживания.',
    mt: 'Вывод в нескольких форматах',
    m1: 'Один креатив для 1:1, 4:5, 16:9 и 8:1 без полной ручной переверстки.',
    m2: 'Шаблон: расширить до 8:1 без искажения объекта и обрезки важного; фон естественно продолжается; текст читаем; стиль как в оригинале. То же для 16:9.',
    imgT: 'Пример изображения',
    imgAlt: 'Nano Banana 2 как ассистент дизайна',
    imgC: 'Сториборды и форматы',
    startT: 'Начать создание',
    startx: 'На LimaxAI используйте Nano Banana 2 как ассистента по дизайну, ретуши и адаптации, чтобы ускорить выпуск визуалов.',
    cta: 'Использовать на LimaxAI',
  },
  hi: {
    title: 'Nano Banana 2 डिज़ाइन सहायक: स्टोरीबोर्ड, बैच एडिट, मल्टी-साइज़',
    intro:
      'इसे सहज भाषा में ब्रीफ समझने वाला सहायक मानें: पूरे स्टोरीबोर्ड, बैच में एक जैसा स्टाइल, और अनुपात अनुकूलन। LimaxAI पर ई-कॉमर्स के लिए टेम्पलेट।',
    st: 'एक साथ बड़े स्टोरीबोर्ड',
    s1: 'पैनल संख्या (12/24/48), दर्शक, दर्द बिंदु और उत्पाद (मुख्य लाभ) बताएं। आप «प्रॉम्प्ट लिखने» से «ब्रीफ + रिव्यू» पर आ जाते हैं।',
    s2: 'टेम्पलेट: लैपटॉप के लिए 24-ग्रिड फोटोरियलिस्टिक विज्ञापन स्टोरीबोर्ड; रंग वेरिएंट और क्लोज़-अप। या कार के लिए 12 पैनल: शहर की रात, टेक इंटीरियर, सुरक्षा और रेंज पर फोकस।',
    s3: 'ब्रांड रेफरेंस URL चिपकाएं और उसी विज़ुअल भाषा में प्रोडक्ट पेज मांगें। मार्केटप्लेस: «Amazon-स्टाइल 6 इमेज।» टेंट: «US Amazon लिस्टिंग के लिए 6 इमेज।»',
    bt: 'उत्पाद फोटो बैच रिटच',
    b1: 'कई SKU पर स्टूडियो जैसा एक जैसा लुक चाहिए। कई फोटो अपलोड करें: एक जैसी छाया दिशा, साफ रिफ्लेक्शन, कड़ा मेटल, तेज किनारे, हल्का ग्रे एक समान बैकग्राउंड।',
    b2: 'टेम्पलेट: बैच रिटच, हल्का ग्रे स्टूडियो बैकग्राउंड; अनुपात और संरचना बरकरार; स्पष्ट किनारे; बेहतर मेटल/प्लास्टिक टेक्सचर; नियंत्रित रिफ्लेक्शन; सुसंगत छाया; स्थिर रंग; अति-स्मूदिंग नहीं।',
    mt: 'मल्टी-साइज़ आउटपुट',
    m1: '1:1, 4:5, 16:9 और 8:1 के लिए एक ही क्रिएटिव बिना पूरी मैनुअल रीलेआउट।',
    m2: 'टेम्पलेट: 8:1 तक बढ़ाएं—विषय विकृत न हो, ज़रूरी हिस्से कटें नहीं; पृष्ठभूमि प्राकृतिक रूप से फैले; टेक्स्ट पढ़ने योग्य; स्टाइल मूल जैसा। 16:9 के लिए भी।',
    imgT: 'नमूना छवि',
    imgAlt: 'Nano Banana 2 डिज़ाइन सहायक',
    imgC: 'स्टोरीबोर्ड और कई अनुपात',
    startT: 'बनाना शुरू करें',
    startx: 'LimaxAI पर Nano Banana 2 को डिज़ाइन + रिटच + अनुकूलन सहायक की तरह इस्तेमाल करें।',
    cta: 'LimaxAI पर उपयोग करें',
  },
  ja: {
    title: 'Nano Banana 2をデザインアシスタントに：ストーリーボード・一括レタッチ・マルチ比率',
    intro:
      '自然な言葉のブリーフを理解するアシスタントとして使う：一括でストーリーボード、バッチでスタイル統一、比率の最適化。LimaxAI向けECテンプレ付き。',
    st: '多パネルのストーリーボードを一度に',
    s1: 'パネル数（12/24/48）、ターゲット、課題、売るもの（主なベネフィット）を指定。「プロンプト執筆」から「ブリーフ＋レビュー」へ。',
    s2: '例：ノートPC向けフォトリアル24グリッド広告ストーリーボード。配色バリエーションとクローズアップ。または車12枚：都市の夜、テック内装、安全・航続を強調。',
    s3: 'ブランド参考URLを貼り同じビジュアル言語で商品ページを依頼。マーケットプレイスでは「Amazon型6枚」。テントなら「米Amazon出品用6枚」。',
    bt: '商品写真の一括レタッチ',
    b1: 'SKUが多いとスタジオ調の統一が必要。複数枚をアップし、影の方向統一、反射をクリーンに、金属を硬く、エッジをシャープに、明るいグレー背景で揃えると依頼。',
    b2: 'テンプレ：一括レタッチ、明るいグレー背景。比率・構造維持。エッジ強調。金属/プラ質感向上。反射・影を統一。色安定。過度のスムージングなし。',
    mt: 'マルチサイズ出力',
    m1: '1:1・4:5・16:9・8:1を手作業フル組版なしで回す。',
    m2: 'テンプレ：8:1へ拡張—被写体を歪ませず重要部を切らない。背景は自然に延長。文字読みやすく。元と同じトーン。16:9も同様。',
    imgT: 'サンプル画像',
    imgAlt: 'Nano Banana 2 デザインアシスタント',
    imgC: 'ストーリーボードとマルチサイズ',
    startT: '作成を始める',
    startx: 'LimaxAIでNano Banana 2をデザイン・レタッチ・適用アシスタントにしてクリエイティブ产量を上げる。',
    cta: 'LimaxAIで使う',
  },
  de: {
    title: 'Nano Banana 2 als Design-Assistent: Storyboards, Batch-Retusche, Mehrformat',
    intro:
      'Nutzen Sie es wie einen Assistenten für Briefings in Klartext: ganze Storyboards, Stil-Vereinheitlichung in Batches und Anpassung der Seitenverhältnisse. Fertige E-Commerce-Vorlagen auf LimaxAI.',
    st: 'Große Storyboards auf einmal',
    s1: 'Geben Sie Panelzahl (12/24/48), Zielgruppe, Schmerzpunkt und Produkt (Kernnutzen) an. Sie wechseln vom «Prompt schreiben» zu «Briefing + Review».',
    s2: 'Vorlage: fotorealistisches 24er-Grid-Werbestoryboard für einen Laptop; Farbvarianten und Nahaufnahmen. Oder 12 Panels Auto: Stadt bei Nacht, Tech-Cockpit, Fokus Sicherheit und Reichweite.',
    s3: 'Marken-Referenz-URL einfügen und Produktseite in diesem Look fordern. Für Marktplätze: «6 Amazon-ähnliche Bilder». Für Zelt: «6 Bilder für US-Amazon-Listing».',
    bt: 'Batch-Retusche für Produktfotos',
    b1: 'Bei vielen SKUs brauchen Sie einen einheitlichen Studio-Look. Viele Bilder hochladen und wünschen: gleiche Schattenrichtung, sauberere Spiegelungen, härteres Metall, schärfere Kanten, helles Grau als Hintergrund.',
    b2: 'Vorlage: Batch-Retusche, hellgrauer Studiohintergrund; Proportion und Struktur beibehalten; schärfere Kanten; bessere Metall-/Kunststofftextur; kontrollierte Spiegelungen; konsistente Schatten; stabile Farbe; kein Überglätten.',
    mt: 'Mehrgrößen-Output',
    m1: 'Ein Asset für 1:1, 4:5, 16:9 und 8:1 ohne komplette manuelle Neugestaltung.',
    m2: 'Vorlage: auf 8:1 erweitern ohne Motiv zu verzerren oder Wesentliches abzuschneiden; Hintergrund natürlich verlängern; Text lesbar; Stil wie das Original. Ebenso für 16:9.',
    imgT: 'Beispielbild',
    imgAlt: 'Nano Banana 2 als Design-Assistent',
    imgC: 'Storyboard und Formate',
    startT: 'Erstellen starten',
    startx: 'Nutzen Sie Nano Banana 2 auf LimaxAI als Design-, Retusche- und Format-Assistenten für mehr Output.',
    cta: 'Auf LimaxAI verwenden',
  },
  ko: {
    title: 'Nano Banana 2 디자인 어시스턴트: 스토리보드, 일괄 보정, 멀티 비율',
    intro:
      '자연어 브리프를 이해하는 어시스턴트처럼 쓰세요: 한 번에 스토리보드, 배치로 스타일 통일, 비율 맞춤. LimaxAI 전자상거래용 템플릿 포함.',
    st: '다패널 스토리보드 한 번에',
    s1: '패널 수(12/24/48), 타깃, 페인포인트, 제품(핵심 혜택)을 알려 주세요. «프롬프트 작성»에서 «브리프+검수»로 전환됩니다.',
    s2: '예: 노트북용 포토리얼 24그리드 광고 스토리보드, 컬러웨이·클로즈업. 또는 자동차 12컷: 야간 도시, 테크 실내, 안전·주행거리 강조.',
    s3: '브랜드 레퍼런스 URL을 붙여 같은 비주얼 언어로 상세 페이지를 요청하세요. 마켓플레이스: «아마존형 6장». 텐트: «미국 아마존 리스팅용 6장».',
    bt: '제품 사진 일괄 보정',
    b1: 'SKU가 많으면 스튜디오 룩이 일관되어야 합니다. 여러 장을 올리고 그림자 방향 통일, 반사 정리, 금속 질감 강화, 윤곽 선명, 밝은 회색 배경을 요청하세요.',
    b2: '템플릿: 일괄 보정, 밝은 회색 스튜디오 배경; 비율·구조 유지; 윤곽 선명; 금속/플라스틱 질감 개선; 반사·그림자 일관; 색 안정; 과도한 스무딩 금지.',
    mt: '멀티 사이즈 출력',
    m1: '1:1, 4:5, 16:9, 8:1에 같은 소재를 수작업 풀 재배치 없이.',
    m2: '템플릿: 8:1로 확장—피사체 왜곡·핵심 크롭 금지; 배경 자연 연장; 텍스트 가독; 원본과 동일 톤. 16:9도 동일.',
    imgT: '샘플 이미지',
    imgAlt: 'Nano Banana 2 디자인 어시스턴트',
    imgC: '스토리보드와 멀티 사이즈',
    startT: '제작 시작',
    startx: 'LimaxAI에서 Nano Banana 2를 디자인·보정·적용 어시스턴트로 써서 산출을 늘리세요.',
    cta: 'LimaxAI에서 사용',
  },
  tr: {
    title: 'Nano Banana 2 tasarım asistanı: storyboard, toplu rötuş, çoklu boyut',
    intro:
      'Doğal dilde brifleri anlayan bir asistan gibi kullanın: tam storyboard, toplu stil uyumu ve oran uyarlama. LimaxAI’da e-ticaret şablonları.',
    st: 'Çok panelli storyboard tek seferde',
    s1: 'Panel sayısı (12/24/48), kitle, sorun ve ürün (temel faydalar) belirtin. «Prompt yazmak» yerine «brif + inceleme» yaparsınız.',
    s2: 'Şablon: dizüstü için fotorealistik 24 ızgara reklam storyboard’u; renk varyantları ve yakın çekim. Ya da araba için 12 panel: gece şehir, teknolojik iç mekan, güvenlik ve menzil vurgusu.',
    s3: 'Marka referans URL’sini yapıştırıp aynı görsel dilde ürün sayfası isteyin. Pazar yerleri: «Amazon tarzı 6 görsel». Çadır: «ABD Amazon listesi için 6 görsel».',
    bt: 'Ürün fotoğrafı toplu rötuş',
    b1: 'Çok SKU’da stüdyo görünümü tutarlı olmalı. Birçok fotoğraf yükleyin: gölge yönü aynı, yansımalar daha temiz, metal daha sert, kenarlar daha keskin, açık gri arka plan.',
    b2: 'Şablon: toplu rötuş, açık gri stüdyo arka planı; oran ve yapı korunsun; net kenarlar; daha iyi metal/plastik dokusu; kontrollü yansımalar; tutarlı gölgeler; sabit renk; aşırı yumuşatma yok.',
    mt: 'Çoklu boyut çıktısı',
    m1: '1:1, 4:5, 16:9 ve 8:1 için aynı kreatif, tam el ile yeniden düzenleme olmadan.',
    m2: 'Şablon: 8:1’e uzat—özneyi bozma, önemli kısımları kesme; arka plan doğal uzasın; metin okunaklı; stil orijinalle aynı. 16:9 için de.',
    imgT: 'Örnek görsel',
    imgAlt: 'Nano Banana 2 tasarım asistanı',
    imgC: 'Storyboard ve çoklu boyut',
    startT: 'Oluşturmaya başla',
    startx: 'LimaxAI’da Nano Banana 2’yi tasarım + rötuş + uyarlama asistanı olarak kullanın.',
    cta: 'LimaxAI’da kullan',
  },
  vi: {
    title: 'Nano Banana 2 như trợ lý thiết kế: storyboard, chỉnh sửa hàng loạt, đa tỷ lệ',
    intro:
      'Coi như trợ lý hiểu brief ngôn ngữ tự nhiên: storyboard trọn bộ, đồng bộ phong cách theo lô, và chỉnh tỷ lệ. Mẫu sẵn cho thương mại điện tử trên LimaxAI.',
    st: 'Storyboard nhiều khung một lần',
    s1: 'Nêu số khung (12/24/48), đối tượng, điểm đau và sản phẩm (lợi ích chính). Bạn chuyển từ «viết prompt» sang «brief + duyệt».',
    s2: 'Mẫu: storyboard quảng cáo photorealistic lưới 24 cho laptop; nhiều màu và cận cảnh. Hoặc 12 khung xe: đêm phố, nội thất tech, nhấn an toàn và quãng đường.',
    s3: 'Dán URL tham chiếu thương hiệu và yêu cầu trang sản phẩm cùng ngôn ngữ hình ảnh. Sàn: «6 ảnh kiểu Amazon». Lều: «6 ảnh cho listing Amazon Mỹ».',
    bt: 'Chỉnh sửa hàng loạt ảnh sản phẩm',
    b1: 'Nhiều SKU cần phong cách studio nhất quán. Tải nhiều ảnh và yêu cầu: cùng hướng bóng, phản chiếu sạch hơn, kim loại cứng hơn, viền sắc nét, nền xám nhạt đều.',
    b2: 'Mẫu: chỉnh theo lô, nền studio xám nhạt; giữ tỷ lệ và cấu trúc; viền rõ hơn; kết cấu kim loại/nhựa tốt hơn; phản chiếu kiểm soát; bóng nhất quán; màu ổn định; không làm mịn quá mức.',
    mt: 'Đa kích thước',
    m1: 'Một bộ creative cho 1:1, 4:5, 16:9, 8:1 mà không dàn trang lại toàn bộ thủ công.',
    m2: 'Mẫu: mở rộng 8:1—không méo chủ thể, không cắt phần quan trọng; nền kéo dài tự nhiên; chữ đọc được; phong cách như bản gốc. Tương tự 16:9.',
    imgT: 'Ảnh mẫu',
    imgAlt: 'Nano Banana 2 trợ lý thiết kế',
    imgC: 'Storyboard và đa tỷ lệ',
    startT: 'Bắt đầu tạo',
    startx: 'Trên LimaxAI dùng Nano Banana 2 như trợ lý thiết kế, chỉnh và thích ứng để tăng sản lượng creative.',
    cta: 'Dùng trên LimaxAI',
  },
  th: {
    title: 'Nano Banana 2 เป็นผู้ช่วยออกแบบ: สตอรี่บอร์ด แก้เป็นชุด หลายสัดส่วน',
    intro:
      'ใช้เหมือนผู้ช่วยที่เข้าใจบรีฟภาษาพูด: สตอรี่บอร์ดเต็มชุด ปรับสไตล์เป็นชุด และปรับอัตราส่วน เทมเพลตอีคอมเมิร์ซบน LimaxAI',
    st: 'สตอรี่บอร์ดหลายเฟรมครั้งเดียว',
    s1: 'ระบุจำนวนเฟรม (12/24/48) กลุ่มเป้าหมาย ปัญหา และสินค้า (ประโยชน์หลัก) คุณเปลี่ยนจาก «เขียนพรอมป์» เป็น «บรีฟ + ตรวจ»',
    s2: 'ตัวอย่าง: สตอรี่บอร์ดโฆษณาโฟโตรีล 24 ช่องสำหรับโน้ตบุ๊ก สีหลากหลายและระยะใกล้ หรือ 12 เฟรมรถ: กลางคืนในเมือง ห้องโดยสารเทค เน้นความปลอดภัยและระยะทาง',
    s3: 'วาง URL อ้างอิงแบรนด์แล้วขอหน้าสินค้าด้วยภาษาภาพเดียวกัน สำหรับมาร์เก็ตเพลส: «6 ภาพสไตล์ Amazon» เต็นท์: «6 ภาพสำหรับลิสต์ Amazon สหรัฐ»',
    bt: 'รีทัชภาพสินค้าเป็นชุด',
    b1: 'SKU เยอะต้องได้ลุคสตูดิโอสม่ำเสมอ อัปโหลดหลายภาพแล้วขอ: ทิศเงาเดียวกัน เงาสะท้อนสะอาดขึ้น โลหะแข็งขึ้น ขอบคมขึ้น พื้นหลังเทาอ่อนสม่ำเสมอ',
    b2: 'เทมเพลต: รีทัชเป็นชุด พื้นหลังสตูดิโอเทาอ่อน คงสัดส่วนและโครงสร้าง ขอบชัด เนื้อผิวโลหะ/พลาสติกดีขึ้น ควบคุมเงาสะท้อน เงาสอดคล้อง สีคงที่ ไม่เกลี่ยเกินไป',
    mt: 'หลายสัดส่วน',
    m1: 'ครีเอทีฟเดียวสำหรับ 1:1 4:5 16:9 8:1 โดยไม่จัดวางใหม่ทั้งหมดด้วยมือ',
    m2: 'เทมเพลต: ขยายเป็น 8:1 โดยไม่บิดวัตถุและไม่ตัดส่วนสำคัญ พื้นหลังยืดตามธรรมชาติ ตัวอ่านออก สไตล์เหมือนต้นฉบับ เช่นเดียวกับ 16:9',
    imgT: 'ภาพตัวอย่าง',
    imgAlt: 'Nano Banana 2 ผู้ช่วยออกแบบ',
    imgC: 'สตอรี่บอร์ดและหลายสัดส่วน',
    startT: 'เริ่มสร้าง',
    startx: 'บน LimaxAI ใช้ Nano Banana 2 เป็นผู้ช่วยออกแบบ รีทัช และปรับรูปแบบเพื่อเพิ่มผลผลิต',
    cta: 'ใช้บน LimaxAI',
  },
  it: {
    title: 'Nano Banana 2 come assistente di design: storyboard, ritocco in batch, multi-formato',
    intro:
      'Usalo come assistente che capisce brief in linguaggio naturale: storyboard completi, uniformazione dello stile in batch e adattamento delle proporzioni. Template pronti per l’e-commerce su LimaxAI.',
    st: 'Storyboard multi-pannello in un colpo',
    s1: 'Indica numero di pannelli (12/24/48), pubblico, pain point e prodotto (benefici chiave). Passi da «scrivere prompt» a «brief + revisione».',
    s2: 'Modello: storyboard pubblicitario fotorealistico a griglia 24 per un laptop; varianti colore e primi piani. Oppure 12 pannelli auto: notte in città, interni tech, focus su sicurezza e autonomia.',
    s3: 'Incolla URL di riferimento brand e chiedi una scheda prodotto nello stesso linguaggio visivo. Per marketplace: «6 immagini stile Amazon». Per tenda: «6 immagini per listing Amazon US».',
    bt: 'Ritocco batch delle foto prodotto',
    b1: 'Con molti SKU serve un look da studio coerente. Carica molte foto e chiedi: stessa direzione ombra, riflessi più puliti, metallo più duro, bordi più netti, sfondo grigio chiaro uniforme.',
    b2: 'Modello: ritocco batch, sfondo grigio chiaro da studio; mantieni proporzioni e struttura; bordi più definiti; migliore texture metallo/plastica; riflessi controllati; ombre coerenti; colore stabile; niente oversmoothing.',
    mt: 'Output multi-formato',
    m1: 'Un solo creative per 1:1, 4:5, 16:9 e 8:1 senza rifare tutto il layout a mano.',
    m2: 'Modello: estendi a 8:1 senza deformare il soggetto o tagliare l’essenziale; sfondo esteso in modo naturale; testo leggibile; stile come l’originale. Stesso per 16:9.',
    imgT: 'Immagine di esempio',
    imgAlt: 'Nano Banana 2 assistente di design',
    imgC: 'Storyboard e multi-formato',
    startT: 'Inizia a creare',
    startx: 'Su LimaxAI usa Nano Banana 2 come assistente design, ritocco e adattamento per aumentare la produzione.',
    cta: 'Usa su LimaxAI',
  },
  fa: {
    title: 'نانو بانانا ۲ به‌عنوان دستیار طراحی: استوری‌بورد، ویرایش دسته‌ای، چند نسبت',
    intro:
      'مثل دستیاری که بریف را به زبان ساده می‌فهمد استفاده کنید: استوری‌بورد کامل، یکدست‌سازی استایل به‌صورت دسته‌ای و تطبیق نسبت. قالب‌های آماده برای تجارت الکترونیک در LimaxAI.',
    st: 'استوری‌برد چند پنل یکجا',
    s1: 'تعداد پنل (۱۲/۲۴/۴۸)، مخاطب، نقطه درد و محصول (مزایای کلیدی) را بگویید. از «نوشتن پرامپت» به «بریف + بازبینی» می‌روید.',
    s2: 'الگو: استوری‌بورد تبلیغاتی فوتورئالیستی ۲۴ خانه برای لپ‌تاپ؛ رنگ‌های متنوع و نمای نزدیک. یا ۱۲ پنل خودرو: شب شهری، کابین تکنولوژیک، تمرکز بر ایمنی و برد.',
    s3: 'URL مرجع برند را بچسبانید و صفحه محصول با همان زبان بصری بخواهید. برای مارکت‌پلیس: «۶ تصویر شبیه آمازون». برای چادر: «۶ تصویر برای لیستینگ آمازون آمریکا».',
    bt: 'رتوش دسته‌ای عکس محصول',
    b1: 'با SKU زیاد به ظاهر استودیویی یکدست نیاز دارید. چند عکس بارگذاری کنید: جهت سایه یکسان، بازتاب تمیزتر، فلز سخت‌تر، لبه‌های تیزتر، پس‌زمینه خاکستری روشن یکنواخت.',
    b2: 'الگو: رتوش دسته‌ای، پس‌زمینه خاکستری روشن استودیویی؛ حفظ نسبت و ساختار؛ لبه‌های واضح‌تر؛ بافت فلز/پلاستیک بهتر؛ بازتاب کنترل‌شده؛ سایه‌های هماهنگ؛ رنگ پایدار؛ بدون نرم‌کردن بیش از حد.',
    mt: 'خروجی چند سایز',
    m1: 'یک خروجی خلاقانه برای ۱:۱، ۴:۵، ۱۶:۹ و ۸:۱ بدون چیدمان مجدد کامل دستی.',
    m2: 'الگو: گسترش به ۸:۱ بدون اعوجاج سوژه و برش بخش‌های مهم؛ پس‌زمینه به‌صورت طبیعی ادامه یابد؛ متن خوانا؛ سبک مانند اصل. همین برای ۱۶:۹.',
    imgT: 'تصویر نمونه',
    imgAlt: 'نانو بانانا ۲ دستیار طراحی',
    imgC: 'استوری‌بورد و چند نسبت',
    startT: 'شروع ساخت',
    startx: 'در LimaxAI از نانو بانانا ۲ به‌عنوان دستیار طراحی، رتوش و تطبیق استفاده کنید.',
    cta: 'استفاده در LimaxAI',
  },
  nl: {
    title: 'Nano Banana 2 als ontwerp-assistent: storyboards, batch-retouche, meerdere formaten',
    intro:
      'Gebruik het als assistent die natuurlijke briefing begrijpt: volledige storyboards, stijluniformering in batches en aanpassing van verhoudingen. Kant-en-klare e-commerce-sjablonen op LimaxAI.',
    st: 'Grote storyboards in één keer',
    s1: 'Geef aantal panelen (12/24/48), doelgroep, pijnpunt en product (kernvoordelen) op. Je gaat van «prompts schrijven» naar «briefing + review».',
    s2: 'Sjabloon: fotorealistisch 24-raster advertentiestoryboard voor een laptop; kleurvarianten en close-ups. Of 12 panelen auto: stadsnacht, tech-interieur, focus op veiligheid en bereik.',
    s3: 'Plak merk-URL en vraag een productpagina in dezelfde visuele taal. Voor marketplaces: «6 Amazon-achtige beelden». Voor tent: «6 beelden voor US Amazon-listing».',
    bt: 'Batch-retouche productfoto’s',
    b1: 'Met veel SKU’s heb je een consistente studiolook nodig. Upload veel foto’s en vraag: dezelfde schaduwrichting, schonere reflecties, harder metaal, scherpere randen, lichtgrijze achtergrond.',
    b2: 'Sjabloon: batch-retouche, lichtgrijze studioachtergrond; behoud verhouding en structuur; scherpere randen; betere metaal-/plastic-textuur; gecontroleerde reflecties; consistente schaduwen; stabiele kleur.',
    mt: 'Multi-formaat output',
    m1: 'Eén creative voor 1:1, 4:5, 16:9 en 8:1 zonder volledige handmatige herindeling.',
    m2: 'Sjabloon: uitbreiden naar 8:1 zonder onderwerp te vervormen of essentie te croppen; achtergrond natuurlijk verlengd; tekst leesbaar; stijl als origineel. Zelfde voor 16:9.',
    imgT: 'Voorbeeldafbeelding',
    imgAlt: 'Nano Banana 2 ontwerp-assistent',
    imgC: 'Storyboard en formaten',
    startT: 'Beginnen met maken',
    startx: 'Gebruik Nano Banana 2 op LimaxAI als ontwerp-, retouche- en aanpassingsassistent.',
    cta: 'Gebruiken op LimaxAI',
  },
  pl: {
    title: 'Nano Banana 2 jako asystent projektowy: storyboardy, retusz wsadowy, wiele formatów',
    intro:
      'Traktuj go jak asystenta rozumiejącego briefing w naturalnym języku: pełne storyboardy, ujednolicanie stylu wsadowo i dopasowanie proporcji. Gotowe szablony e-commerce na LimaxAI.',
    st: 'Duże storyboardy naraz',
    s1: 'Podaj liczbę paneli (12/24/48), odbiorców, problem i produkt (kluczowe korzyści). Przechodzisz od «pisanie promptów» do «brief + recenzja».',
    s2: 'Szablon: fotorealistyczny storyboard reklamowy w siatce 24 dla laptopa; warianty kolorystyczne i zbliżenia. Albo 12 paneli auta: nocne miasto, wnętrze tech, nacisk na bezpieczeństwo i zasięg.',
    s3: 'Wklej URL referencyjny marki i poproś o stronę produktu w tym samym języku wizualnym. Dla marketplace: «6 obrazów w stylu Amazon». Dla namiotu: «6 obrazów na listing Amazon US».',
    bt: 'Seria retuszy zdjęć produktu',
    b1: 'Przy wielu SKU potrzebujesz spójnego studia. Wgraj wiele zdjęć i poproś: ten sam kierunek cienia, czystsze odbicia, twardszy metal, ostrzejsze krawędzie, jasnoszare tło.',
    b2: 'Szablon: retusz wsadowy, jasnoszare tło studyjne; zachowaj proporcje i strukturę; wyraźniejsze krawędzie; lepsza tekstura metalu/plastiku; kontrolowane odbicia; spójne cienie; stabilny kolor.',
    mt: 'Wiele formatów wyjściowych',
    m1: 'Jeden kreatyw na 1:1, 4:5, 16:9 i 8:1 bez pełnej ręcznej przebudowy.',
    m2: 'Szablon: rozszerz do 8:1 bez zniekształcania obiektu i bez wycinania kluczowych elementów; tło naturalnie przedłużone; tekst czytelny; styl jak oryginał. To samo dla 16:9.',
    imgT: 'Obraz przykładowy',
    imgAlt: 'Nano Banana 2 asystent projektowy',
    imgC: 'Storyboard i formaty',
    startT: 'Zacznij tworzyć',
    startx: 'Na LimaxAI używaj Nano Banana 2 jako asystenta designu, retuszu i adaptacji.',
    cta: 'Użyj na LimaxAI',
  },
  sv: {
    title: 'Nano Banana 2 som designassistent: storyboards, batch-retusch, flera format',
    intro:
      'Använd det som en assistent som förstår briefs på vardagsspråk: hela storyboards, stilförenlighet i batch och anpassning av proportioner. Färdiga e-handelsmallar på LimaxAI.',
    st: 'Stora storyboards på en gång',
    s1: 'Ange antal paneler (12/24/48), målgrupp, smärtpunkter och produkt (nyckelfördelar). Du går från «skriva prompter» till «brief + granskning».',
    s2: 'Mall: fotorealistiskt 24-rutnät annonsstoryboard för en laptop; färgvarianter och närbilder. Eller 12 paneler bil: stad på natten, tech-interiör, fokus på säkerhet och räckvidd.',
    s3: 'Klistra in varumärkes-URL och be om en produktsida i samma visuella språk. För marknadsplatser: «6 Amazon-liknande bilder». För tält: «6 bilder för US Amazon-listning».',
    bt: 'Batch-retusch av produktbilder',
    b1: 'Med många SKU behövs en enhetlig studiokänsla. Ladda upp många bilder och be om: samma skuggriktning, renare reflexer, hårdare metall, skarpare kanter, ljusgrå bakgrund.',
    b2: 'Mall: batch-retusch, ljusgrå studiobakgrund; behåll proportion och struktur; skarpare kanter; bättre metall-/plasttextur; kontrollerade reflexer; konsekventa skuggor; stabil färg.',
    mt: 'Flerformatutdata',
    m1: 'En creative för 1:1, 4:5, 16:9 och 8:1 utan full manuell omlayout.',
    m2: 'Mall: utöka till 8:1 utan att förvränga motivet eller beskära det viktiga; bakgrund förlängs naturligt; text läsbar; stil som originalet. Samma för 16:9.',
    imgT: 'Exempelbild',
    imgAlt: 'Nano Banana 2 designassistent',
    imgC: 'Storyboard och format',
    startT: 'Börja skapa',
    startx: 'Använd Nano Banana 2 på LimaxAI som design-, retusch- och anpassningsassistent.',
    cta: 'Använd på LimaxAI',
  },
  uk: {
    title: 'Nano Banana 2 як асистент дизайну: сториборди, пакетне ретушування, кілька форматів',
    intro:
      'Використовуйте як асистента, який розуміє брифи природною мовою: повні сториборди, уніфікація стилю пакетами й адаптація пропорцій. Шаблони для e-commerce на LimaxAI.',
    st: 'Великі сториборди за раз',
    s1: 'Вкажіть кількість кадрів (12/24/48), аудиторію, біль і продукт (ключові вигоди). Переходите від «писати промпти» до «бриф + рев’ю».',
    s2: 'Шаблон: фотореалістичний рекламний сториборд сіткою 24 для ноутбука; варіанти кольору та крупні плани. Або 12 кадрів авто: нічне місто, tech-салон, акцент на безпеку та запас ходу.',
    s3: 'Вставте URL референсу бренду й попросіть картку товару тією ж візуальною мовою. Для маркетплейсів: «6 зображень у стилі Amazon». Для намету: «6 зображень для картки на Amazon US».',
    bt: 'Пакетне ретушування фото товару',
    b1: 'З багатьма SKU потрібен єдиний студійний вигляд. Завантажте багато знімків і опишіть: один напрям тіні, чистіші відблиски, жорсткіший метал, чіткіші краї, рівне світло-сіре тло.',
    b2: 'Шаблон: пакетне ретушування, світло-сіре студійне тло; зберегти пропорції й структуру; чіткіші краї; краща текстура металу/пластику; контрольовані відблиски; узгоджені тіні; стабільний колір.',
    mt: 'Вихід у кількох форматах',
    m1: 'Один креатив для 1:1, 4:5, 16:9 та 8:1 без повної ручної переверстки.',
    m2: 'Шаблон: розширити до 8:1 без спотворення об’єкта й без обрізання важливого; фон природно продовжується; текст читабельний; стиль як в оригіналі. Те саме для 16:9.',
    imgT: 'Приклад зображення',
    imgAlt: 'Nano Banana 2 асистент дизайну',
    imgC: 'Сториборди та формати',
    startT: 'Почати створення',
    startx: 'На LimaxAI використовуйте Nano Banana 2 як асистента з дизайну, ретуші та адаптації.',
    cta: 'Використати на LimaxAI',
  },
  ro: {
    title: 'Nano Banana 2 ca asistent de design: storyboard-uri, retușare în lot, multi-format',
    intro:
      'Folosește-l ca pe un asistent care înțelege briefuri în limbaj natural: storyboard-uri complete, uniformizare de stil în lot și adaptarea proporțiilor. Șabloane gata pentru e-commerce pe LimaxAI.',
    st: 'Storyboard-uri mari dintr-o dată',
    s1: 'Indică numărul de panouri (12/24/48), publicul, problema și produsul (beneficii cheie). Treci de la «a scrie prompturi» la «brief + revizuire».',
    s2: 'Șablon: storyboard publicitar fotorealist în grilă 24 pentru un laptop; variante de culoare și close-up. Sau 12 panouri auto: noapte urbană, interior tech, accent pe siguranță și autonomie.',
    s3: 'Lipește URL de referință de brand și cere o pagină de produs în același limbaj vizual. Pentru marketplace: «6 imagini în stil Amazon». Pentru cort: «6 imagini pentru listare Amazon SUA».',
    bt: 'Retușare în lot pentru poze produs',
    b1: 'Cu multe SKU ai nevoie de un look de studio coerent. Încarcă multe fotografii și cere: aceeași direcție a umbrei, reflexii mai curate, metal mai dur, margini mai clare, fundal gri deschis uniform.',
    b2: 'Șablon: retușare în lot, fundal studio gri deschis; păstrează proporția și structura; margini mai definite; textură metal/plastic mai bună; reflexii controlate; umbre coerente; culoare stabilă.',
    mt: 'Ieșire multi-format',
    m1: 'Un singur creative pentru 1:1, 4:5, 16:9 și 8:1 fără re-layout manual complet.',
    m2: 'Șablon: extinde la 8:1 fără a deforma subiectul sau a decupa esențialul; fundal prelungit natural; text lizibil; stil ca originalul. La fel pentru 16:9.',
    imgT: 'Imagine exemplu',
    imgAlt: 'Nano Banana 2 asistent de design',
    imgC: 'Storyboard și formate',
    startT: 'Începe crearea',
    startx: 'Pe LimaxAI folosește Nano Banana 2 ca asistent design, retuș și adaptare.',
    cta: 'Folosește pe LimaxAI',
  },
};

const nanobanana2LaunchExtraLocales: Record<string, Nb2LaunchExtra> = {
  es: {
    title: 'Google presenta Nano Banana 2: pruébalo ya',
    intro:
      'Nano Banana 2 se apoya en Gemini 3.1 Flash Image y destaca por su potencia. Aquí tres capacidades: búsqueda web en tiempo real, coherencia del sujeto y tipografía multilingüe con diseño gráfico, con ejemplos de prompts para LimaxAI.',
    rt: 'Búsqueda web en tiempo real',
    r1: 'Puede «mirar» la web antes de dibujar. Ejemplo: fotos reales del castillo de Clos Lucé reinterpretadas en cubismo sintético vivo; infografía de negocio sobre Nano Banana 2; hito moderno al estilo Ghibli.',
    ct: 'Coherencia del sujeto para series',
    c1: 'Ejemplo: misma mujer asiática de 20 años (boina roja, gafas redondas, gabardina beige) en Tokio lluvioso con paraguas transparente, biblioteca al atardecer y selfie ante la Torre Eiffel de noche. 16:9, rostro y ropa coherentes, estilo tipo Leica.',
    tt: 'Tipografía y diseño gráfico multilingüe',
    t1: 'Buen manejo de varios sistemas de escritura. Ejemplo: tipograma «深圳» con elementos urbanos en los trazos; cartel 3:2 con un lema largo para redes; póster tipo Bento Grid (p. ej. guía de alimentación) con jerarquía clara.',
    imgT: 'Muestra visual',
    imgAlt: 'Capacidades de Nano Banana 2',
    imgC: 'Resumen de capacidades',
    startT: 'Empezar a crear',
    startx: 'Rápido, 4K, consciente de la web, tipografía sólida y personajes coherentes. De juguete a productividad real en LimaxAI.',
    cta: 'Usar en LimaxAI',
  },
  ar: {
    title: 'نانو بانانا 2 من Google جرّبه الآن',
    intro:
      'نانو بانانا 2 مبني على Gemini 3.1 Flash Image ويبرز بقوته. ثلاث قدرات: بحث ويب لحظي، تماسك الشخصية، وطباعة متعددة اللغات مع تصميم جرافيكي، مع أمثلة للبدء على LimaxAI.',
    rt: 'بحث ويب في الوقت الفعلي',
    r1: 'يمكنه «النظر» إلى الويب قبل الرسم. مثال: صور حقيقية لقلعة كلو لوسيه بأسلوب تكعيبي تركيبي حي؛ إنفوجرافيك أعمال عن النموذج؛ معلم حديث بأسلوب جيبلي.',
    ct: 'تماسك الشخصية لمسلسلات ومحتوى',
    c1: 'مثال: نفس امرأة آسيوية 20 سنة (بيريه أحمر، نظارات دائرية، معطف بيج) في ثلاث مشاهد: طوكيو الممطرة بمظلة شفافة، مكتبة عند الغروب، سيلفي ليلاً عند برج إيفل. 16:9، وجه وملابس ثابتان، أسلوب تصوير يشبه Leica.',
    tt: 'طباعة وتصميم جرافيكي متعدد اللغات',
    t1: 'يتعامل جيداً مع أنظمة كتابة متعددة. مثال: تصميم حروف «深圳» بعناصر مدنية في الحدود؛ ملصق 3:2 بعبارة طويلة للشبكات؛ ملصق Bento Grid (مثل دليل غذاء) بتسلسل واضح.',
    imgT: 'صورة توضيحية',
    imgAlt: 'قدرات نانو بانانا 2',
    imgC: 'ملخص القدرات',
    startT: 'ابدأ الإنشاء',
    startx: 'سريع، 4K، واعٍ للويب، طباعة قوية وشخصيات متسقة. من لعبة إلى إنتاجية على LimaxAI.',
    cta: 'استخدام على LimaxAI',
  },
  pt: {
    title: 'O Nano Banana 2 do Google chegou — experimente',
    intro:
      'O Nano Banana 2 usa a stack Gemini 3.1 Flash Image e chama atenção pela força. Três capacidades: pesquisa web em tempo real, consistência do sujeito e tipografia multilíngue com design gráfico, com exemplos para LimaxAI.',
    rt: 'Pesquisa web em tempo real',
    r1: 'Pode «olhar» a web antes de gerar. Exemplo: fotos reais do Château du Clos Lucé reinterpretadas em cubismo sintético vivo; infográfico de negócios sobre o modelo; marco moderno estilo Ghibli.',
    ct: 'Consistência do sujeito para séries',
    c1: 'Exemplo: a mesma mulher asiática de 20 anos (boina vermelha, óculos redondos, gabardina bege) em três cenas: Tóquio chuvosa com guarda-chuva transparente, biblioteca ao entardecer, selfie à noite na Torre Eiffel. 16:9, rosto e roupa coerentes, estilo tipo Leica.',
    tt: 'Tipografia e design gráfico multilíngue',
    t1: 'Bom com vários sistemas de escrita. Exemplo: tipografia «深圳» com elementos urbanos nos traços; cartaz 3:2 com frase longa para redes; pôster Bento Grid (ex.: guia alimentar) com hierarquia clara.',
    imgT: 'Referência visual',
    imgAlt: 'Capacidades do Nano Banana 2',
    imgC: 'Visão geral das capacidades',
    startT: 'Começar a criar',
    startx: 'Rápido, 4K, consciente da web, tipografia forte e personagens consistentes. De brinquedo a produtividade no LimaxAI.',
    cta: 'Usar no LimaxAI',
  },
  id: {
    title: 'Nano Banana 2 dari Google sudah hadir — coba sekarang',
    intro:
      'Nano Banana 2 memakai stack Gemini 3.1 Flash Image dan menonjol karena kekuatannya. Tiga kemampuan: pencarian web real-time, konsistensi subjek, dan tipografi multibahasa dengan desain grafis, plus contoh untuk LimaxAI.',
    rt: 'Pencarian web real-time',
    r1: 'Bisa «melihat» web sebelum menggambar. Contoh: foto nyata Château du Clos Lucé dalam kubisme sintetis yang hidup; infografis bisnis tentang model; landmark modern bergaya Ghibli.',
    ct: 'Konsistensi subjek untuk serial',
    c1: 'Contoh: wanita Asia 20 tahun yang sama (baret merah, kacamata bulat, trench beige) dalam tiga adegan: Tokyo hujan payung transparan, perpustakaan sore, selfie malam di Menara Eiffel. 16:9, wajah dan pakaian konsisten, gaya foto mirip Leica.',
    tt: 'Tipografi dan desain grafis multibahasa',
    t1: 'Menangani beberapa sistem penulisan dengan baik. Contoh: tipografi «深圳» dengan elemen kota dalam guratan; poster 3:2 dengan kalimat panjang untuk sosial; poster Bento Grid (mis. panduan makan) dengan hierarki jelas.',
    imgT: 'Contoh gambar',
    imgAlt: 'Kemampuan Nano Banana 2',
    imgC: 'Ringkasan kemampuan',
    startT: 'Mulai membuat',
    startx: 'Cepat, 4K, sadar web, tipografi kuat, karakter konsisten. Dari mainan menjadi produktivitas di LimaxAI.',
    cta: 'Gunakan di LimaxAI',
  },
  ms: {
    title: 'Nano Banana 2 Google sudah ada — cuba sekarang',
    intro:
      'Nano Banana 2 dibina pada Gemini 3.1 Flash Image dan menonjol dengan kekuatannya. Tiga keupayaan: carian web masa nyata, konsisten subjek, dan tipografi pelbagai bahasa dengan reka bentuk grafik, serta contoh untuk LimaxAI.',
    rt: 'Carian web masa nyata',
    r1: 'Boleh «lihat» web sebelum menjana. Contoh: foto sebenar Château du Clos Lucé dalam kubisme sintetik yang hidup; infografik perniagaan tentang model; mercu tanda moden gaya Ghibli.',
    ct: 'Konsisten subjek untuk siri',
    c1: 'Contoh: wanita Asia sama berumur 20 tahun (bare merah, cermin mata bulat, trench beige) dalam tiga adegan: Tokyo hujan dengan payung lutsinar, perpustakaan petang, selfie malam di Menara Eiffel. 16:9, wajah dan pakaian konsisten, gaya foto seperti Leica.',
    tt: 'Tipografi dan reka bentuk grafik pelbagai bahasa',
    t1: 'Mengendalikan pelbagai sistem tulisan dengan baik. Contoh: tipografi «深圳» dengan elemen bandar dalam goresan; poster 3:2 dengan ayat panjang untuk sosial; poster Bento Grid (cth. panduan pemakanan) dengan hierarki jelas.',
    imgT: 'Imej rujukan',
    imgAlt: 'Keupayaan Nano Banana 2',
    imgC: 'Ringkasan keupayaan',
    startT: 'Mula mencipta',
    startx: 'Pantas, 4K, sedar web, tipografi kukuh, watak konsisten. Daripada mainan kepada produktiviti di LimaxAI.',
    cta: 'Guna di LimaxAI',
  },
  fr: {
    title: 'Nano Banana 2 par Google est là — essayez',
    intro:
      'Nano Banana 2 repose sur la stack Gemini 3.1 Flash Image et impressionne par sa puissance. Trois capacités : recherche web en temps réel, cohérence du sujet, typographie multilingue et design graphique, avec exemples pour LimaxAI.',
    rt: 'Recherche web en temps réel',
    r1: 'Il peut « consulter » le web avant de générer. Exemple : photos réelles du château du Clos Lucé réinterprétées en cubisme synthétique vif ; infographie business sur le modèle ; monument moderne style Ghibli.',
    ct: 'Cohérence du sujet pour les séries',
    c1: 'Exemple : la même femme asiatique de 20 ans (béret rouge, lunettes rondes, trench beige) dans trois scènes : Tokyo pluvieux avec parapluie transparent, bibliothèque en fin d’après-midi, selfie nocturne devant la tour Eiffel. 16:9, visage et tenue cohérents, rendu type Leica.',
    tt: 'Typographie et design graphique multilingues',
    t1: 'Gère bien plusieurs systèmes d’écriture. Exemple : lettrage «深圳» avec éléments urbains dans les traits ; affiche 3:2 avec une phrase longue pour les réseaux ; affiche Bento Grid (ex. guide alimentaire) avec hiérarchie claire.',
    imgT: 'Aperçu visuel',
    imgAlt: 'Capacités de Nano Banana 2',
    imgC: 'Vue d’ensemble',
    startT: 'Commencer à créer',
    startx: 'Rapide, 4K, sensible au web, forte typographie, personnages cohérents. Du gadget à la productivité sur LimaxAI.',
    cta: 'Utiliser sur LimaxAI',
  },
  ru: {
    title: 'Nano Banana 2 от Google уже здесь — попробуйте',
    intro:
      'Nano Banana 2 построен на Gemini 3.1 Flash Image и выделяется силой. Три возможности: поиск в вебе в реальном времени, согласованность персонажа и многоязычная типографика с графдизайном, с примерами для LimaxAI.',
    rt: 'Поиск в интернете в реальном времени',
    r1: 'Может «посмотреть» веб перед генерацией. Пример: реальные фото замка Кло-Люсе в ярком синтетическом кубизме; деловая инфографика о модели; современная достопримечательность в духе Ghibli.',
    ct: 'Согласованность персонажа для серий',
    c1: 'Пример: та же 20-летняя азиатская женщина (красный берет, круглые очки, бежевый тренч) в трёх сценах: дождливый Токио с прозрачным зонтом, библиотека к вечеру, ночное селфи у Эйфелевой башни. 16:9, лицо и одежда стабильны, стиль фото как у Leica.',
    tt: 'Многоязычная типографика и графдизайн',
    t1: 'Хорошо работает с разными письменностями. Пример: буквы «深圳» с городскими мотивами в штрихах; постер 3:2 с длинной фразой для соцсетей; Bento Grid-постер (напр. гид по питанию) с чёткой иерархией.',
    imgT: 'Пример изображения',
    imgAlt: 'Возможности Nano Banana 2',
    imgC: 'Обзор возможностей',
    startT: 'Начать создание',
    startx: 'Быстро, 4K, учёт веба, сильная типографика, стабильные персонажи. От игрушки к продуктивности на LimaxAI.',
    cta: 'Использовать на LimaxAI',
  },
  hi: {
    title: 'Google का Nano Banana 2 आ गया — अभी आज़माएँ',
    intro:
      'Nano Banana 2 नई Gemini 3.1 Flash Image स्टैक पर है और अपनी ताकत से ध्यान खींचता है। तीन मुख्य क्षमताएँ: रियल-टाइम वेब खोज, विषय की स्थिरता, और बहुभाषी टाइपोग्राफी व ग्राफ़िक डिज़ाइन—LimaxAI पर उदाहरणों के साथ।',
    rt: 'रीयल-टाइम वेब खोज',
    r1: 'जनरेट से पहले वेब «देख» सकता है। उदाहरण: क्लो ल्यूसे महल की असली तस्वीरें जीवंत सिंथेटिक क्यूबिज़्म में; मॉडल पर बिज़नेस इन्फोग्राफ़िक; Ghibli-स्टाइल आधुनिक लैंडमार्क।',
    ct: 'सीरीज़ के लिए विषय की स्थिरता',
    c1: 'उदाहरण: वही 20 साल की एशियाई महिला (लाल बेरेट, गोल चश्मा, बेज ट्रेंच)—तीन दृश्य: बारिश वाला टोक्यो पारदर्शी छाता, शाम की लाइब्रेरी, रात में आइफ़ेल टावर पर सेल्फ़ी। 16:9, चेहरा-कपड़े समान, Leica जैसी फ़ोटोग्राफ़ी।',
    tt: 'बहुभाषी टाइपोग्राफी और ग्राफ़िक डिज़ाइन',
    t1: 'कई लिपियों को अच्छा हैंडल करता है। उदाहरण: «深圳» लेटरिंग में शहरी तत्व; सोशल के लिए 3:2 पोस्टर लंबी पंक्ति के साथ; Bento Grid पोस्टर (जैसे खाने की गाइड) साफ़ हैरार्की के साथ।',
    imgT: 'नमूना छवि',
    imgAlt: 'Nano Banana 2 क्षमताएँ',
    imgC: 'क्षमताओं का सार',
    startT: 'बनाना शुरू करें',
    startx: 'तेज़, 4K, वेब-जागरूक, मज़बूत टाइपोग्राफी, स्थिर पात्र। LimaxAI पर खिलौने से उत्पादकता तक।',
    cta: 'LimaxAI पर उपयोग करें',
  },
  ja: {
    title: 'GoogleのNano Banana 2登場——今すぐ試そう',
    intro:
      'Nano Banana 2は新しいGemini 3.1 Flash Image基盤で、実力が注目されています。リアルタイムWeb検索・被写体の一貫性・多言語タイポグラフィとグラフィックデザインの3点を、LimaxAI向け例付きで紹介します。',
    rt: 'リアルタイムWeb検索',
    r1: '生成前にWebを「見に行ける」。例：クロ・リュセ城の実写真を鮮やかな総合立体主義風に再解釈；モデル紹介のビジネス向けインフォグラフィック；ジブリ風の現代ランドマーク。',
    ct: 'シリーズ制作向けの被写体一貫性',
    c1: '例：同じ20代アジア人女性（赤ベレー、丸眼鏡、ベージュトレンチ）を3シーンに——雨の東京と透明傘、夕方の図書館、夜のエッフェル塔前の自撮り。16:9、顔と服を揃えたLeica調写真。',
    tt: '多言語タイポグラフィとグラフィックデザイン',
    t1: '複数の文字体系に強い。例：「深圳」の文字に都市モチーフを笔画へ；長いコピー付き3:2のSNS向けポスター；Bento Grid型インフォグラフィック（食事ガイドなど）で明確な階層。',
    imgT: 'サンプル画像',
    imgAlt: 'Nano Banana 2の能力',
    imgC: '能力の概要',
    startT: '作成を始める',
    startx: '高速、4K、検索を意識、タイポ強化、人物一貫。おもちゃから本番の生産性へ——LimaxAIで。',
    cta: 'LimaxAIで使う',
  },
  de: {
    title: 'Googles Nano Banana 2 ist da — jetzt testen',
    intro:
      'Nano Banana 2 basiert auf dem neuen Gemini-3.1-Flash-Image-Stack und fällt durch Stärke auf. Drei Kernfähigkeiten: Echtzeit-Websuche, Subjektkonsistenz und mehrsprachige Typografie mit Grafikdesign — mit Beispielen für LimaxAI.',
    rt: 'Echtzeit-Websuche',
    r1: 'Kann vor der Generierung im Web «nachsehen». Beispiel: echte Fotos von Château du Clos Lucé in lebendigem synthetischem Kubismus; Business-Infografik zum Modell; moderner Wahrzeichen-Look im Ghibli-Stil.',
    ct: 'Subjektkonsistenz für Serien',
    c1: 'Beispiel: dieselbe 20-jährige asiatische Frau (rote Baskenmütze, runde Brille, beiger Trench) in drei Szenen: regnerisches Tokio mit transparentem Schirm, Bibliothek am späten Nachmittag, Nacht-Selfie vor dem Eiffelturm. 16:9, Gesicht und Outfit konsistent, Leica-ähnlicher Fotostil.',
    tt: 'Mehrsprachige Typografie und Grafikdesign',
    t1: 'Gut mit verschiedenen Schriftsystemen. Beispiel: Schriftzug «深圳» mit urbanen Elementen in den Strichen; 3:2-Poster mit langem Text für Social; Bento-Grid-Poster (z. B. Ernährungsguide) mit klarer Hierarchie.',
    imgT: 'Beispielbild',
    imgAlt: 'Fähigkeiten von Nano Banana 2',
    imgC: 'Überblick',
    startT: 'Erstellen starten',
    startx: 'Schnell, 4K, webbewusst, starke Typografie, konsistente Figuren. Vom Spielzeug zur Produktivität auf LimaxAI.',
    cta: 'Auf LimaxAI verwenden',
  },
  ko: {
    title: 'Google의 Nano Banana 2 출시 — 지금 써 보세요',
    intro:
      'Nano Banana 2는 새 Gemini 3.1 Flash Image 스택을 기반으로 강력한 성능으로 주목받습니다. 실시간 웹 검색, 피사체 일관성, 다국어 타이포그래피와 그래픽 디자인 세 가지를 LimaxAI 예시와 함께 소개합니다.',
    rt: '실시간 웹 검색',
    r1: '생성 전에 웹을 «살펴볼» 수 있습니다. 예: 클로 뤼세 성의 실사를 선명한 종합 입체파로 재해석; 모델 소개 비즈니스 인포그래픽; 지브리풍 현대 랜드마크.',
    ct: '시리즈용 피사체 일관성',
    c1: '예: 동일한 20대 아시아 여성(빨간 베레모, 둥근 안경, 베이지 트렌치) 세 장면—우산 든 비 오는 도쿄, 늦은 오후 도서관, 밤 에펠탑 앞 셀카. 16:9, 얼굴·의상 일치, Leica 느낌 사진.',
    tt: '다국어 타이포그래피와 그래픽 디자인',
    t1: '여러 문자 체계를 잘 다룹니다. 예: 「深圳」 레터링에 도시 요소를 획에; 긴 문구가 있는 3:2 SNS 포스터; Bento Grid 인포그래픽(식단 가이드 등) 명확한 위계.',
    imgT: '샘플 이미지',
    imgAlt: 'Nano Banana 2 기능',
    imgC: '기능 요약',
    startT: '제작 시작',
    startx: '빠르고 4K, 웹 인식, 타이포 강화, 캐릭터 일관. 장난감에서 생산성으로—LimaxAI에서.',
    cta: 'LimaxAI에서 사용',
  },
  tr: {
    title: 'Google’ın Nano Banana 2’si geldi — hemen dene',
    intro:
      'Nano Banana 2, yeni Gemini 3.1 Flash Image yığını üzerinde ve gücüyle dikkat çekiyor. Üç yetenek: gerçek zamanlı web araması, özne tutarlılığı ve çok dilli tipografi ile grafik tasarım — LimaxAI için örneklerle.',
    rt: 'Gerçek zamanlı web araması',
    r1: 'Üretmeden önce web’e «bakabilir». Örnek: Château du Clos Lucé’nin gerçek fotoğraflarını canlı sentetik kübizme dönüştürme; model hakkında iş infografiği; Ghibli tarzı modern simge yapı.',
    ct: 'Seriler için özne tutarlılığı',
    c1: 'Örnek: aynı 20 yaşında Asyalı kadın (kırmızı bere, yuvarlak gözlük, bej trenç)—üç sahne: şeffaf şemsiyeli yağmurlu Tokyo, öğleden sonra kütüphane, gece Eyfel önünde selfie. 16:9, yüz ve kıyafet tutarlı, Leica tarzı fotoğraf.',
    tt: 'Çok dilli tipografi ve grafik tasarım',
    t1: 'Birden fazla yazı sistemini iyi işler. Örnek: «深圳» harf tasarımında kentsel öğeler; sosyal için uzun metinli 3:2 poster; Bento Grid poster (ör. beslenme rehberi) net hiyerarşi.',
    imgT: 'Örnek görsel',
    imgAlt: 'Nano Banana 2 yetenekleri',
    imgC: 'Yetenek özeti',
    startT: 'Oluşturmaya başla',
    startx: 'Hızlı, 4K, web bilinçli, güçlü tipografi, tutarlı karakterler. Oyuncaktan verimliliğe — LimaxAI’da.',
    cta: 'LimaxAI’da kullan',
  },
  vi: {
    title: 'Nano Banana 2 của Google đã ra mắt — dùng thử ngay',
    intro:
      'Nano Banana 2 dựa trên nền Gemini 3.1 Flash Image mới và nổi bật nhờ sức mạnh. Ba khả năng: tìm kiếm web thời gian thực, nhất quán chủ thể, và chữ in đa ngôn ngữ kèm thiết kế đồ họa — có ví dụ cho LimaxAI.',
    rt: 'Tìm kiếm web thời gian thực',
    r1: 'Có thể «xem» web trước khi tạo. Ví dụ: ảnh thật lâu đài Clos Lucé tái hiện theo lập thể tổng hợp rực rỡ; infographic giới thiệu mô hình; địa danh hiện đại phong cách Ghibli.',
    ct: 'Nhất quán chủ thể cho series',
    c1: 'Ví dụ: cùng một phụ nữ châu Á 20 tuổi (mũ nồi đỏ, kính tròn, áo khoác be)—ba cảnh: Tokyo mưa ô trong suốt, thư viện chiều muộn, selfie đêm trước tháp Eiffel. 16:9, mặt và trang phục đồng nhất, ảnh kiểu Leica.',
    tt: 'Chữ in đa ngôn ngữ và thiết kế đồ họa',
    t1: 'Xử lý tốt nhiều hệ chữ. Ví dụ: chữ «深圳» gắn yếu tố đô thị vào nét; poster 3:2 với câu dài cho mạng xã hội; poster Bento Grid (vd. hướng dẫn ăn uống) phân cấp rõ.',
    imgT: 'Ảnh mẫu',
    imgAlt: 'Khả năng Nano Banana 2',
    imgC: 'Tóm tắt khả năng',
    startT: 'Bắt đầu tạo',
    startx: 'Nhanh, 4K, hiểu web, chữ in tốt, nhân vật nhất quán. Từ đồ chơi đến năng suất trên LimaxAI.',
    cta: 'Dùng trên LimaxAI',
  },
  th: {
    title: 'Nano Banana 2 จาก Google มาแล้ว — ลองเลย',
    intro:
      'Nano Banana 2 ใช้สแต็ก Gemini 3.1 Flash Image ใหม่และโดดเด่นด้วยพลัง สามความสามารถ: ค้นเว็บแบบเรียลไทม์ ความสม่ำเสมอของตัวแบบ และตัวพิมพ์หลายภาษากับกราฟิกดีไซน์ พร้อมตัวอย่างบน LimaxAI',
    rt: 'ค้นเว็บแบบเรียลไทม์',
    r1: 'สามารถ «ดู»เว็บก่อนสร้างภาพ ตัวอย่าง: ภาพจริงของปราสาทโคลูซ์ลูเซ่ในสไตล์คิวบิสซึ่งสังเคราะห์สดใส อินโฟกราฟิกธุรกิจแนะนำโมเดล แลนด์มาร์กสมัยใหม่แบบจิบลิ',
    ct: 'ความสม่ำเสมอของตัวแบบสำหรับซีรีส์',
    c1: 'ตัวอย่าง: ผู้หญิงเอเชียวัย 20 เดิม (หมวกเบเร่ต์แดง แว่นกลม เสื้อโค้ทเบจ) สามฉาก—โตเกียวฝนร่มใส ห้องสมุดตอนบ่าย เซลฟี่กลางคืนหน้าไอเฟล 16:9 ใบหน้าและชุดสอดคล้อง สไตล์ภาพแบบ Leica',
    tt: 'ตัวพิมพ์หลายภาษาและกราฟิกดีไซน์',
    t1: 'จัดการหลายระบบการเขียนได้ดี ตัวอย่าง: ตัวอักษร「深圳」ผสมองค์ประกอบเมืองในเส้น โปสเตอร์ 3:2 ข้อความยาวสำหรับโซเชียล โปสเตอร์ Bento Grid (เช่น คู่มืออาหาร) ลำดับชัด',
    imgT: 'ภาพตัวอย่าง',
    imgAlt: 'ความสามารถของ Nano Banana 2',
    imgC: 'สรุปความสามารถ',
    startT: 'เริ่มสร้าง',
    startx: 'เร็ว 4K เข้าใจเว็บ ตัวพิมพ์แกร่ง ตัวละครคงที่ จากของเล่นสู่ผลผลิตบน LimaxAI',
    cta: 'ใช้บน LimaxAI',
  },
  it: {
    title: 'Nano Banana 2 di Google è qui — provalo',
    intro:
      'Nano Banana 2 si basa sul nuovo stack Gemini 3.1 Flash Image e colpisce per la potenza. Tre capacità: ricerca web in tempo reale, coerenza del soggetto, tipografia multilingue e graphic design — con esempi per LimaxAI.',
    rt: 'Ricerca web in tempo reale',
    r1: 'Può «consultare» il web prima di generare. Esempio: foto reali del Château du Clos Lucé reinterpretate in cubismo sintetico vivido; infografica business sul modello; landmark moderno stile Ghibli.',
    ct: 'Coerenza del soggetto per serie',
    c1: 'Esempio: la stessa donna asiatica di 20 anni (berretto rosso, occhiali tondi, trench beige) in tre scene: Tokyo piovosa con ombrello trasparente, biblioteca nel tardo pomeriggio, selfie notturno alla Tour Eiffel. 16:9, volto e outfit coerenti, stile foto tipo Leica.',
    tt: 'Tipografia multilingue e graphic design',
    t1: 'Gestisce bene più sistemi di scrittura. Esempio: lettering «深圳» con elementi urbani nei tratti; poster 3:2 con frase lunga per i social; poster Bento Grid (es. guida alimentare) con gerarchia chiara.',
    imgT: 'Immagine di esempio',
    imgAlt: 'Capacità di Nano Banana 2',
    imgC: 'Panoramica',
    startT: 'Inizia a creare',
    startx: 'Veloce, 4K, consapevole del web, tipografia solida, personaggi coerenti. Dal giocattolo alla produttività su LimaxAI.',
    cta: 'Usa su LimaxAI',
  },
  fa: {
    title: 'نانو بانانا ۲ گوگل آمد — همین حال امتحان کنید',
    intro:
      'نانو بانانا ۲ بر پایهٔ پشتهٔ جدید Gemini 3.1 Flash Image است و با قدرتش توجه می‌گیرد. سه توانایی: جستجوی وب بلادرنگ، ثبات سوژه، و تایپوگرافی چندزبانه با طراحی گرافیکی — با نمونه برای LimaxAI.',
    rt: 'جستجوی وب بلادرنگ',
    r1: 'قبل از تولید می‌تواند وب را «ببیند». مثال: عکس واقعی قلعهٔ کلو لوسه در کوبیسم ترکیبی زنده؛ اینفوگرافیک کسب‌وکار دربارهٔ مدل؛ نماد شهری مدرن به سبک جیبلی.',
    ct: 'ثبات سوژه برای سریال و محتوا',
    c1: 'مثال: همان زن آسیایی ۲۰ ساله (کلاه برت قرمز، عینک گرد، بارانی بژ) در سه صحنه: توکیوی بارانی با چتر شفاف، کتابخانه عصر، سلفی شبانه پای برج ایفل. ۱۶:۹، چهره و لباس یکدست، سبک عکس شبیه Leica.',
    tt: 'تایپوگرافی چندزبانه و طراحی گرافیکی',
    t1: 'چند سیستم نوشتاری را خوب مدیریت می‌کند. مثال: حروف «深圳» با عناصر شهری در خطوط؛ پوستر ۳:۲ با جملهٔ بلند برای شبکه‌های اجتماعی؛ پوستر Bento Grid (مثل راهنمای تغذیه) با سلسله‌مراتب روشن.',
    imgT: 'تصویر نمونه',
    imgAlt: 'توانایی‌های نانو بانانا ۲',
    imgC: 'خلاصهٔ توانایی‌ها',
    startT: 'شروع ساخت',
    startx: 'سریع، ۴K، آگاه از وب، تایپوگرافی قوی، شخصیت‌های یکدست. از اسباب‌بازی تا بهره‌وری در LimaxAI.',
    cta: 'استفاده در LimaxAI',
  },
  nl: {
    title: 'Googles Nano Banana 2 is er — probeer het',
    intro:
      'Nano Banana 2 draait op de nieuwe Gemini 3.1 Flash Image-stack en valt op door kracht. Drie kernen: realtime webzoeken, subjectconsistentie en meertalige typografie met grafisch ontwerp — met voorbeelden voor LimaxAI.',
    rt: 'Realtime webzoeken',
    r1: 'Kan voor genereren op het web «kijken». Voorbeeld: echte foto’s van Château du Clos Lucé in levendig synthetisch kubisme; zakelijke infographic over het model; moderne landmark in Ghibli-stijl.',
    ct: 'Subjectconsistentie voor series',
    c1: 'Voorbeeld: dezelfde 20-jarige Aziatische vrouw (rode baret, ronde bril, beige trench) in drie scènes: regenachtig Tokio met transparante paraplu, bibliotheek laat in de middag, nachtselfie bij de Eiffeltoren. 16:9, gezicht en outfit consistent, Leica-achtige fotostijl.',
    tt: 'Meertalige typografie en grafisch ontwerp',
    t1: 'Goed met meerdere schriftsystemen. Voorbeeld: letterwerk «深圳» met stedelijke elementen in de streken; 3:2-poster met lange tekst voor social; Bento Grid-poster (bv. eetgids) met duidelijke hiërarchie.',
    imgT: 'Voorbeeldafbeelding',
    imgAlt: 'Mogelijkheden van Nano Banana 2',
    imgC: 'Overzicht',
    startT: 'Beginnen met maken',
    startx: 'Snel, 4K, webbewust, sterke typografie, consistente personages. Van speelgoed naar productiviteit op LimaxAI.',
    cta: 'Gebruiken op LimaxAI',
  },
  pl: {
    title: 'Nano Banana 2 od Google jest — wypróbuj',
    intro:
      'Nano Banana 2 opiera się na nowym stosie Gemini 3.1 Flash Image i wyróżnia się mocą. Trzy możliwości: wyszukiwanie w sieci w czasie rzeczywistym, spójność podmiotu oraz wielojęzyczna typografia i projekt graficzny — z przykładami dla LimaxAI.',
    rt: 'Wyszukiwanie w sieci w czasie rzeczywistym',
    r1: 'Może «sprawdzić» sieć przed generowaniem. Przykład: prawdziwe zdjęcia Château du Clos Lucé w żywym syntetycznym kubizmie; infografika biznesowa o modelu; nowoczesny punkt orientacyjny w stylu Ghibli.',
    ct: 'Spójność podmiotu dla serii',
    c1: 'Przykład: ta sama 20-letnia Azjatka (czerwony beret, okrągłe okulary, beżowy trencz) w trzech scenach: deszczowe Tokio z przezroczystym parasolem, biblioteka późnym popołudniem, nocne selfie przy Wieży Eiffla. 16:9, twarz i strój spójne, styl zdjęć jak Leica.',
    tt: 'Wielojęzyczna typografia i projekt graficzny',
    t1: 'Dobrze radzi sobie z wieloma systemami pisma. Przykład: liternictwo «深圳» z miejskimi motywami w kreskach; plakat 3:2 z długim tekstem na social media; plakat Bento Grid (np. poradnik żywieniowy) z jasną hierarchią.',
    imgT: 'Obraz przykładowy',
    imgAlt: 'Możliwości Nano Banana 2',
    imgC: 'Przegląd',
    startT: 'Zacznij tworzyć',
    startx: 'Szybko, 4K, świadomość sieci, mocna typografia, spójne postacie. Od zabawki do produktywności na LimaxAI.',
    cta: 'Użyj na LimaxAI',
  },
  sv: {
    title: 'Googles Nano Banana 2 är här — prova nu',
    intro:
      'Nano Banana 2 bygger på den nya Gemini 3.1 Flash Image-stacken och sticker ut med styrka. Tre förmågor: webbsökning i realtid, subjektkonsistens och flerspråkig typografi med grafisk design — med exempel för LimaxAI.',
    rt: 'Webbsökning i realtid',
    r1: 'Kan «titta» på webben innan generering. Exempel: verkliga foton av Château du Clos Lucé i livfull syntetisk kubism; affärsinfografik om modellen; modern landmärke i Ghibli-stil.',
    ct: 'Subjektkonsistens för serier',
    c1: 'Exempel: samma 20-åriga asiatiska kvinna (röd basker, runda glasögon, beige trench) i tre scener: regnigt Tokyo med genomskinligt paraply, bibliotek sent på eftermiddagen, nattselfie vid Eiffeltornet. 16:9, ansikte och kläder konsekventa, Leica-liknande fotostil.',
    tt: 'Flerspråkig typografi och grafisk design',
    t1: 'Hanterar flera skriftsystem bra. Exempel: bokstäver «深圳» med urbana element i dragen; 3:2-affisch med lång text för sociala medier; Bento Grid-affisch (t.ex. matguide) med tydlig hierarki.',
    imgT: 'Exempelbild',
    imgAlt: 'Nano Banana 2-förmågor',
    imgC: 'Översikt',
    startT: 'Börja skapa',
    startx: 'Snabbt, 4K, webbmedveten, stark typografi, konsekventa karaktärer. Från leksak till produktivitet på LimaxAI.',
    cta: 'Använd på LimaxAI',
  },
  uk: {
    title: 'Nano Banana 2 від Google вже тут — спробуйте',
    intro:
      'Nano Banana 2 побудований на новому стеку Gemini 3.1 Flash Image і вирізняється силою. Три можливості: пошук у мережі в реальному часі, узгодженість об’єкта та багатомовна типографіка з графічним дизайном — з прикладами для LimaxAI.',
    rt: 'Пошук у вебі в реальному часі',
    r1: 'Може «подивитися» веб перед генерацією. Приклад: реальні фото замку Кло-Люсе у яскравому синтетичному кубізмі; бізнес-інфографіка про модель; сучасна пам’ятка у стилі Ghibli.',
    ct: 'Узгодженість об’єкта для серій',
    c1: 'Приклад: та сама 20-річна азійська жінка (червоний берет, круглі окуляри, бежевий тренч) у трьох сценах: дощовий Токіо з прозорою парасолькою, бібліотека пізно вдень, нічне селфі біля Ейфелевої вежі. 16:9, обличчя й одяг стабільні, стиль фото як у Leica.',
    tt: 'Багатомовна типографіка та графічний дизайн',
    t1: 'Добре працює з кількома системами письма. Приклад: літери «深圳» з міськими мотивами в штрихах; постер 3:2 з довгою фразою для соцмереж; Bento Grid-постер (напр. гід харчування) з чіткою ієрархією.',
    imgT: 'Приклад зображення',
    imgAlt: 'Можливості Nano Banana 2',
    imgC: 'Огляд',
    startT: 'Почати створення',
    startx: 'Швидко, 4K, урахування вебу, сильна типографіка, узгоджені персонажі. Від іграшки до продуктивності на LimaxAI.',
    cta: 'Використати на LimaxAI',
  },
  ro: {
    title: 'Nano Banana 2 de la Google a sosit — încearcă acum',
    intro:
      'Nano Banana 2 se bazează pe noul stack Gemini 3.1 Flash Image și iese în evidență prin putere. Trei capacități: căutare web în timp real, consistența subiectului și tipografie multilingvă cu design grafic — cu exemple pentru LimaxAI.',
    rt: 'Căutare web în timp real',
    r1: 'Poate «privi» webul înainte de generare. Exemplu: fotografii reale ale castelului Clos Lucé reinterpretate în cubism sintetic vibrant; infografică de business despre model; reper modern în stil Ghibli.',
    ct: 'Consistența subiectului pentru serii',
    c1: 'Exemplu: aceeași femeie asiatică de 20 de ani (beretă roșie, ochelari rotunzi, trench bej) în trei scene: Tokyo ploios cu umbrelă transparentă, bibliotecă spre seară, selfie nocturn la Turnul Eiffel. 16:9, față și ținută coerente, stil foto tip Leica.',
    tt: 'Tipografie multilingvă și design grafic',
    t1: 'Gestionează bine mai multe sisteme de scriere. Exemplu: litere «深圳» cu elemente urbane în trăsături; poster 3:2 cu frază lungă pentru social; poster Bento Grid (ex. ghid alimentar) cu ierarhie clară.',
    imgT: 'Imagine exemplu',
    imgAlt: 'Capacități Nano Banana 2',
    imgC: 'Prezentare generală',
    startT: 'Începe crearea',
    startx: 'Rapid, 4K, conștient de web, tipografie puternică, personaje coerente. De la jucărie la productivitate pe LimaxAI.',
    cta: 'Folosește pe LimaxAI',
  },
};

export function getNanobanana2DesignArticleForExtraLocale(loc: string): ExtraLocaleTutorialArticle | null {
  const c = nanobanana2DesignExtraLocales[loc];
  if (!c) return null;
  return {
    slug: 'nanobanana2-design-assistant',
    title: c.title,
    intro: c.intro,
    sections: [
      {
        id: 'storyboard',
        title: c.st,
        blocks: [
          { type: 'paragraph', text: c.s1 },
          { type: 'paragraph', text: c.s2 },
          { type: 'paragraph', text: c.s3 },
        ],
      },
      {
        id: 'batch',
        title: c.bt,
        blocks: [
          { type: 'paragraph', text: c.b1 },
          { type: 'paragraph', text: c.b2 },
        ],
      },
      {
        id: 'multisize',
        title: c.mt,
        blocks: [
          { type: 'paragraph', text: c.m1 },
          { type: 'paragraph', text: c.m2 },
        ],
      },
      { id: 'image', title: c.imgT, blocks: [{ type: 'image', src: NB_DESIGN_IMG, alt: c.imgAlt, caption: c.imgC }] },
      {
        id: 'start',
        title: c.startT,
        blocks: [{ type: 'paragraph', text: c.startx }, { type: 'cta', text: c.cta, url: 'https://www.limaxai.com/' }],
      },
    ],
  };
}

export function getNanobanana2LaunchArticleForExtraLocale(loc: string): ExtraLocaleTutorialArticle | null {
  const c = nanobanana2LaunchExtraLocales[loc];
  if (!c) return null;
  return {
    slug: 'nanobanana2-google-launch',
    title: c.title,
    intro: c.intro,
    sections: [
      { id: 'realtime', title: c.rt, blocks: [{ type: 'paragraph', text: c.r1 }] },
      { id: 'consistency', title: c.ct, blocks: [{ type: 'paragraph', text: c.c1 }] },
      { id: 'typography', title: c.tt, blocks: [{ type: 'paragraph', text: c.t1 }] },
      { id: 'image', title: c.imgT, blocks: [{ type: 'image', src: NB_LAUNCH_IMG, alt: c.imgAlt, caption: c.imgC }] },
      {
        id: 'start',
        title: c.startT,
        blocks: [{ type: 'paragraph', text: c.startx }, { type: 'cta', text: c.cta, url: 'https://www.limaxai.com/' }],
      },
    ],
  };
}
