# Full section translations for GPT-5.6 release blog.
# Used by generate_gpt56_release_blog.py for locales except zh-cn and en.


def _en():
    return {
        "intro": "Several developers have spotted **GPT-5.6** references in OpenAI Codex backend logs before any official announcement. If the reports hold, the next generation may offer roughly **1.5 million tokens** of context, with a launch window around **June 2026**. This article separates what can be verified today from what is still unknown, and compares the rumored limits with GPT-5.5.",
        "keywords": "Keywords: chatgpt, GPT-5.6, gpt tutorial.",
        "published": "Published: May 26, 2026",
        "img_alt": "OpenAI GPT-5.6 leak 1.5M context window",
        "h_leak": "Where the clues came from: a Codex log canary",
        "leak": "About three weeks after GPT-5.5 shipped, researchers began discussing a possible successor. Unlike a system card or Dev Day keynote, the first signal was a **routing entry in OpenAI Codex logs**: most traffic still mapped to `gpt-5.5`, but some sessions briefly pointed to `gpt-5.6`. The line then disappeared from later session files—more like a leftover deployment mapping than a deliberate reveal.\n\n**OpenAI has not announced GPT-5.6.** Everything below comes from developer logs, community reproductions, and public leaks; it may change when official docs land.",
        "h_codenames": "Internal codenames: iris-alpha, ember-alpha, beacon-alpha",
        "codenames": "Leaks and logs mention several internal build names, including **iris-alpha** (most often tied to GPT-5.6), **ember-alpha**, and **beacon-alpha**. It is unclear whether each maps to a public tier (standard, Pro, fast) or whether all will ship.",
        "codenames_table": "| Codename | What is public today | Notes |\n| --- | --- | --- |\n| iris-alpha | Appears alongside the GPT-5.6 name | Treated as the closest to a shipping build |\n| ember-alpha | Mentioned in logs | Role still unknown |\n| beacon-alpha | Mentioned in logs | Role still unknown |",
        "h_context": "1.5M context: how much more than GPT-5.5",
        "context": "Leaks point to a context window of about **1,500,000 tokens** for GPT-5.6. Compared with GPT-5.5 today:",
        "ctx_table": "| Channel / version | Approx. context cap | vs. 1.5M leak |\n| --- | --- | --- |\n| GPT-5.5 API | 1,050,000 tokens | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400,000 tokens | ~+275% |\n| Rumored GPT-5.6 | 1,500,000 tokens | — |",
        "context_note": "For long-document analysis, repo-wide code review, and multi-step agents, a larger window often means less manual chunking—but also higher per-call cost and latency. Whether it pays off depends on your workload.",
        "h_test": "Stress tests at extreme length (unofficial)",
        "test": "Community developers have run heavy tests in tools such as **OpenCode**: inputs around **900k tokens** still got responses; some reports claim requests above **1.05M tokens** completed. These runs depend on specific channels and builds—they are **not** an official SLA and do not guarantee day-one access at full window for every user.",
        "h_ui": "UI generation: closer to shippable front ends",
        "ui": "Leak screenshots showed **Lumen Notes**, a minimal notes UI generated with very short prompts—cleaner grids, restrained palettes, and clearer type hierarchy and navigation. If that holds in public builds, GPT-5.6 may be stronger at **layout and visual constraints**, not just code snippets; wait for release builds and benchmarks before betting production UI on it.",
        "h_release": "How to read the release timeline",
        "release": "There is no confirmed ship date yet. Weak signals you can track:",
        "sig_table": "| Signal | Notes |\n| --- | --- |\n| Leak timeline | Multiple sources point to **June 2026** |\n| Prediction markets | Polymarket-style odds on \"before June 30\" reflect community expectation, not OpenAI commitments |\n| Product cadence | GPT-5.6 hints ~3 weeks after GPT-5.5 fits recent fast iteration |\n| What to watch | More canary logs, a new system card, Codex routing changes, alignment/reward blog posts |",
        "release_note": "Canary names appear and vanish at large labs all the time—**a log line is not a launch date**. Treat the table as a checklist, not a schedule.",
        "h_unknown": "What is still unclear",
        "unknown": "As of this writing, outsiders still do not know:\n\n- Whether parameter count, training data, or architecture change materially (a ~3-week window often looks like a strong point release, not a full rebuild)\n- API pricing and rate tiers versus GPT-5.5\n- Whether ChatGPT plans sync on day one and whether products like an \"ultrafast\" mode ship separately\n- How fixes tied to the goblin alignment incident will show up in the system card\n\nWait for OpenAI's announcement or system card before treating any of this as final.",
        "h_guide": "GPT tutorial: what to practice before launch",
        "guide": "You can build good habits on **GPT-5.5 / GPT-5.4** now so migration is cheaper when GPT-5.6 lands:\n\n1. **Trim long inputs** before upload—drop irrelevant sections and anchor with an outline or short summary.\n2. **Write stop rules for agents and coding** (e.g. \"at most two search rounds,\" \"stop when evidence is enough\") to cut useless tool calls.\n3. **Layer UI asks**—ask for information architecture and component list first, then code, instead of one-shot \"full app\" prompts.\n4. **Keep a fixed eval set**—run the same prompts at `low` and `medium` reasoning effort and log latency, cost, and quality for an A/B when 5.6 ships.\n\nTo try GPT chat and model switching in the browser now, use the button below on LimaxAI (currently **gpt-5.4**; pick newer models from the list when they appear).",
        "h_sum": "Summary",
        "sum_table": "| Item | Current read |\n| --- | --- |\n| Officially announced | No |\n| Context leak | ~1.5M tokens |\n| vs. GPT-5.5 API | ~+43% |\n| Timing | Often cited as June 2026—unconfirmed |\n| Practical takeaway | Master today's GPT for long context and agents; migrate after the system card |",
        "sum_line": "Whether GPT-5.6 ships on time and whether the full window opens to everyone depends on OpenAI's next announcement. Until then, getting more from the GPT you already have is usually a better bet than reshaping your stack around every leak.",
        "outro": "To start chatting with GPT on LimaxAI, tap the button below and choose your model.",
    }


def _zh_tw():
    e = _en()
    return {
        **e,
        "intro": "多名開發者在 OpenAI 尚未正式官宣前，於 Codex 後端日誌中發現 **GPT-5.6** 線索。若爆料屬實，下一代上下文可能約 **150 萬 tokens**，時間點指向 **2026 年 6 月**。本文區分目前已能核實的資訊與仍不確定的部分，並與 GPT-5.5 對照。",
        "keywords": "關鍵字：chatgpt、GPT-5.6、gpt教程。",
        "published": "發布日期：2026年5月26日",
        "img_alt": "OpenAI GPT-5.6 爆料 150 萬上下文",
        "h_leak": "線索從哪來：Codex 日誌裡的「金絲雀」",
        "leak": "GPT-5.5 上線約三週後，研究社群開始討論下一代模型。與以往不同，這次不是系統卡或開發者大會，而是有人復現 **OpenAI Codex 路由日誌**：多數請求仍映射到 `gpt-5.5`，偶爾出現指向 `gpt-5.6` 的條目，隨後又從後續會話檔案中消失，更像部署殘留映射，而非有意官宣。\n\n**OpenAI 尚未發布公告。** 以下內容來自開發者抓包、社群復現與公開爆料，可能隨官方澄清而調整。",
        "h_codenames": "內部代號：iris-alpha、ember-alpha、beacon-alpha",
        "codenames": "日誌與爆料提到多個內部構建代號，包括 **iris-alpha**（與 GPT-5.6 關聯最緊）、**ember-alpha**、**beacon-alpha**。目前無法確認是否對應不同公開檔位，或是否都會對外發布。",
        "codenames_table": "| 代號 | 目前公開資訊 | 備註 |\n| --- | --- | --- |\n| iris-alpha | 與 GPT-5.6 名稱一同出現 | 被視為最接近對外版本 |\n| ember-alpha | 日誌中提及 | 定位待定 |\n| beacon-alpha | 日誌中提及 | 定位待定 |",
        "h_context": "150 萬上下文：相對 GPT-5.5 漲了多少",
        "context": "爆料指向 GPT-5.6 上下文約 **1,500,000 tokens**。與現行 GPT-5.5 對比：",
        "ctx_table": "| 渠道 / 版本 | 上下文上限（約） | 相對 150 萬 |\n| --- | --- | --- |\n| GPT-5.5 API | 1,050,000 tokens | 約 +43% |\n| GPT-5.5（Codex OAuth） | 400,000 tokens | 約 +275% |\n| 爆料中的 GPT-5.6 | 1,500,000 tokens | — |",
        "context_note": "對長文件分析、跨倉庫程式審查與多輪 Agent，窗口變大通常意味更少手動切塊，但也帶來更高單次成本與延遲，是否划算取決於工作負載。",
        "h_test": "超長上下文實測（非官方）",
        "test": "社群在 **OpenCode** 等工具做過壓力測試：輸入約 **90 萬 tokens** 仍可回應；有案例稱超過 **105 萬 tokens** 也能跑通。此類測試依賴特定渠道與構建，**不等同官方 SLA**，也不代表所有用戶首日就能用滿窗口。",
        "h_ui": "前端生成：更接近可上線的 UI",
        "ui": "爆料截圖出現 **Lumen Notes** 極簡記事介面——在提示詞很短時生成，柵格更整齊、配色更克制、字體層級與導航更清晰。若公開版本屬實，GPT-5.6 在 **版面與視覺約束** 上可能再進一步；仍需等正式版與評測再下結論。",
        "h_release": "如何判斷發布時間",
        "release": "目前沒有確定發布日。可追蹤的弱信號：",
        "sig_table": "| 信號 | 說明 |\n| --- | --- |\n| 爆料時間線 | 多指向 **2026 年 6 月** |\n| 預測市場 | Polymarket 等對「6 月 30 日前」的機率反映社群預期，非官方承諾 |\n| 產品節奏 | GPT-5.5 約三週後出現 5.6 線索，符合近年快速迭代 |\n| 後續觀察 | 更多金絲雀日誌、新版系統卡、Codex 路由變更、對齊/獎勵相關博文 |",
        "release_note": "金絲雀名稱出現又消失很常見——**有日誌不代表下週就上**。把上表當追蹤清單，而非排期承諾。",
        "h_unknown": "目前仍不清楚的事",
        "unknown": "截至本文寫作時，外界仍不清楚：參數與架構是否大改（三週窗口常更像強點版本）；API 定價與速率檔；ChatGPT 各方案是否同步；哥布林對齊事件修復如何寫進系統卡。需等 OpenAI 正式公告再定論。",
        "h_guide": "GPT 教程：發布前可以先練什麼",
        "guide": "在 GPT-5.6 落地前，用 **GPT-5.5 / GPT-5.4** 養成習慣，遷移成本更低：\n\n1. **長上下文先壓縮輸入**——去掉無關章節，用目錄或小摘要當錨點。\n2. **Agent / 程式任務寫清停止條件**——例如「檢索最多兩輪」「證據足夠就停」。\n3. **UI 需求分層**——先要資訊架構與元件清單，再要程式碼。\n4. **固定樣本做對比**——在 `low` / `medium` 推理檔各跑一遍，記錄延遲、成本與品質。\n\n想先在瀏覽器體驗 GPT，可點下方按鈕進入 LimaxAI（目前 **gpt-5.4**，上新後在模型列表選擇）。",
        "h_sum": "小結",
        "sum_table": "| 項目 | 目前判斷 |\n| --- | --- |\n| 是否已官宣 | 否 |\n| 上下文爆料 | 約 150 萬 tokens |\n| 對比 GPT-5.5 API | 約 +43% |\n| 時間 | 多指向 2026 年 6 月，待確認 |\n| 建議 | 用現有 GPT 練長上下文與 Agent，等系統卡再遷移 |",
        "sum_line": "GPT-5.6 是否準時、窗口是否對所有人開放，要看 OpenAI 下一則公告。在那之前，把手上的 GPT 用熟，往往比追爆料改架構更划算。",
        "outro": "要在 LimaxAI 開始使用 GPT，請點下方按鈕並選擇模型。",
    }


_LOCALE_OVERRIDES: dict[str, dict[str, str]] = {}


def _add(lang: str, **kwargs):
    _LOCALE_OVERRIDES[lang] = kwargs


# Japanese
_add(
    "ja",
    intro="OpenAI が正式発表する前に、複数の開発者が Codex バックエンドログで **GPT-5.6** の痕跡を確認しています。報道が正しければ、次世代は約 **150 万トークン**のコンテキストを、**2026 年 6 月**頃の公開を想定している可能性があります。本記事では現時点で検証できる情報と未確定事項を分け、GPT-5.5 と比較します。",
    keywords="キーワード：chatgpt、GPT-5.6、gptチュートリアル。",
    published="公開日：2026年5月26日",
    img_alt="OpenAI GPT-5.6 リーク 150万コンテキスト",
    h_leak="手がかりの出所：Codex ログのカナリア",
    leak="GPT-5.5 公開から約 3 週間後、研究コミュニティで後継モデルの話題が出始めました。今回はシステムカードや Dev Day ではなく、**OpenAI Codex のルーティングログ**に、大半は `gpt-5.5` なのに一部だけ `gpt-5.6` へ向く記録が一時的に現れ、後続セッションからは消えた——意図的な発表というよりデプロイ残りの可能性が高いです。\n\n**OpenAI はまだ GPT-5.6 を公式発表していません。** 以下は開発者ログ・再現・リークに基づく内容で、公式情報で変わる可能性があります。",
    h_codenames="内部コード名：iris-alpha、ember-alpha、beacon-alpha",
    codenames="リークやログでは **iris-alpha**（GPT-5.6 と最も結びつく）、**ember-alpha**、**beacon-alpha** などが言及されています。公開ティアへの対応や、すべてが出荷されるかは不明です。",
    codenames_table="| コード名 | 現時点の公開情報 | 備考 |\n| --- | --- | --- |\n| iris-alpha | GPT-5.6 名と同時に出現 | 出荷に最も近い構築と見られる |\n| ember-alpha | ログで言及 | 役割未定 |\n| beacon-alpha | ログで言及 | 役割未定 |",
    h_context="150 万コンテキスト：GPT-5.5 比でどれだけ増えるか",
    context="リークでは GPT-5.6 のコンテキストが約 **1,500,000 トークン**とされています。現行 GPT-5.5 との比較：",
    ctx_table="| チャネル / 版 | コンテキスト上限（目安） | 150 万比 |\n| --- | --- | --- |\n| GPT-5.5 API | 1,050,000 tokens | 約 +43% |\n| GPT-5.5（Codex OAuth） | 400,000 tokens | 約 +275% |\n| リークの GPT-5.6 | 1,500,000 tokens | — |",
    context_note="長文分析・リポジトリ横断レビュー・多段 Agent では、窓が大きいほど手動チャンクは減りますが、コストと遅延も増えます。ワークロード次第です。",
    h_test="超長コンテキストのストレステスト（非公式）",
    test="コミュニティは **OpenCode** などで、入力約 **90 万トークン**でも応答、**105 万超**の事例も報告されています。チャネルとビルド依存であり、**公式 SLA ではありません**。",
    h_ui="UI 生成：出荷に近いフロントエンドへ",
    ui="リーク画面では、短いプロンプトで **Lumen Notes** というミニメモ UI が生成され、グリッド・配色・タイポ階層が整理されていました。公開版で同様なら **レイアウト制約**が強化された可能性がありますが、本番 UI の判断はリリース後の検証を待ちましょう。",
    h_release="公開時期の読み方",
    release="確定した発売日はまだありません。追跡できる弱いシグナル：",
    sig_table="| シグナル | 内容 |\n| --- | --- |\n| リークの時期 | 多くが **2026 年 6 月**を指す |\n| 予測市場 | 6/30 前などのオッズはコミュニティ期待であり公式約束ではない |\n| 製品ペース | GPT-5.5 の約 3 週間後に 5.6 痕跡——近年の高速イテレーションと整合 |\n| 注目点 | カナリアログ増、新システムカード、Codex ルーティング、整合/報酬ブログ |",
    release_note="カナリア名の出現と消失は大規模ラボでは日常茶飯事——**ログ 1 行は発売日ではありません**。",
    h_unknown="まだ不明な点",
    unknown="現時点では、パラメータ規模・アーキテクチャの大幅変更の有無、API 価格、ChatGPT プラン同期、「ultrafast」などの製品形態、ゴブリン整合事件の修正のシステムカード記載などは不明です。公式発表を待ちましょう。",
    h_guide="GPT チュートリアル：公開前に慣れておくこと",
    guide="GPT-5.6 前に **GPT-5.5 / GPT-5.4** で習慣づけすると移行が楽です：\n\n1. **長文は入力を圧縮**（無関係章の削除、目次・要約でアンカー）。\n2. **Agent/コーディングに停止条件**（検索は最大 2 回など）。\n3. **UI は段階的に**（IA とコンポーネント一覧→コード）。\n4. **固定評価セットで A/B**（`low`/`medium` の遅延・コスト・品質を記録）。\n\nブラウザで試すには下のボタンから LimaxAI（現状 **gpt-5.4**、新モデルはリストから選択）。",
    h_sum="まとめ",
    sum_table="| 項目 | 現時点の見立て |\n| --- | --- |\n| 公式発表 | なし |\n| コンテキストリーク | 約 150 万 tokens |\n| GPT-5.5 API 比 | 約 +43% |\n| 時期 | 2026 年 6 月が多いが未確定 |\n| 実務 | 現行 GPT で長文・Agent を磨き、システムカード後に移行 |",
    sum_line="GPT-5.6 が予定通り来るか、全ユーザーに満開の窓が開くかは次の公式発表次第。それまでは手元の GPT を使いこなす方が、リークごとにスタックを組み替えるより得なことが多いです。",
    outro="LimaxAI で GPT を始めるには、下のボタンからモデルを選んでください。",
)

# Korean
_add(
    "ko",
    intro="여러 개발자가 OpenAI 공식 발표 전 Codex 백엔드 로그에서 **GPT-5.6** 흔적을 확인했습니다. 보도가 맞다면 다음 세대는 약 **150만 토큰** 컨텍스트와 **2026년 6월** 전후 공개가 거론됩니다. 본문은 현재 검증 가능한 정보와 불확실한 부분을 나누고 GPT-5.5와 비교합니다.",
    keywords="키워드: chatgpt, GPT-5.6, gpt 튜토리얼.",
    published="게시일: 2026년 5월 26일",
    img_alt="OpenAI GPT-5.6 유출 150만 컨텍스트",
    h_leak="단서의 출처: Codex 로그 카나리",
    leak="GPT-5.5 출시 약 3주 후 연구 커뮤니티에서 후속 모델 이야기가 나왔습니다. 이번에는 시스템 카드가 아니라 **Codex 라우팅 로그**에 대부분 `gpt-5.5`인데 일부만 `gpt-5.6`으로 가는 항목이 잠깐 보였다가 사라졌습니다—의도적 발표보다 배포 잔여 매핑에 가깝습니다.\n\n**OpenAI는 아직 GPT-5.6을 공식 발표하지 않았습니다.** 아래는 개발자 로그·재현·유출에 따른 내용입니다.",
    h_codenames="내부 코드명: iris-alpha, ember-alpha, beacon-alpha",
    codenames="유출과 로그에 **iris-alpha**(GPT-5.6과 가장 연관), **ember-alpha**, **beacon-alpha** 등이 언급됩니다. 공개 티어 매핑과 전부 출시 여부는 불명입니다.",
    codenames_table="| 코드명 | 현재 공개 정보 | 비고 |\n| --- | --- | --- |\n| iris-alpha | GPT-5.6 이름과 함께 등장 | 출시에 가장 가까운 빌드로 봄 |\n| ember-alpha | 로그 언급 | 역할 미정 |\n| beacon-alpha | 로그 언급 | 역할 미정 |",
    h_context="150만 컨텍스트: GPT-5.5 대비 얼마나 늘었나",
    context="유출에 따르면 GPT-5.6 컨텍스트는 약 **1,500,000 토큰**입니다. 현행 GPT-5.5 비교:",
    ctx_table="| 채널 / 버전 | 컨텍스트 상한(약) | 150만 대비 |\n| --- | --- | --- |\n| GPT-5.5 API | 1,050,000 tokens | 약 +43% |\n| GPT-5.5 (Codex OAuth) | 400,000 tokens | 약 +275% |\n| 유출 GPT-5.6 | 1,500,000 tokens | — |",
    context_note="긴 문서·리포 전체 리뷰·다단계 Agent에서는 수동 청크가 줄지만 비용·지연이 늘 수 있습니다.",
    h_test="초장문 스트레스 테스트(비공식)",
    test="커뮤니티는 **OpenCode** 등에서 입력 약 **90만 토큰**에도 응답, **105만 초과** 사례도 보고했습니다. 채널·빌드에 의존하며 **공식 SLA가 아닙니다**.",
    h_ui="UI 생성: 출시 가능한 프론트엔드에 더 가깝게",
    ui="유출 스크린샷에 짧은 프롬프트로 **Lumen Notes** 미니 메모 UI가 생성됐습니다—그리드·색·타이포가 더 정돈됐습니다. 공개 빌드에서도 같다면 **레이아웃 제약**이 강화됐을 수 있으나, 본판은 출시 후 벤치마크를 보세요.",
    h_release="출시 시점 읽는 법",
    release="확정된 출시일은 없습니다. 추적할 약한 신호:",
    sig_table="| 신호 | 설명 |\n| --- | --- |\n| 유출 타임라인 | 다수 **2026년 6월** 지목 |\n| 예측 시장 | 6/30 전 확률은 커뮤니티 기대이지 공식 약속 아님 |\n| 제품 속도 | GPT-5.5 약 3주 후 5.6 단서 |\n| 관찰 | 카나리 로그, 새 시스템 카드, Codex 라우팅, 정렬/보상 블로그 |",
    release_note="카나리 이름은 자주 나타났다 사라집니다—**로그 한 줄이 출시일은 아닙니다**.",
    h_unknown="아직 불명확한 점",
    unknown="파라미터·아키텍처 대변경 여부, API 가격, ChatGPT 플랜 동기화, goblin 정렬 수정의 시스템 카드 반영 등은 공식 발표를 기다려야 합니다.",
    h_guide="GPT 튜토리얼: 출시 전에 연습할 것",
    guide="GPT-5.6 전에 **GPT-5.5 / GPT-5.4**로 습관을 들이면 이전 비용이 줄어듭니다:\n\n1. **긴 입력 압축** 2. **Agent/코딩 중단 조건** 3. **UI는 단계적으로** 4. **고정 eval로 A/B**\n\n브라우저에서 쓰려면 아래 LimaxAI 버튼(**gpt-5.4**, 신모델은 목록에서).",
    h_sum="요약",
    sum_table="| 항목 | 현재 판단 |\n| --- | --- |\n| 공식 발표 | 없음 |\n| 컨텍스트 유출 | 약 150만 |\n| GPT-5.5 API 대비 | 약 +43% |\n| 시기 | 2026년 6월 다수, 미확정 |\n| 실무 | 현 GPT로 긴 컨텍스트·Agent 연습 후 시스템 카드 뒤 이전 |",
    sum_line="GPT-5.6이 제때 오고 전체 창이 열리는지는 다음 공지에 달렸습니다. 그전엔 손에 있는 GPT를 쓰는 편이 유출마다 스택을 바꾸는 것보다 낫습니다.",
    outro="LimaxAI에서 GPT를 시작하려면 아래 버튼에서 모델을 고르세요.",
)

# Spanish, French, German - full key sets
_add(
    "es",
    intro="Varios desarrolladores han visto referencias a **GPT-5.6** en los logs del backend de OpenAI Codex antes de cualquier anuncio oficial. Si los informes son correctos, la próxima generación podría ofrecer unos **1,5 millones de tokens** de contexto, con ventana de lanzamiento hacia **junio de 2026**. Separamos lo verificable de lo incierto y comparamos con GPT-5.5.",
    keywords="Palabras clave: chatgpt, GPT-5.6, tutorial gpt.",
    published="Publicado: 26 de mayo de 2026",
    img_alt="Filtración OpenAI GPT-5.6 ventana de 1,5M tokens",
    h_leak="De dónde salió la pista: un canario en los logs de Codex",
    leak="Unas tres semanas después de GPT-5.5, apareció una entrada de **enrutamiento en Codex**: casi todo a `gpt-5.5`, pero a veces a `gpt-5.6`, luego desapareció—más resto de despliegue que anuncio.\n\n**OpenAI no ha anunciado GPT-5.6.** Lo siguiente viene de logs, reproducciones y filtraciones.",
    h_codenames="Nombres internos: iris-alpha, ember-alpha, beacon-alpha",
    codenames="Mencionan **iris-alpha** (más ligado a GPT-5.6), **ember-alpha** y **beacon-alpha**. No está claro el mapeo a tiers públicos.",
    codenames_table="| Nombre | Info pública | Notas |\n| --- | --- | --- |\n| iris-alpha | Aparece con GPT-5.6 | Más cercano a versión final |\n| ember-alpha | En logs | Rol desconocido |\n| beacon-alpha | En logs | Rol desconocido |",
    h_context="Contexto de 1,5M: cuánto más que GPT-5.5",
    context="Las filtraciones apuntan a unos **1.500.000 tokens** para GPT-5.6:",
    ctx_table="| Canal / versión | Tope aprox. | vs. 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1.050.000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400.000 | ~+275% |\n| GPT-5.6 filtrado | 1.500.000 | — |",
    context_note="Menos troceado manual, pero más coste y latencia por llamada.",
    h_test="Pruebas de estrés (no oficiales)",
    test="En **OpenCode** y similares: ~**900k tokens** aún responden; algunos >**1,05M**. No es SLA oficial.",
    h_ui="Generación de UI: frontends más listos",
    ui="Filtraciones mostraron **Lumen Notes** con prompts cortos—rejillas y tipografía más limpias. Espera builds públicos antes de producción.",
    h_release="Cómo leer el calendario",
    release="Sin fecha confirmada. Señales débiles:",
    sig_table="| Señal | Notas |\n| --- | --- |\n| Filtraciones | Muchas apuntan a **junio 2026** |\n| Mercados | Probabilidades en Polymarket = expectativa comunitaria |\n| Ritmo | Pistas ~3 semanas tras GPT-5.5 |\n| Vigilar | Más canarios, system card, routing Codex |",
    release_note="Un log no es una fecha de lanzamiento.",
    h_unknown="Qué sigue sin saberse",
    unknown="Parámetros, precios API, planes ChatGPT y arreglos de alineación «goblin» esperan anuncio oficial.",
    h_guide="Tutorial GPT: practica antes del lanzamiento",
    guide="Con **GPT-5.5 / GPT-5.4** hoy: recorta entradas largas, define paradas en agentes, pide UI por capas y guarda un eval fijo. Botón abajo en LimaxAI (**gpt-5.4**).",
    h_sum="Resumen",
    sum_table="| Ítem | Lectura actual |\n| --- | --- |\n| Anunciado | No |\n| Contexto | ~1,5M |\n| vs API 5.5 | ~+43% |\n| Fecha | Jun 2026 rumoreado |\n| Consejo | Domina GPT actual; migra tras system card |",
    sum_line="Hasta el próximo comunicado de OpenAI, sacar más del GPT que ya tienes suele pagar más que rearmar todo por cada filtración.",
    outro="Para chatear con GPT en LimaxAI, usa el botón de abajo.",
)

_add(
    "fr",
    intro="Plusieurs développeurs ont repéré **GPT-5.6** dans les journaux backend d'OpenAI Codex avant toute annonce officielle. Si les fuites tiennent, la prochaine génération viserait environ **1,5 million de tokens** de contexte, avec une fenêtre vers **juin 2026**. Nous séparons le vérifiable de l'incertain et comparons à GPT-5.5.",
    keywords="Mots-clés : chatgpt, GPT-5.6, tutoriel gpt.",
    published="Publié le 26 mai 2026",
    img_alt="Fuite OpenAI GPT-5.6 contexte 1,5M",
    h_leak="Origine des indices : un canari dans les logs Codex",
    leak="Environ trois semaines après GPT-5.5, une entrée de **routage Codex** pointait parfois vers `gpt-5.6` puis disparaissait—plutôt un résidu de déploiement qu'une annonce.\n\n**OpenAI n'a pas annoncé GPT-5.6.** Le contenu ci-dessous vient de logs et fuites.",
    h_codenames="Noms internes : iris-alpha, ember-alpha, beacon-alpha",
    codenames="**iris-alpha** (lié à GPT-5.6), **ember-alpha**, **beacon-alpha**—rôles publics encore flous.",
    codenames_table="| Nom | Info publique | Notes |\n| --- | --- | --- |\n| iris-alpha | Avec le nom GPT-5.6 | Build le plus proche |\n| ember-alpha | Dans les logs | Rôle inconnu |\n| beacon-alpha | Dans les logs | Rôle inconnu |",
    h_context="Contexte 1,5M : par rapport à GPT-5.5",
    context="Les fuites évoquent environ **1 500 000 tokens** :",
    ctx_table="| Canal | Plafond approx. | vs 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1 050 000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400 000 | ~+275% |\n| GPT-5.6 fuité | 1 500 000 | — |",
    context_note="Moins de découpage manuel, mais coût et latence plus élevés.",
    h_test="Tests de stress (non officiels)",
    test="~**900k tokens** encore répondent ; certains >**1,05M**—pas un SLA.",
    h_ui="Génération d'UI",
    ui="**Lumen Notes** généré avec peu de prompt—grilles et typo plus propres. Attendre la version publique.",
    h_release="Lire le calendrier",
    release="Pas de date confirmée. Signaux faibles :",
    sig_table="| Signal | Notes |\n| --- | --- |\n| Fuites | Souvent **juin 2026** |\n| Marchés | Polymarket = attente communautaire |\n| Rythme | Indices ~3 semaines après 5.5 |\n| À suivre | Canaris, system card, routage Codex |",
    release_note="Une ligne de log n'est pas une date de sortie.",
    h_unknown="Encore inconnu",
    unknown="Paramètres, tarifs API, plans ChatGPT, correctifs « goblin »—à confirmer officiellement.",
    h_guide="Tutoriel GPT : s'entraîner avant le lancement",
    guide="Avec **GPT-5.5 / GPT-5.4** : compressez les entrées, définissez des arrêts pour les agents, découpez les demandes UI, gardez un jeu de tests fixe. Bouton LimaxAI ci-dessous (**gpt-5.4**).",
    h_sum="Synthèse",
    sum_table="| Point | Lecture |\n| --- | --- |\n| Annoncé | Non |\n| Contexte | ~1,5M |\n| vs API 5.5 | ~+43% |\n| Date | Juin 2026 souvent cité |\n| Conseil | Maîtriser le GPT actuel |",
    sum_line="La suite dépend du prochain communiqué OpenAI ; en attendant, exploitez le GPT que vous avez déjà.",
    outro="Pour discuter avec GPT sur LimaxAI, cliquez le bouton ci-dessous.",
)

_add(
    "de",
    intro="Mehrere Entwickler haben **GPT-5.6** in OpenAI-Codex-Backend-Logs gesehen, bevor es eine offizielle Ankündigung gab. Berichten zufolge könnte die nächste Generation rund **1,5 Millionen Token** Kontext bieten, Launch-Fenster **Juni 2026**. Wir trennen Verifizierbares von Unbekanntem und vergleichen mit GPT-5.5.",
    keywords="Schlüsselwörter: chatgpt, GPT-5.6, gpt tutorial.",
    published="Veröffentlicht: 26. Mai 2026",
    img_alt="OpenAI GPT-5.6 Leak 1,5M Kontext",
    h_leak="Woher der Hinweis kommt: ein Canary in Codex-Logs",
    leak="Etwa drei Wochen nach GPT-5.5 tauchte ein **Routing-Eintrag** kurz auf `gpt-5.6` auf und verschwand wieder.\n\n**OpenAI hat GPT-5.6 nicht angekündigt.**",
    h_codenames="Interne Codenamen",
    codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha**—öffentliche Zuordnung unklar.",
    codenames_table="| Codename | Öffentlich | Hinweis |\n| --- | --- | --- |\n| iris-alpha | Mit GPT-5.6 | Nächster Release-Kandidat |\n| ember-alpha | In Logs | unbekannt |\n| beacon-alpha | In Logs | unbekannt |",
    h_context="1,5M Kontext vs. GPT-5.5",
    context="Leaks nennen etwa **1.500.000 Token**:",
    ctx_table="| Kanal | Limit ca. | vs. 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1.050.000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400.000 | ~+275% |\n| GPT-5.6 Leak | 1.500.000 | — |",
    context_note="Weniger manuelles Chunking, höhere Kosten/Latenz.",
    h_test="Stresstests (inoffiziell)",
    test="~**900k Token** noch nutzbar; teils >**1,05M**—kein SLA.",
    h_ui="UI-Generierung",
    ui="**Lumen Notes** mit kurzem Prompt—saubereres Layout. Erst nach Release bewerten.",
    h_release="Zeitplan lesen",
    release="Kein festes Datum. Schwache Signale:",
    sig_table="| Signal | Notiz |\n| --- | --- |\n| Leaks | oft **Juni 2026** |\n| Märkte | Polymarket = Erwartung |\n| Tempo | ~3 Wochen nach 5.5 |\n| Beobachten | Canaries, System Card, Codex |",
    release_note="Ein Log ist kein Launch-Termin.",
    h_unknown="Noch unklar",
    unknown="Parameter, API-Preise, ChatGPT-Pläne, Goblin-Fixes—offizielle Ankündigung abwarten.",
    h_guide="GPT-Tutorial: vor dem Launch üben",
    guide="Mit **GPT-5.5 / GPT-5.4**: Eingaben kürzen, Stoppregeln für Agenten, UI schichtweise, festes Eval-Set. LimaxAI-Button unten (**gpt-5.4**).",
    h_sum="Kurzfassung",
    sum_table="| Punkt | Stand |\n| --- | --- |\n| Angekündigt | Nein |\n| Kontext | ~1,5M |\n| vs API 5.5 | ~+43% |\n| Termin | Juni 2026 Gerücht |\n| Tipp | Heutiges GPT nutzen |",
    sum_line="Ob GPT-5.6 pünktlich kommt, entscheidet OpenAI—bis dahin lohnt sich das GPT, das Sie schon haben.",
    outro="GPT auf LimaxAI starten: Button unten.",
)

def _clone_es(lang: str, intro: str, keywords: str, published: str, img_alt: str, outro: str, **overrides):
    """Build locale from Spanish template with overrides."""
    es = _LOCALE_OVERRIDES["es"].copy()
    es.update(
        intro=intro,
        keywords=keywords,
        published=published,
        img_alt=img_alt,
        outro=outro,
        **overrides,
    )
    _LOCALE_OVERRIDES[lang] = es


# Portuguese (full article from es template)
_clone_es(
    "pt",
    intro="Vários desenvolvedores viram **GPT-5.6** nos logs do backend do OpenAI Codex antes de qualquer anúncio oficial. Se os relatos forem corretos, a próxima geração pode oferecer cerca de **1,5 milhão de tokens** de contexto, com janela de lançamento em **junho de 2026**. Este artigo separa o que já dá para verificar do que ainda é incerto e compara com o GPT-5.5.",
    keywords="Palavras-chave: chatgpt, GPT-5.6, tutorial gpt.",
    published="Publicado: 26 de maio de 2026",
    img_alt="Vazamento OpenAI GPT-5.6 janela de 1,5M tokens",
    outro="Para conversar com GPT no LimaxAI, use o botão abaixo.",
    h_leak="De onde veio a pista: um canário nos logs do Codex",
    leak="Cerca de três semanas após o GPT-5.5, apareceu uma **entrada de roteamento no Codex**: quase tudo ia para `gpt-5.5`, mas algumas sessões apontaram brevemente para `gpt-5.6`, depois sumiu—mais resto de deploy do que anúncio.\n\n**A OpenAI não anunciou o GPT-5.6.** O texto abaixo vem de logs, reproduções e vazamentos.",
    h_codenames="Nomes internos: iris-alpha, ember-alpha, beacon-alpha",
    codenames="Citam-se **iris-alpha** (mais ligado ao GPT-5.6), **ember-alpha** e **beacon-alpha**. Não está claro o mapeamento para tiers públicos.",
    codenames_table="| Nome | Info pública hoje | Notas |\n| --- | --- | --- |\n| iris-alpha | Aparece com o nome GPT-5.6 | Mais próximo de build final |\n| ember-alpha | Nos logs | Papel desconhecido |\n| beacon-alpha | Nos logs | Papel desconhecido |",
    h_context="Contexto de 1,5M: quanto a mais que o GPT-5.5",
    context="Os vazamentos apontam para cerca de **1.500.000 tokens** no GPT-5.6:",
    ctx_table="| Canal / versão | Teto aprox. | vs. 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1.050.000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400.000 | ~+275% |\n| GPT-5.6 (vazamento) | 1.500.000 | — |",
    context_note="Menos fatiamento manual, mas mais custo e latência por chamada.",
    h_test="Testes de estresse (não oficiais)",
    test="Em **OpenCode** e similares: ~**900k tokens** ainda respondem; alguns >**1,05M**. Não é SLA oficial.",
    h_ui="Geração de UI: frontends mais prontos",
    ui="Vazamentos mostraram **Lumen Notes** com prompts curtos—grades e tipografia mais limpas. Espere builds públicos antes de produção.",
    h_release="Como ler o calendário",
    release="Sem data confirmada. Sinais fracos:",
    sig_table="| Sinal | Notas |\n| --- | --- |\n| Vazamentos | Muitos apontam **junho de 2026** |\n| Mercados | Polymarket = expectativa da comunidade |\n| Ritmo | Pistas ~3 semanas após GPT-5.5 |\n| Observar | Mais canários, system card, roteamento Codex |",
    release_note="Uma linha de log não é data de lançamento.",
    h_unknown="O que ainda não se sabe",
    unknown="Parâmetros, preços de API, planos ChatGPT e correções de alinhamento «goblin» dependem de anúncio oficial.",
    h_guide="Tutorial GPT: pratique antes do lançamento",
    guide="Com **GPT-5.5 / GPT-5.4** hoje: encurte entradas longas, defina paradas em agentes, peça UI em camadas e mantenha um conjunto de testes fixo. Botão LimaxAI abaixo (**gpt-5.4**).",
    h_sum="Resumo",
    sum_table="| Item | Leitura atual |\n| --- | --- |\n| Anunciado | Não |\n| Contexto | ~1,5M |\n| vs API 5.5 | ~+43% |\n| Data | Junho 2026 (rumor) |\n| Dica | Domine o GPT atual; migre após system card |",
    sum_line="Até o próximo comunicado da OpenAI, tirar mais proveito do GPT que você já tem costuma valer mais do que reestruturar tudo a cada vazamento.",
)

# Italian
_clone_es(
    "it",
    intro="Diversi sviluppatori hanno visto **GPT-5.6** nei log backend di OpenAI Codex prima di un annuncio ufficiale. Se le fughe fossero attendibili, la prossima generazione potrebbe offrire circa **1,5 milioni di token** di contesto, con finestra di lancio verso **giugno 2026**. Separiamo ciò che è verificabile da ciò che resta incerto e confrontiamo con GPT-5.5.",
    keywords="Parole chiave: chatgpt, GPT-5.6, tutorial gpt.",
    published="Pubblicato: 26 maggio 2026",
    img_alt="Fuga OpenAI GPT-5.6 contesto 1,5M token",
    outro="Per usare GPT su LimaxAI, clicca il pulsante sotto.",
    h_leak="Da dove viene l'indizio: un canary nei log Codex",
    leak="Circa tre settimane dopo GPT-5.5, nei **log di routing Codex** è comparsa una voce verso `gpt-5.6` poi scomparsa—più residuo di deploy che annuncio.\n\n**OpenAI non ha annunciato GPT-5.6.**",
    h_codenames="Nomi interni: iris-alpha, ember-alpha, beacon-alpha",
    codenames="Si citano **iris-alpha**, **ember-alpha**, **beacon-alpha**; mapping ai tier pubblici ancora incerto.",
    codenames_table="| Nome | Info pubblica | Note |\n| --- | --- | --- |\n| iris-alpha | Con il nome GPT-5.6 | Build più vicina al rilascio |\n| ember-alpha | Nei log | Ruolo sconosciuto |\n| beacon-alpha | Nei log | Ruolo sconosciuto |",
    h_context="Contesto 1,5M rispetto a GPT-5.5",
    context="Le fughe indicano circa **1.500.000 token** per GPT-5.6:",
    ctx_table="| Canale | Limite ca. | vs 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1.050.000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400.000 | ~+275% |\n| GPT-5.6 (fuga) | 1.500.000 | — |",
    context_note="Meno chunk manuale, più costo e latenza.",
    h_test="Stress test (non ufficiali)",
    test="~**900k token** ancora rispondono; alcuni >**1,05M**—non è SLA.",
    h_ui="Generazione UI",
    ui="**Lumen Notes** con prompt brevi—layout più pulito. Attendere build pubbliche.",
    h_release="Leggere il calendario",
    release="Nessuna data confermata. Segnali deboli:",
    sig_table="| Segnale | Note |\n| --- | --- |\n| Fughe | Spesso **giugno 2026** |\n| Mercati | Polymarket = aspettativa community |\n| Ritmo | Indizi ~3 settimane dopo 5.5 |\n| Da seguire | Canari, system card, routing Codex |",
    release_note="Una riga di log non è una data di uscita.",
    h_unknown="Ancora sconosciuto",
    unknown="Parametri, prezzi API, piani ChatGPT, fix «goblin»—serve annuncio ufficiale.",
    h_guide="Tutorial GPT: allenarsi prima del lancio",
    guide="Con **GPT-5.5 / GPT-5.4**: comprimi input lunghi, regole di stop per agenti, UI a strati, set di test fisso. Pulsante LimaxAI (**gpt-5.4**).",
    h_sum="Sintesi",
    sum_table="| Voce | Lettura |\n| --- | --- |\n| Annunciato | No |\n| Contesto | ~1,5M |\n| vs API 5.5 | ~+43% |\n| Data | Giugno 2026 (voce) |\n| Consiglio | Usa bene il GPT attuale |",
    sum_line="Il resto dipende dal prossimo comunicato OpenAI; fino ad allora conviene sfruttare il GPT che hai già.",
)

# Russian
_add(
    "ru",
    intro="Несколько разработчиков заметили **GPT-5.6** в логах бэкенда OpenAI Codex до официального анонса. По утечкам, следующее поколение может дать около **1,5 млн токенов** контекста, окно выхода — **июнь 2026**. Мы отделяем проверяемое от неизвестного и сравниваем с GPT-5.5.",
    keywords="Ключевые слова: chatgpt, GPT-5.6, урок gpt.",
    published="Опубликовано: 26 мая 2026 г.",
    img_alt="Утечка OpenAI GPT-5.6 контекст 1,5M",
    h_leak="Откуда след: «канарейка» в логах Codex",
    leak="Примерно через три недели после GPT-5.5 в **логах маршрутизации Codex** появилась запись на `gpt-5.6`, затем исчезла — скорее остаток деплоя, чем анонс.\n\n**OpenAI не объявляла GPT-5.6.** Ниже — логи, воспроизведения и утечки.",
    h_codenames="Внутренние кодовые имена",
    codenames="Упоминаются **iris-alpha**, **ember-alpha**, **beacon-alpha**; публичное соответствие неясно.",
    codenames_table="| Имя | Что известно | Примечание |\n| --- | --- | --- |\n| iris-alpha | Рядом с именем GPT-5.6 | Ближе к релизу |\n| ember-alpha | В логах | Роль неизвестна |\n| beacon-alpha | В логах | Роль неизвестна |",
    h_context="Контекст 1,5M против GPT-5.5",
    context="Утечки указывают на ~**1 500 000 токенов**:",
    ctx_table="| Канал | Лимит (ок.) | к 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1 050 000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400 000 | ~+275% |\n| GPT-5.6 (утечка) | 1 500 000 | — |",
    context_note="Меньше ручной нарезки, выше стоимость и задержка вызова.",
    h_test="Стресс-тесты (неофициально)",
    test="В **OpenCode** и др.: ~**900k токенов** ещё отвечают; есть случаи >**1,05M** — не SLA.",
    h_ui="Генерация UI",
    ui="На скриншотах — **Lumen Notes** с коротким промптом. Ждите публичные сборки.",
    h_release="Как читать сроки",
    release="Даты нет. Слабые сигналы:",
    sig_table="| Сигнал | Заметки |\n| --- | --- |\n| Утечки | Часто **июнь 2026** |\n| Рынки | Polymarket = ожидание сообщества |\n| Темп | ~3 недели после 5.5 |\n| Следить | Канарейки, system card, Codex |",
    release_note="Строка в логе — не дата релиза.",
    h_unknown="Что ещё неясно",
    unknown="Параметры, цены API, планы ChatGPT, правки goblin — ждём официального анонса.",
    h_guide="Урок GPT: что отработать до релиза",
    guide="На **GPT-5.5 / GPT-5.4**: сжимайте длинный ввод, задавайте стоп-правила агентам, UI по слоям, фиксированный eval. Кнопка LimaxAI (**gpt-5.4**).",
    h_sum="Итог",
    sum_table="| Пункт | Оценка |\n| --- | --- |\n| Анонс | Нет |\n| Контекст | ~1,5M |\n| к API 5.5 | ~+43% |\n| Срок | Июнь 2026 (слух) |\n| Совет | Освойте текущий GPT |",
    sum_line="Сроки и полное окно решит OpenAI; пока выгоднее выжать максимум из уже доступного GPT.",
    outro="Чтобы начать чат с GPT на LimaxAI, нажмите кнопку ниже.",
)

# Ukrainian (from Russian structure)
_clone_es(
    "uk",
    intro="Кілька розробників побачили **GPT-5.6** у логах OpenAI Codex до офіційного анонсу. За чутками — близько **1,5 млн токенів** контексту та вікно **червня 2026**. Розділяємо перевірене й невідоме, порівнюємо з GPT-5.5.",
    keywords="Ключові слова: chatgpt, GPT-5.6, урок gpt.",
    published="Опубліковано: 26 травня 2026",
    img_alt="Витік OpenAI GPT-5.6 контекст 1,5M",
    outro="Щоб почати GPT у LimaxAI, натисніть кнопку нижче.",
    h_leak="Звідки слід: «канарейка» в логах Codex",
    leak="Близько трьох тижнів після GPT-5.5 у **логах маршрутизації Codex** з’явився запис на `gpt-5.6`, потім зник.\n\n**OpenAI не оголошувала GPT-5.6.**",
    h_codenames="Внутрішні кодові імена",
    codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha** — публічне відповідність неясне.",
    codenames_table="| Ім’я | Відомо | Примітка |\n| --- | --- | --- |\n| iris-alpha | Поруч із GPT-5.6 | Найближче до релізу |\n| ember-alpha | У логах | Невідомо |\n| beacon-alpha | У логах | Невідомо |",
    h_context="Контекст 1,5M проти GPT-5.5",
    context="Чутки вказують на ~**1 500 000 токенів**:",
    ctx_table="| Канал | Ліміт | до 1,5M |\n| --- | --- | --- |\n| GPT-5.5 API | 1 050 000 | ~+43% |\n| GPT-5.5 (Codex OAuth) | 400 000 | ~+275% |\n| GPT-5.6 | 1 500 000 | — |",
    context_note="Менше ручної нарізки, вища вартість і затримка.",
    h_test="Стрес-тести (неофіційно)",
    test="~**900k токенів** ще працюють; інколи >**1,05M** — не SLA.",
    h_ui="Генерація UI",
    ui="**Lumen Notes** з коротким промптом — чекайте публічні збірки.",
    h_release="Як читати терміни",
    release="Дати немає. Слабкі сигнали:",
    sig_table="| Сигнал | Нотатки |\n| --- | --- |\n| Чутки | Часто **червень 2026** |\n| Ринки | Polymarket = очікування |\n| Темп | ~3 тижні після 5.5 |\n| Стежити | Канарейки, system card |",
    release_note="Рядок у лозі — не дата релізу.",
    h_unknown="Що ще неясно",
    unknown="Параметри, ціни API, плани ChatGPT — чекаємо офіційного анонсу.",
    h_guide="Урок GPT: що відпрацювати",
    guide="На **GPT-5.5 / GPT-5.4**: стискайте ввід, стоп-правила агентів, UI шарами. LimaxAI (**gpt-5.4**).",
    h_sum="Підсумок",
    sum_table="| Пункт | Оцінка |\n| --- | --- |\n| Анонс | Ні |\n| Контекст | ~1,5M |\n| до API 5.5 | ~+43% |\n| Термін | Червень 2026 (чутка) |",
    sum_line="Терміни вирішить OpenAI; поки вигідніше використати наявний GPT.",
)

# Polish, Dutch, Swedish, Romanian — partial overrides (completed in gpt56_locales_fix)
for _lc, _data in {
    "pl": dict(
        intro="Kilku deweloperów zauważyło **GPT-5.6** w logach OpenAI Codex przed oficjalnym ogłoszeniem. Przecieki wskazują ~**1,5 mln tokenów** kontekstu i **czerwiec 2026**. Rozdzielamy to, co da się zweryfikować, od niepewności i porównujemy z GPT-5.5.",
        keywords="Słowa kluczowe: chatgpt, GPT-5.6, samouczek gpt.",
        published="Opublikowano: 26 maja 2026",
        img_alt="Wyciek OpenAI GPT-5.6 kontekst 1,5M",
        outro="Aby czatować z GPT na LimaxAI, użyj przycisku poniżej.",
        h_leak="Skąd trop: kanarek w logach Codex",
        leak="Około trzech tygodni po GPT-5.5 w **logach routingu Codex** pojawił się wpis `gpt-5.6`, potem zniknął.\n\n**OpenAI nie ogłosiło GPT-5.6.**",
        h_codenames="Wewnętrzne nazwy kodowe",
        codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha** — mapowanie na tiery publiczne niejasne.",
        h_context="Kontekst 1,5M vs GPT-5.5",
        context="Przecieki: ok. **1 500 000 tokenów**.",
        h_test="Testy obciążeniowe (nieoficjalne)",
        test="~**900k tokenów** nadal działa; czasem >**1,05M** — to nie SLA.",
        h_ui="Generowanie UI",
        ui="**Lumen Notes** przy krótkim prompcie — czekaj na buildy publiczne.",
        h_release="Jak czytać harmonogram",
        release="Brak potwierdzonej daty. Słabe sygnały:",
        h_unknown="Co nadal niejasne",
        unknown="Parametry, ceny API, plany ChatGPT — czekamy na ogłoszenie.",
        h_guide="Samouczek GPT przed premierą",
        guide="Na **GPT-5.5 / GPT-5.4**: skracaj wejście, reguły stopu dla agentów, UI warstwami. LimaxAI (**gpt-5.4**).",
        h_sum="Podsumowanie",
        sum_line="Termin zdecyduje OpenAI; na razie lepiej wykorzystać GPT, który już masz.",
    ),
    "nl": dict(
        intro="Meerdere ontwikkelaars zagen **GPT-5.6** in OpenAI Codex-logs vóór een officiële aankondiging. Leaks wijzen op ~**1,5 miljoen tokens** en **juni 2026**. We scheiden verifieerbaar van onzeker en vergelijken met GPT-5.5.",
        keywords="Trefwoorden: chatgpt, GPT-5.6, gpt tutorial.",
        published="Gepubliceerd: 26 mei 2026",
        img_alt="OpenAI GPT-5.6-leak 1,5M context",
        outro="Start GPT op LimaxAI via de knop hieronder.",
        h_leak="Waar de aanwijzing vandaan komt",
        leak="~3 weken na GPT-5.5 verscheen kort een **routingregel** naar `gpt-5.6` in Codex-logs.\n\n**OpenAI heeft GPT-5.6 niet aangekondigd.**",
        h_codenames="Interne codenamen",
        codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha**.",
        h_context="1,5M context vs GPT-5.5",
        context="Leaks: ~**1.500.000 tokens**.",
        h_test="Stresstests (onofficieel)",
        test="~**900k tokens** werkt nog; soms >**1,05M** — geen SLA.",
        h_ui="UI-generatie",
        ui="**Lumen Notes** met korte prompts.",
        h_release="Releasekalender lezen",
        release="Geen bevestigde datum.",
        h_unknown="Nog onduidelijk",
        unknown="Parameters, API-prijzen, ChatGPT-plannen — wacht op aankondiging.",
        h_guide="GPT-tutorial vóór launch",
        guide="Met **GPT-5.5 / GPT-5.4**: inkorten, stopregels, UI in lagen. LimaxAI (**gpt-5.4**).",
        h_sum="Samenvatting",
        sum_line="OpenAI beslist over timing; tot dan haal meer uit je huidige GPT.",
    ),
    "sv": dict(
        intro="Flera utvecklare såg **GPT-5.6** i OpenAI Codex-loggar före officiellt besked. Läckor pekar på ~**1,5 miljoner tokens** och **juni 2026**.",
        keywords="Nyckelord: chatgpt, GPT-5.6, gpt guide.",
        published="Publicerad: 26 maj 2026",
        img_alt="OpenAI GPT-5.6-läcka 1,5M kontext",
        outro="Starta GPT på LimaxAI med knappen nedan.",
        h_leak="Var ledtråden kom ifrån",
        leak="~3 veckor efter GPT-5.5 syntes kort `gpt-5.6` i **Codex-routing**.\n\n**OpenAI har inte annonserat GPT-5.6.**",
        h_codenames="Interna kodnamn",
        codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha**.",
        h_context="1,5M kontext vs GPT-5.5",
        context="Läckor: ~**1 500 000 tokens**.",
        h_test="Stresstester (inofficiella)",
        test="~**900k tokens** fungerar; ibland >**1,05M** — inte SLA.",
        h_ui="UI-generering",
        ui="**Lumen Notes** med korta prompts.",
        h_release="Tidslinje",
        release="Inget bekräftat datum.",
        h_unknown="Fortfarande oklart",
        unknown="Parametrar, API-priser — vänta på besked.",
        h_guide="GPT-guide före lansering",
        guide="Med **GPT-5.5 / GPT-5.4**: korta indata, stoppregler, UI i lager. LimaxAI (**gpt-5.4**).",
        h_sum="Sammanfattning",
        sum_line="OpenAI avgör timing; tills dess, använd GPT du redan har.",
    ),
    "ro": dict(
        intro="Mai mulți dezvoltatori au văzut **GPT-5.6** în jurnalele Codex înainte de anunț oficial. Zvonurile indică ~**1,5 milioane tokeni** și **iunie 2026**.",
        keywords="Cuvinte cheie: chatgpt, GPT-5.6, tutorial gpt.",
        published="Publicat: 26 mai 2026",
        img_alt="Scurgere OpenAI GPT-5.6 context 1,5M",
        outro="Pentru GPT pe LimaxAI, folosiți butonul de mai jos.",
        h_leak="De unde vine indiciul",
        leak="La ~3 săptămâni după GPT-5.5, o intrare **Codex** spre `gpt-5.6` a dispărut rapid.\n\n**OpenAI nu a anunțat GPT-5.6.**",
        h_codenames="Nume interne",
        codenames="**iris-alpha**, **ember-alpha**, **beacon-alpha**.",
        h_context="Context 1,5M vs GPT-5.5",
        context="Zvonuri: ~**1.500.000 tokeni**.",
        h_test="Teste de stres (neoficiale)",
        test="~**900k tokeni** încă răspund; uneori >**1,05M**.",
        h_ui="Generare UI",
        ui="**Lumen Notes** cu prompt scurt.",
        h_release="Calendar",
        release="Fără dată confirmată.",
        h_unknown="Încă neclar",
        unknown="Parametri, prețuri API — așteptați anunțul.",
        h_guide="Tutorial GPT înainte de lansare",
        guide="Cu **GPT-5.5 / GPT-5.4**: scurtați intrarea, reguli de oprire. LimaxAI (**gpt-5.4**).",
        h_sum="Rezumat",
        sum_line="OpenAI decide termenul; până atunci, folosiți GPT-ul actual.",
    ),
}.items():
    _defaults = _LOCALE_OVERRIDES["es"].copy()
    _defaults.update(_data)
    _LOCALE_OVERRIDES[_lc] = _defaults

try:
    from gpt56_locales_fix import apply_locale_fixes
except ImportError:
    from scripts.gpt56_locales_fix import apply_locale_fixes  # type: ignore

apply_locale_fixes(_LOCALE_OVERRIDES, _LOCALE_OVERRIDES["es"])


def build_sections(lang: str) -> dict:
    if lang == "zh-tw":
        return _zh_tw()
    base = _en()
    if lang in _LOCALE_OVERRIDES:
        base.update(_LOCALE_OVERRIDES[lang])
    return base


FULL_SECTIONS = {
    lang: build_sections(lang)
    for lang in [
        "zh-tw",
        "ja",
        "ko",
        "es",
        "fr",
        "de",
        "pt",
        "it",
        "ru",
        "uk",
        "pl",
        "nl",
        "sv",
        "ro",
        "ar",
        "id",
        "ms",
        "vi",
        "th",
        "tr",
        "hi",
        "fa",
    ]
}
