# Extra fully-localized section bodies for GPT 5.5 blog locales.

EXTRA_SECTIONS: dict[str, dict[str, str]] = {
    "ru": {
        "intro": "OpenAI опубликовал официальное руководство по промптам GPT-5.5. Пошаговые инструкции старых моделей могут сужать возможности модели. Ниже — 7 ключевых изменений.",
        "keywords": "Ключевые слова: chatgpt, gpt 5.5, урок gpt.",
        "published": "Дата: 22 мая 2026 г.",
        "img_alt": "Руководство по промптам GPT 5.5 OpenAI",
        "h_bg": "Контекст: зачем переписывать старые промпты",
        "bg": "Старые промпты часто **перегружают процесс** — раньше моделям нужны были жёсткие рельсы. С GPT-5.5 это шум: сужает пространство поиска и даёт механические ответы. **Перепишите с нуля**, не копируйте старые шаблоны.",
        "h1": "Изменение 1: от пошаговости к результату",
        "c1": "**Было:** проверить A, B, исключения, выбрать инструмент, объяснить каждый шаг.\n\n**Стало:** полностью решить задачу пользователя; действовать по политике и данным; отчитаться о сделанном и остатке; задать один критический вопрос при нехватке данных.\n\n**Опишите пункт назначения, а не каждый поворот.**",
        "h2": "Изменение 2: меньше «обязательно» и «запрещено»",
        "c2": "GPT-5.5 чувствителен к абсолютным формулировкам; противоречивые «должен» ломают оба правила.",
        "tbl_h1": "Ситуация", "tbl_h2": "Стиль",
        "tbl_r1": "Безопасность, обязательные поля", "tbl_r1b": "всегда/никогда",
        "tbl_r2": "Искать или спрашивать", "tbl_r2b": "условия",
        "c2_ex": "Пример: вместо «перед ответом обязательно искать» — «если контекста достаточно, отвечай без поиска».",
        "h3": "Изменение 3: роль снова нужна, но коротко",
        "c3": "**Role** — 1–2 предложения о функции; **Personality** — тон и стиль совместной работы, не резюме на 20 лет.",
        "h4": "Изменение 4: преамбула перед многошаговой работой",
        "c4": "Перед инструментами отправьте 1–2 видимых предложения: запрос принят, первый шаг — …",
        "h5": "Изменение 5: явные условия остановки",
        "c5": "1. **Бюджет поиска:** по умолчанию один раунд. 2. **Стоп цикла:** после каждого инструмента — хватает ли доказательств на главный вопрос?",
        "h6": "Изменение 6: скелет из 7 блоков",
        "c6_table": "| Блок | Назначение |\n| --- | --- |\n| Role | Функция |\n| Personality | Тон |\n| Goal | Результат |\n| Success | Готово |\n| Constraints | Границы |\n| Output | Формат |\n| Stop | Когда остановиться |",
        "c6_note": "Для простых вопросов достаточно Goal + Output.",
        "h7": "Изменение 7: формат и краткость",
        "c7": "Используйте `text.verbosity` и Structured Outputs. В переписывании сначала укажите, **что сохранить**.",
        "h_mig": "Миграция: reasoning с низкого уровня",
        "mig": "Пересмотрите `reasoning.effort`: по умолчанию medium, часто хватает low. Повышайте только по метрикам качества.",
        "h_sum": "Итог",
        "sum_line": "**Скажите, что нужно — не каждый шаг выполнения.**",
        "sum_table": "| Измерение | Раньше | GPT-5.5 |\n| --- | --- | --- |\n| Процесс | Подробные шаги | Результат |\n| Тон | Много абсолютов | Абсолюты только для красных линий |\n| Роль | Длинные био | Коротко |\n| Многошаг | Сразу в работу | Сначала преамбула |\n| Стоп | Часто нет | Явно |\n| Структура | Свободно | 7 блоков |\n| Формат | По умолчанию | API + промпт |",
        "outro": "Протестируйте на реальных задачах, затем попробуйте GPT на LimaxAI кнопкой ниже.",
    },
    "uk": {
        "intro": "OpenAI опублікував офіційний гайд із промптів GPT-5.5. Покрокові інструкції старих моделей можуть обмежувати модель. Ось 7 ключових змін.",
        "keywords": "Ключові слова: chatgpt, gpt 5.5, урок gpt.",
        "published": "Дата: 22 травня 2026",
        "img_alt": "Гайд промптів GPT 5.5 OpenAI",
        "h_bg": "Контекст: навіщо переписувати старі промпти",
        "bg": "Старі промпти часто **перевантажують процес**. З GPT-5.5 це шум — **перепишіть з нуля**.",
        "h1": "Зміна 1: від покроковості до результату",
        "c1": "**Було:** A, B, винятки, інструмент, пояснити кожен крок.\n\n**Стало:** повністю вирішити запит; діяти за політикою та даними; звіт; одне критичне питання.\n\n**Опишіть пункт призначення, не кожен поворот.**",
        "h2": "Зміна 2: менше «обов'язково»",
        "c2": "GPT-5.5 чутливий до абсолютів; суперечливі правила ламаються.",
        "tbl_h1": "Ситуація", "tbl_h2": "Стиль",
        "tbl_r1": "Безпека, обов'язкові поля", "tbl_r1b": "завжди/ніколи",
        "tbl_r2": "Шукати чи питати", "tbl_r2b": "умови",
        "c2_ex": "Замість «обов'язково шукати» — «якщо контексту достатньо, відповідай без пошуку».",
        "h3": "Зміна 3: коротка роль",
        "c3": "**Role** 1–2 речення; **Personality** — тон і співпраця.",
        "h4": "Зміна 4: преамбула",
        "c4": "Перед інструментами — 1–2 видимі речення про прийом запиту та перший крок.",
        "h5": "Зміна 5: умови зупинки",
        "c5": "Бюджет пошуку (1 раунд) + зупинка, коли доказів достатньо.",
        "h6": "Зміна 6: скелет із 7 блоків",
        "c6_table": "| Блок | Призначення |\n| --- | --- |\n| Role | Функція |\n| Personality | Тон |\n| Goal | Результат |\n| Success | Готово |\n| Constraints | Межі |\n| Output | Формат |\n| Stop | Зупинка |",
        "c6_note": "Простим запитам часто вистачає Goal + Output.",
        "h7": "Зміна 7: формат",
        "c7": "`text.verbosity`, Structured Outputs; у переписуванні спочатку «що зберегти».",
        "h_mig": "Міграція: reasoning з низького",
        "mig": "Перегляньте `reasoning.effort`; часто вистачає low.",
        "h_sum": "Підсумок",
        "sum_line": "**Скажіть, що потрібно — не кожен крок.**",
        "sum_table": "| Вимір | Раніше | GPT-5.5 |\n| --- | --- | --- |\n| Процес | Кроки | Результат |\n| Тон | Абсолюти | Лише червоні лінії |\n| Роль | Довго | Коротко |\n| Багатокрок | Одразу | Преамбула |\n| Стоп | Немає | Явно |\n| Структура | Вільно | 7 блоків |\n| Формат | За замовч. | API+prompt |",
        "outro": "Протестуйте на реальних задачах і спробуйте GPT на LimaxAI.",
    },
    "pl": {
        "intro": "OpenAI opublikował oficjalny przewodnik promptów GPT-5.5. Prompty krok po kroku ze starych modeli mogą ograniczać wyniki. Oto 7 kluczowych zmian.",
        "keywords": "Słowa kluczowe: chatgpt, gpt 5.5, samouczek gpt.",
        "published": "Data: 22 maja 2026",
        "img_alt": "Przewodnik promptów GPT 5.5",
        "h_bg": "Tło: dlaczego przepisać stare prompty",
        "bg": "Stare prompty **nadmiernie opisują proces**. Przy GPT-5.5 to szum — **przepisz od zera**.",
        "h1": "Zmiana 1: z procesu na wynik",
        "c1": "**Było:** A, B, wyjątki, narzędzie, wyjaśnij wszystko.\n\n**Jest:** rozwiąż problem; działaj wg polityki i danych; raport; jedno kluczowe pytanie.\n\n**Opisz cel, nie każdy krok.**",
        "h2": "Zmiana 2: mniej absolutów",
        "c2": "GPT-5.5 jest wrażliwy na «musi/zawsze»; sprzeczne reguły zawodzą.",
        "tbl_h1": "Sytuacja", "tbl_h2": "Styl",
        "tbl_r1": "Bezpieczeństwo, pola wymagane", "tbl_r1b": "zawsze/nigdy",
        "tbl_r2": "Szukać czy pytać", "tbl_r2b": "warunki",
        "c2_ex": "Zamiast «musi szukać» — «jeśli kontekst wystarcza, odpowiedz bez szukania».",
        "h3": "Zmiana 3: krótka rola",
        "c3": "**Rola** 1–2 zdania; **osobowość** = ton i współpraca.",
        "h4": "Zmiana 4: preambuła",
        "c4": "Przed narzędziami: 1–2 widoczne zdania o przyjęciu zadania i pierwszym kroku.",
        "h5": "Zmiana 5: warunki stopu",
        "c5": "Budżet wyszukiwania (1 runda) + stop, gdy dowody wystarczają.",
        "h6": "Zmiana 6: szkielet 7 części",
        "c6_table": "| Część | Cel |\n| --- | --- |\n| Rola | Funkcja |\n| Osobowość | Ton |\n| Cel | Deliverable |\n| Sukces | Gotowe |\n| Ograniczenia | Granice |\n| Wyjście | Format |\n| Stop | Kiedy przestać |",
        "c6_note": "Proste Q&A: często Cel + Wyjście.",
        "h7": "Zmiana 7: format",
        "c7": "`text.verbosity`, Structured Outputs; przy przeróbce najpierw «co zachować».",
        "h_mig": "Migracja: reasoning od niskiego",
        "mig": "Sprawdź `reasoning.effort`; często wystarczy low.",
        "h_sum": "Podsumowanie",
        "sum_line": "**Powiedz, czego chcesz — nie każdego kroku.**",
        "sum_table": "| Wymiar | Wcześniej | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Kroki | Wynik |\n| Ton | Absoluty | Tylko czerwone linie |\n| Rola | Długo | Krótko |\n| Wieloetap | Od razu | Preambuła |\n| Stop | Brak | Jawny |\n| Struktura | Wolna | 7 części |\n| Format | Domyślny | API+prompt |",
        "outro": "Przetestuj na realnych zadaniach i wypróbuj GPT na LimaxAI.",
    },
    "nl": {
        "intro": "OpenAI publiceerde de officiële GPT-5.5-promptgids. Stap-voor-stap-prompts van oudere modellen kunnen prestaties beperken. Zeven belangrijke wijzigingen.",
        "keywords": "Trefwoorden: chatgpt, gpt 5.5, gpt tutorial.",
        "published": "Gepubliceerd: 22 mei 2026",
        "img_alt": "GPT 5.5 promptgids OpenAI",
        "h_bg": "Achtergrond: waarom opnieuw schrijven",
        "bg": "Oude prompts **specificeren het proces te veel**. Bij GPT-5.5 is dat ruis—**schrijf opnieuw**.",
        "h1": "Wijziging 1: van proces naar resultaat",
        "c1": "**Oud:** A, B, uitzonderingen, tool, alles uitleggen.\n\n**Nieuw:** probleem oplossen; handelen met beleid/data; rapporteren; één kritische vraag.\n\n**Beschrijf de bestemming, niet elke stap.**",
        "h2": "Wijziging 2: minder absoluten",
        "c2": "GPT-5.5 is gevoelig voor moet/altijd; tegenstrijdige regels falen.",
        "tbl_h1": "Situatie", "tbl_h2": "Stijl",
        "tbl_r1": "Veiligheid, verplichte velden", "tbl_r1b": "altijd/nooit",
        "tbl_r2": "Zoeken of vragen", "tbl_r2b": "voorwaarden",
        "c2_ex": "Vervang «moet zoeken» door «antwoord zonder zoeken als context volstaat».",
        "h3": "Wijziging 3: korte rol",
        "c3": "**Rol** in 1–2 zinnen; **persoonlijkheid** = toon en samenwerking.",
        "h4": "Wijziging 4: preambule",
        "c4": "Vóór tools: 1–2 zichtbare zinnen over ontvangst en eerste actie.",
        "h5": "Wijziging 5: stopregels",
        "c5": "Zoekbudget (1 ronde) + stoppen wanneer bewijs de kernvraag beantwoordt.",
        "h6": "Wijziging 6: zevendelig skelet",
        "c6_table": "| Deel | Doel |\n| --- | --- |\n| Rol | Functie |\n| Persoonlijkheid | Toon |\n| Doel | Output |\n| Succes | Klaar |\n| Beperkingen | Grenzen |\n| Output | Formaat |\n| Stop | Wanneer stoppen |",
        "c6_note": "Eenvoudige Q&A: vaak Doel + Output.",
        "h7": "Wijziging 7: formaat",
        "c7": "`text.verbosity`, Structured Outputs; bij herschrijven eerst «behouden».",
        "h_mig": "Migratie: reasoning laag",
        "mig": "Herzie `reasoning.effort`; vaak volstaat low.",
        "h_sum": "Samenvatting",
        "sum_line": "**Zeg wat je wilt—niet elke stap.**",
        "sum_table": "| Dimensie | Voorheen | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Stappen | Resultaat |\n| Toon | Absoluten | Alleen rode lijnen |\n| Rol | Lang | Kort |\n| Multi-step | Direct | Preambule |\n| Stop | Ontbreekt | Expliciet |\n| Structuur | Vrij | 7 delen |\n| Formaat | Default | API+prompt |",
        "outro": "Test op echte taken en probeer GPT via LimaxAI.",
    },
    "sv": {
        "intro": "OpenAI publicerade den officiella GPT-5.5-promptguiden. Steg-för-steg-prompts från äldre modeller kan begränsa modellen. Sju viktiga förändringar.",
        "keywords": "Nyckelord: chatgpt, gpt 5.5, gpt guide.",
        "published": "Publicerad: 22 maj 2026",
        "img_alt": "GPT 5.5 promptguide",
        "h_bg": "Bakgrund: varför skriva om",
        "bg": "Äldre prompts **överspecificerar processen**. Med GPT-5.5 blir det brus—**skriv om från scratch**.",
        "h1": "Förändring 1: från process till resultat",
        "c1": "**Gammalt:** A, B, undantag, verktyg, förklara allt.\n\n**Nytt:** lösa problemet; agera med policy/data; rapportera; en kritisk fråga.\n\n**Beskriv målet, inte varje steg.**",
        "h2": "Förändring 2: färre absoluta regler",
        "c2": "GPT-5.5 är känslig för måste/alltid; motstridiga regler misslyckas.",
        "tbl_h1": "Situation", "tbl_h2": "Stil",
        "tbl_r1": "Säkerhet, obligatoriska fält", "tbl_r1b": "alltid/aldrig",
        "tbl_r2": "Söka eller fråga", "tbl_r2b": "villkor",
        "c2_ex": "Byt «måste söka» mot «svara utan sök om kontext räcker».",
        "h3": "Förändring 3: kort roll",
        "c3": "**Roll** 1–2 meningar; **personlighet** = ton och samarbete.",
        "h4": "Förändring 4: preamble",
        "c4": "Före verktyg: 1–2 synliga meningar om mottagande och första steg.",
        "h5": "Förändring 5: stoppregler",
        "c5": "Sökbudget (1 runda) + stopp när evidens räcker.",
        "h6": "Förändring 6: sju delar",
        "c6_table": "| Del | Syfte |\n| --- | --- |\n| Roll | Funktion |\n| Personlighet | Ton |\n| Mål | Leverans |\n| Framgång | Klart |\n| Begränsningar | Gränser |\n| Output | Format |\n| Stopp | När stoppa |",
        "c6_note": "Enkel Q&A: ofta Mål + Output.",
        "h7": "Förändring 7: format",
        "c7": "`text.verbosity`, Structured Outputs; vid omskrivning: behåll först.",
        "h_mig": "Migration: reasoning lågt",
        "mig": "Utvärdera `reasoning.effort`; low räcker ofta.",
        "h_sum": "Sammanfattning",
        "sum_line": "**Säg vad du vill—inte varje steg.**",
        "sum_table": "| Dimension | Före | GPT-5.5 |\n| --- | --- | --- |\n| Process | Steg | Resultat |\n| Ton | Absolut | Röda linjer |\n| Roll | Lång | Kort |\n| Flersteg | Direkt | Preamble |\n| Stopp | Saknas | Tydlig |\n| Struktur | Fri | 7 delar |\n| Format | Default | API+prompt |",
        "outro": "Testa på riktiga uppgifter och prova GPT på LimaxAI.",
    },
    "ro": {
        "intro": "OpenAI a publicat ghidul oficial de prompturi GPT-5.5. Prompturile pas cu pas ale modelelor vechi pot limita performanța. 7 schimbări cheie.",
        "keywords": "Cuvinte cheie: chatgpt, gpt 5.5, tutorial gpt.",
        "published": "Publicat: 22 mai 2026",
        "img_alt": "Ghid prompturi GPT 5.5",
        "h_bg": "Context: de ce rescrii",
        "bg": "Prompturile vechi **supraspecifică procesul**. Cu GPT-5.5 e zgomot — **rescrie de la zero**.",
        "h1": "Schimbarea 1: de la proces la rezultat",
        "c1": "**Înainte:** A, B, excepții, tool, explică tot.\n\n**Acum:** rezolvă; acționează cu policy/date; raport; o întrebare critică.\n\n**Descrie destinația, nu fiecare pas.**",
        "h2": "Schimbarea 2: mai puține absolute",
        "c2": "GPT-5.5 e sensibil la trebuie/întotdeauna; reguli conflictuale eșuează.",
        "tbl_h1": "Situație", "tbl_h2": "Stil",
        "tbl_r1": "Siguranță, câmpuri obligatorii", "tbl_r1b": "mereu/niciodată",
        "tbl_r2": "Căutare sau întrebare", "tbl_r2b": "condițional",
        "c2_ex": "Înlocuie «trebuie să caute» cu «răspunde fără căutare dacă contextul ajunge».",
        "h3": "Schimbarea 3: rol scurt",
        "c3": "**Rol** 1–2 propoziții; **personalitate** = ton și colaborare.",
        "h4": "Schimbarea 4: preamble",
        "c4": "Înainte de tool-uri: 1–2 propoziții vizibile despre primire și primul pas.",
        "h5": "Schimbarea 5: reguli de oprire",
        "c5": "Buget căutare (1 rundă) + oprire când dovada răspunde la întrebarea centrală.",
        "h6": "Schimbarea 6: schelet în 7 părți",
        "c6_table": "| Parte | Rol |\n| --- | --- |\n| Rol | Funcție |\n| Personalitate | Ton |\n| Obiectiv | Livrabil |\n| Succes | Gata |\n| Constrângeri | Limite |\n| Output | Format |\n| Stop | Când oprești |",
        "c6_note": "Q&A simplu: adesea Obiectiv + Output.",
        "h7": "Schimbarea 7: format",
        "c7": "`text.verbosity`, Structured Outputs; la rescriere: ce păstrezi întâi.",
        "h_mig": "Migrație: reasoning jos",
        "mig": "Reevaluează `reasoning.effort`; low e des suficient.",
        "h_sum": "Rezumat",
        "sum_line": "**Spune ce vrei—nu fiecare pas.**",
        "sum_table": "| Dimensiune | Înainte | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Pași | Rezultat |\n| Ton | Absolut | Linii roșii |\n| Rol | Lung | Scurt |\n| Multi-pas | Imediat | Preamble |\n| Stop | Omis | Explicit |\n| Structură | Liber | 7 părți |\n| Format | Default | API+prompt |",
        "outro": "Testează pe sarcini reale și încearcă GPT pe LimaxAI.",
    },
    "ar": {
        "intro": "نشرت OpenAI دليل المطالبات الرسمي مع GPT-5.5. المطالبات خطوة بخطوة للنماذج القديمة قد تحد الأداء. إليك 7 تغييرات عملية.",
        "keywords": "الكلمات المفتاحية: chatgpt، gpt 5.5، دليل gpt.",
        "published": "تاريخ النشر: 22 مايو 2026",
        "img_alt": "دليل مطالبات GPT 5.5 من OpenAI",
        "h_bg": "الخلفية: لماذا إعادة كتابة المطالبات القديمة",
        "bg": "المطالبات القديمة **تحدد العملية أكثر من اللازم**. مع GPT-5.5 يصبح ذلك ضوضاء—**أعد الكتابة من الصفر**.",
        "h1": "التغيير 1: من الخطوات إلى النتيجة",
        "c1": "**قديم:** تحقق من A وB، استثناءات، أداة، شرح كل خطوة.\n\n**جديد:** حل المشكلة؛ التصرف وفق السياسة والبيانات؛ تقرير؛ سؤال حرج واحد.\n\n**صف الوجهة، وليس كل منعطف.**",
        "h2": "التغيير 2: أقل من «يجب» و«ممنوع»",
        "c2": "GPT-5.5 حساس للصياغة المطلقة؛ القواعد المتعارضة تفشل.",
        "tbl_h1": "الحالة", "tbl_h2": "الأسلوب",
        "tbl_r1": "الأمان، الحقول الإلزامية", "tbl_r1b": "دائمًا/أبدًا",
        "tbl_r2": "البحث أو السؤال", "tbl_r2b": "شروط",
        "c2_ex": "مثال: بدل «يجب البحث قبل الإجابة» — «إن كفى السياق، أجب دون بحث».",
        "h3": "التغيير 3: دور قصير",
        "c3": "**الدور** في جملتين؛ **الشخصية** = النبرة وأسلوب التعاون.",
        "h4": "التغيير 4: مقدمة قبل التنفيذ",
        "c4": "قبل الأدوات: جملتان مرئيتان تؤكدان الاستلام وأول إجراء.",
        "h5": "التغيير 5: شروط التوقف",
        "c5": "1. **ميزانية البحث:** جولة واحدة افتراضيًا. 2. **توقف الحلقة:** هل الأدلة تكفي للسؤال الجوهر؟",
        "h6": "التغيير 6: هيكل من 7 أجزاء",
        "c6_table": "| الجزء | الغرض |\n| --- | --- |\n| الدور | الوظيفة |\n| الشخصية | النبرة |\n| الهدف | المخرجات |\n| النجاح | الاكتمال |\n| القيود | الحدود |\n| المخرج | التنسيق |\n| التوقف | متى تتوقف |",
        "c6_note": "الأسئلة البسيطة: غالبًا الهدف + المخرج فقط.",
        "h7": "التغيير 7: التنسيق والإيجاز",
        "c7": "استخدم `text.verbosity` وStructured Outputs؛ في إعادة الصياغة حدد **ما يُحفظ** أولًا.",
        "h_mig": "الترحيل: reasoning منخفض",
        "mig": "أعد تقييم `reasoning.effort`؛ غالبًا يكفي low.",
        "h_sum": "الخلاصة",
        "sum_line": "**قل ماذا تريد—لا كل خطوة تنفيذ.**",
        "sum_table": "| البعد | سابقًا | GPT-5.5 |\n| --- | --- | --- |\n| العملية | خطوات | نتيجة |\n| النبرة | مطلق | خطوط حمراء فقط |\n| الدور | طويل | قصير |\n| متعدد الخطوات | فوري | مقدمة |\n| التوقف | غائب | صريح |\n| الهيكل | حر | 7 أجزاء |\n| التنسيق | افتراضي | API+prompt |",
        "outro": "اختبر على مهام حقيقية ثم جرّب GPT عبر LimaxAI بالزر أدناه.",
    },
    "id": {
        "intro": "OpenAI merilis panduan prompt resmi GPT-5.5. Prompt langkah demi langkah model lama bisa membatasi kinerja. Berikut 7 perubahan penting.",
        "keywords": "Kata kunci: chatgpt, gpt 5.5, tutorial gpt.",
        "published": "Tanggal: 22 Mei 2026",
        "img_alt": "Panduan prompt GPT 5.5",
        "h_bg": "Latar: mengapa menulis ulang prompt lama",
        "bg": "Prompt lama sering **terlalu menjabarkan proses**. Di GPT-5.5 itu menjadi noise—**tulis ulang dari awal**.",
        "h1": "Perubahan 1: dari proses ke hasil",
        "c1": "**Dulu:** cek A, B, pengecualian, pilih tool, jelaskan semua langkah.\n\n**Sekarang:** selesaikan masalah; bertindak sesuai kebijakan/data; laporan; satu pertanyaan kritis.\n\n**Gambarkan tujuan, bukan setiap langkah.**",
        "h2": "Perubahan 2: lebih sedikit absolut",
        "c2": "GPT-5.5 sensitif pada harus/selalu; aturan bentrok gagal.",
        "tbl_h1": "Situasi", "tbl_h2": "Gaya",
        "tbl_r1": "Keamanan, field wajib", "tbl_r1b": "selalu/tidak pernah",
        "tbl_r2": "Cari atau tanya", "tbl_r2b": "bersyarat",
        "c2_ex": "Ganti «harus cari dulu» dengan «jika konteks cukup, jawab tanpa cari».",
        "h3": "Perubahan 3: peran singkat",
        "c3": "**Peran** 1–2 kalimat; **kepribadian** = nada dan kolaborasi.",
        "h4": "Perubahan 4: preamble",
        "c4": "Sebelum tool: 1–2 kalimat terlihat tentang penerimaan dan langkah pertama.",
        "h5": "Perubahan 5: aturan berhenti",
        "c5": "Anggaran pencarian (1 putaran) + berhenti jika bukti sudah cukup.",
        "h6": "Perubahan 6: kerangka 7 bagian",
        "c6_table": "| Bagian | Fungsi |\n| --- | --- |\n| Peran | Fungsi |\n| Kepribadian | Nada |\n| Tujuan | Output |\n| Sukses | Selesai |\n| Batasan | Limit |\n| Output | Format |\n| Stop | Kapan berhenti |",
        "c6_note": "Q&A sederhana: sering Tujuan + Output saja.",
        "h7": "Perubahan 7: format",
        "c7": "`text.verbosity`, Structured Outputs; saat menulis ulang, sebut yang dipertahankan dulu.",
        "h_mig": "Migrasi: reasoning rendah",
        "mig": "Evaluasi ulang `reasoning.effort`; low sering cukup.",
        "h_sum": "Ringkasan",
        "sum_line": "**Katakan apa yang Anda mau—bukan setiap langkah.**",
        "sum_table": "| Dimensi | Dulu | GPT-5.5 |\n| --- | --- | --- |\n| Proses | Langkah | Hasil |\n| Nada | Absolut | Garis merah saja |\n| Peran | Panjang | Pendek |\n| Multi-langkah | Langsung | Preamble |\n| Stop | Absen | Eksplisit |\n| Struktur | Bebas | 7 bagian |\n| Format | Default | API+prompt |",
        "outro": "Uji pada tugas nyata lalu coba GPT di LimaxAI lewat tombol di bawah.",
    },
    "ms": {
        "intro": "OpenAI melancarkan panduan prompt rasmi GPT-5.5. Prompt langkah demi langkah model lama boleh mengehadkan prestasi. 7 perubahan utama.",
        "keywords": "Kata kunci: chatgpt, gpt 5.5, tutorial gpt.",
        "published": "Tarikh: 22 Mei 2026",
        "img_alt": "Panduan prompt GPT 5.5",
        "h_bg": "Latar: mengapa tulis semula prompt lama",
        "bg": "Prompt lama sering **terlalu memperincikan proses**. Pada GPT-5.5 ia menjadi hingar—**tulis semula dari awal**.",
        "h1": "Perubahan 1: proses ke hasil",
        "c1": "**Dulu:** semak A, B, pengecualian, pilih alat, jelaskan setiap langkah.\n\n**Kini:** selesaikan masalah; bertindak ikut dasar/data; laporan; satu soalan kritikal.\n\n**Gambarkan destinasi, bukan setiap langkah.**",
        "h2": "Perubahan 2: kurang absolut",
        "c2": "GPT-5.5 sensitif pada mesti/sentiasa; peraturan bercanggah gagal.",
        "tbl_h1": "Situasi", "tbl_h2": "Gaya",
        "tbl_r1": "Keselamatan, medan wajib", "tbl_r1b": "sentiasa/tidak",
        "tbl_r2": "Cari atau tanya", "tbl_r2b": "bersyarat",
        "c2_ex": "Ganti «mesti cari» dengan «jika konteks mencukupi, jawab tanpa cari».",
        "h3": "Perubahan 3: peranan pendek",
        "c3": "**Peranan** 1–2 ayat; **personaliti** = nada dan kerjasama.",
        "h4": "Perubahan 4: preamble",
        "c4": "Sebelum alat: 1–2 ayat kelihatan tentang penerimaan dan langkah pertama.",
        "h5": "Perubahan 5: peraturan henti",
        "c5": "Bajet carian (1 pusingan) + henti apabila bukti mencukupi.",
        "h6": "Perubahan 6: rangka 7 bahagian",
        "c6_table": "| Bahagian | Fungsi |\n| --- | --- |\n| Peranan | Fungsi |\n| Personaliti | Nada |\n| Matlamat | Output |\n| Kejayaan | Siap |\n| Kekangan | Had |\n| Output | Format |\n| Henti | Bila berhenti |",
        "c6_note": "Q&A mudah: sering Matlamat + Output.",
        "h7": "Perubahan 7: format",
        "c7": "`text.verbosity`, Structured Outputs; semasa menulis semula, nyatakan yang dikekalkan dahulu.",
        "h_mig": "Migrasi: reasoning rendah",
        "mig": "Nilai semula `reasoning.effort`; low sering mencukupi.",
        "h_sum": "Ringkasan",
        "sum_line": "**Katakan apa yang anda mahu—bukan setiap langkah.**",
        "sum_table": "| Dimensi | Dulu | GPT-5.5 |\n| --- | --- | --- |\n| Proses | Langkah | Hasil |\n| Nada | Mutlak | Garisan merah |\n| Peranan | Panjang | Pendek |\n| Berbilang langkah | Terus | Preamble |\n| Henti | Tiada | Jelas |\n| Struktur | Bebas | 7 bahagian |\n| Format | Lalai | API+prompt |",
        "outro": "Uji pada tugas sebenar kemudian cuba GPT di LimaxAI.",
    },
    "vi": {
        "intro": "OpenAI phát hành hướng dẫn prompt chính thức GPT-5.5. Prompt từng bước của model cũ có thể hạn chế hiệu suất. 7 thay đổi quan trọng.",
        "keywords": "Từ khóa: chatgpt, gpt 5.5, hướng dẫn gpt.",
        "published": "Ngày đăng: 22 tháng 5 năm 2026",
        "img_alt": "Hướng dẫn prompt GPT 5.5",
        "h_bg": "Bối cảnh: vì sao viết lại prompt cũ",
        "bg": "Prompt cũ thường **mô tả quy trình quá chi tiết**. Với GPT-5.5 đó là nhiễu—**viết lại từ đầu**.",
        "h1": "Thay đổi 1: từ quy trình sang kết quả",
        "c1": "**Cũ:** kiểm A, B, ngoại lệ, chọn tool, giải thích từng bước.\n\n**Mới:** giải quyết triệt để; hành động theo chính sách/dữ liệu; báo cáo; một câu hỏi then chốt.\n\n**Mô tả đích đến, không phải từng bước.**",
        "h2": "Thay đổi 2: ít tuyệt đối hơn",
        "c2": "GPT-5.5 nhạy với phải/luôn; quy tắc mâu thuẫn dễ hỏng.",
        "tbl_h1": "Tình huống", "tbl_h2": "Kiểu",
        "tbl_r1": "An toàn, trường bắt buộc", "tbl_r1b": "luôn/không bao giờ",
        "tbl_r2": "Tìm hay hỏi", "tbl_r2b": "điều kiện",
        "c2_ex": "Thay «phải tìm trước» bằng «nếu ngữ cảnh đủ, trả lời không cần tìm».",
        "h3": "Thay đổi 3: vai trò ngắn",
        "c3": "**Vai trò** 1–2 câu; **tính cách** = giọng và cách hợp tác.",
        "h4": "Thay đổi 4: xác nhận trước",
        "c4": "Trước tool: 1–2 câu hiển thị về đã nhận yêu cầu và bước đầu.",
        "h5": "Thay đổi 5: điều kiện dừng",
        "c5": "Ngân sách tìm kiếm (1 vòng) + dừng khi bằng chứng đủ trả lời câu hỏi cốt lõi.",
        "h6": "Thay đổi 6: khung 7 phần",
        "c6_table": "| Phần | Mục đích |\n| --- | --- |\n| Vai trò | Chức năng |\n| Tính cách | Giọng |\n| Mục tiêu | Đầu ra |\n| Thành công | Xong |\n| Ràng buộc | Giới hạn |\n| Đầu ra | Định dạng |\n| Dừng | Khi nào dừng |",
        "c6_note": "Hỏi đáp đơn giản: thường chỉ Mục tiêu + Đầu ra.",
        "h7": "Thay đổi 7: định dạng",
        "c7": "`text.verbosity`, Structured Outputs; khi viết lại, nêu phần giữ trước.",
        "h_mig": "Di chuyển: reasoning thấp",
        "mig": "Đánh giá lại `reasoning.effort`; low thường đủ.",
        "h_sum": "Tóm tắt",
        "sum_line": "**Nói bạn muốn gì—không phải từng bước.**",
        "sum_table": "| Chiều | Trước | GPT-5.5 |\n| --- | --- | --- |\n| Quy trình | Bước | Kết quả |\n| Giọng | Tuyệt đối | Chỉ vạch đỏ |\n| Vai trò | Dài | Ngắn |\n| Đa bước | Ngay | Xác nhận |\n| Dừng | Thiếu | Rõ |\n| Cấu trúc | Tự do | 7 phần |\n| Định dạng | Mặc định | API+prompt |",
        "outro": "Kiểm thử trên tác vụ thật rồi dùng GPT trên LimaxAI qua nút bên dưới.",
    },
    "th": {
        "intro": "OpenAI เปิดตัวคู่มือพรอมต์ GPT-5.5 อย่างเป็นทางการ พรอมต์ทีละขั้นของโมเดลเก่าอาจจำกัดประสิทธิภาพ สรุป 7 การเปลี่ยนแปลงสำคัญ",
        "keywords": "คำสำคัญ: chatgpt, gpt 5.5, บทช่วยสอน gpt",
        "published": "เผยแพร่: 22 พฤษภาคม 2026",
        "img_alt": "คู่มือพรอมต์ GPT 5.5",
        "h_bg": "พื้นหลัง: ทำไมต้องเขียนพรอมต์ใหม่",
        "bg": "พรอมต์เก่ามัก **ระบุขั้นตอนละเอียดเกินไป** กับ GPT-5.5 กลายเป็นสัญญาณรบกวน—**เขียนใหม่ตั้งแต่ต้น**",
        "h1": "การเปลี่ยนแปลง 1: จากขั้นตอนสู่ผลลัพธ์",
        "c1": "**เดิม:** ตรวจ A B ข้อยกเว้น เลือกเครื่องมือ อธิบายทุกขั้น\n\n**ใหม่:** แก้ปัญหาให้จบ ทำตามนโยบาย/ข้อมูล รายงาน ถามคำถามสำคัญหนึ่งข้อ\n\n**บอกจุดหมาย ไม่ใช่ทุกเลี้ยว**",
        "h2": "การเปลี่ยนแปลง 2: ลดคำสั่งแบบสัมบูรณ์",
        "c2": "GPT-5.5 ไวต่อ must/never กฎขัดแย้งมักล้มเหลว",
        "tbl_h1": "สถานการณ์", "tbl_h2": "สไตล์",
        "tbl_r1": "ความปลอดภัย ฟิลด์บังคับ", "tbl_r1b": "เสมอ/ไม่เคย",
        "tbl_r2": "ค้นหาหรือถาม", "tbl_r2b": "เงื่อนไข",
        "c2_ex": "เปลี่ยน «ต้องค้นหาก่อน» เป็น «ถ้าบริบทพอ ตอบโดยไม่ค้นหา»",
        "h3": "การเปลี่ยนแปลง 3: บทบาทสั้น",
        "c3": "**บทบาท** 1–2 ประโยค **บุคลิก** = น้ำเสียงและการทำงานร่วม",
        "h4": "การเปลี่ยนแปลง 4: ยืนยันก่อนทำ",
        "c4": "ก่อนเรียกเครื่องมือ: 1–2 ประโยคที่ผู้ใช้เห็น ยืนยันรับคำขอและขั้นแรก",
        "h5": "การเปลี่ยนแปลง 5: เงื่อนไขหยุด",
        "c5": "งบค้นหา (1 รอบ) + หยุดเมื่อหลักฐานตอบคำถามหลักได้",
        "h6": "การเปลี่ยนแปลง 6: โครง 7 ส่วน",
        "c6_table": "| ส่วน | วัตถุประสงค์ |\n| --- | --- |\n| บทบาท | หน้าที่ |\n| บุคลิก | น้ำเสียง |\n| เป้าหมาย | ผลลัพธ์ |\n| สำเร็จ | เสร็จ |\n| ข้อจำกัด | ขอบเขต |\n| เอาต์พุต | รูปแบบ |\n| หยุด | เมื่อไหร่หยุด |",
        "c6_note": "คำถามง่าย: มักแค่เป้าหมาย+เอาต์พุต",
        "h7": "การเปลี่ยนแปลง 7: รูปแบบ",
        "c7": "`text.verbosity` Structured Outputs เขียนใหม่ระบุสิ่งที่คงไว้ก่อน",
        "h_mig": "ย้ายระบบ: reasoning ต่ำ",
        "mig": "ปรับ `reasoning.effort` ใหม่ หลายงาน low พอ",
        "h_sum": "สรุป",
        "sum_line": "**บอกว่าต้องการอะไร—ไม่ใช่ทุกขั้นตอน**",
        "sum_table": "| มิติ | ก่อน | GPT-5.5 |\n| --- | --- | --- |\n| กระบวนการ | ขั้น | ผลลัพธ์ |\n| น้ำเสียง | สัมบูรณ์ | เฉพาะเส้นแดง |\n| บทบาท | ยาว | สั้น |\n| หลายขั้น | ทันที | ยืนยันก่อน |\n| หยุด | ไม่มี | ชัด |\n| โครงสร้าง | อิสระ | 7 ส่วน |\n| รูปแบบ | ค่าเริ่ม | API+prompt |",
        "outro": "ทดสอบงานจริงแล้วลอง GPT บน LimaxAI ผ่านปุ่มด้านล่าง",
    },
    "tr": {
        "intro": "OpenAI, GPT-5.5 ile resmi istem kılavuzunu yayınladı. Eski modellerin adım adım istemleri performansı sınırlayabilir. 7 kritik değişiklik.",
        "keywords": "Anahtar kelimeler: chatgpt, gpt 5.5, gpt eğitimi.",
        "published": "Yayın: 22 Mayıs 2026",
        "img_alt": "GPT 5.5 istem kılavuzu",
        "h_bg": "Arka plan: neden yeniden yazmalı",
        "bg": "Eski istemler **süreci fazla tarif eder**. GPT-5.5'te bu gürültü—**sıfırdan yazın**.",
        "h1": "Değişiklik 1: süreçten sonuca",
        "c1": "**Eski:** A B istisna araç her adımı açıkla.\n\n**Yeni:** sorunu çöz; politika/veriyle hareket et; raporla; tek kritik soru.\n\n**Varış noktasını yaz, her virajı değil.**",
        "h2": "Değişiklik 2: daha az mutlak",
        "c2": "GPT-5.5 must/asla ifadelerine duyarlı; çelişen kurallar bozar.",
        "tbl_h1": "Durum", "tbl_h2": "Stil",
        "tbl_r1": "Güvenlik, zorunlu alanlar", "tbl_r1b": "her zaman/asla",
        "tbl_r2": "Ara veya sor", "tbl_r2b": "koşullu",
        "c2_ex": "«Önce ara» yerine «bağlam yeterliyse aramadan yanıtla».",
        "h3": "Değişiklik 3: kısa rol",
        "c3": "**Rol** 1–2 cümle; **kişilik** = ton ve iş birliği.",
        "h4": "Değişiklik 4: ön onay",
        "c4": "Araçlardan önce: alındı ve ilk adım hakkında 1–2 görünür cümle.",
        "h5": "Değişiklik 5: durma kuralları",
        "c5": "Arama bütçesi (1 tur) + kanıt yeterliyse dur.",
        "h6": "Değişiklik 6: 7 parçalı iskelet",
        "c6_table": "| Parça | Amaç |\n| --- | --- |\n| Rol | İşlev |\n| Kişilik | Ton |\n| Hedef | Çıktı |\n| Başarı | Bitti |\n| Kısıt | Sınır |\n| Çıktı | Biçim |\n| Dur | Ne zaman |",
        "c6_note": "Basit S&C: çoğu zaman Hedef+Çıktı yeter.",
        "h7": "Değişiklik 7: biçim",
        "c7": "`text.verbosity`, Structured Outputs; yeniden yazımda önce korunanları belirt.",
        "h_mig": "Geçiş: düşük reasoning",
        "mig": "`reasoning.effort` yeniden değerlendir; low çoğu iş için yeter.",
        "h_sum": "Özet",
        "sum_line": "**Ne istediğini söyle—her adımı değil.**",
        "sum_table": "| Boyut | Önce | GPT-5.5 |\n| --- | --- | --- |\n| Süreç | Adım | Sonuç |\n| Ton | Mutlak | Kırmızı çizgi |\n| Rol | Uzun | Kısa |\n| Çok adım | Hemen | Ön onay |\n| Dur | Yok | Açık |\n| Yapı | Serbest | 7 parça |\n| Biçim | Varsayılan | API+prompt |",
        "outro": "Gerçek görevlerde test edin, ardından LimaxAI'da GPT'yi deneyin.",
    },
    "hi": {
        "intro": "OpenAI ने GPT-5.5 के साथ आधिकारिक प्रॉम्प्ट गाइड जारी की। पुराने मॉडल के स्टेप-बाय-स्टेप प्रॉम्प्ट प्रदर्शन सीमित कर सकते हैं। 7 महत्वपूर्ण बदलाव।",
        "keywords": "कीवर्ड: chatgpt, gpt 5.5, gpt ट्यूटोरियल।",
        "published": "प्रकाशन: 22 मई 2026",
        "img_alt": "GPT 5.5 प्रॉम्प्ट गाइड",
        "h_bg": "पृष्ठभूमि: पुराने प्रॉम्प्ट क्यों बदलें",
        "bg": "पुराने प्रॉम्प्ट अक्सर **प्रक्रिया को ज़्यादा बताते हैं**। GPT-5.5 पर यह शोर है—**शुरू से लिखें**।",
        "h1": "बदलाव 1: प्रक्रिया से परिणाम",
        "c1": "**पुराना:** A, B, अपवाद, टूल, हर कदम समझाएँ।\n\n**नया:** समस्या पूरी हल करें; नीति/डेटा से कार्य; रिपोर्ट; एक महत्वपूर्ण सवाल।\n\n**मंज़िल बताएँ, हर मोड़ नहीं।**",
        "h2": "बदलाव 2: कम निरपेक्ष निर्देश",
        "c2": "GPT-5.5 must/never के प्रति संवेदनशील; विरोधाभासी नियम विफल।",
        "tbl_h1": "स्थिति", "tbl_h2": "शैली",
        "tbl_r1": "सुरक्षा, अनिवार्य फ़ील्ड", "tbl_r1b": "हमेशा/कभी नहीं",
        "tbl_r2": "खोजें या पूछें", "tbl_r2b": "शर्तें",
        "c2_ex": "«पहले खोज अनिवार्य» की जगह «संदर्भ पर्याप्त हो तो बिना खोज जवाब दें»।",
        "h3": "बदलाव 3: छोटी भूमिका",
        "c3": "**भूमिका** 1–2 वाक्य; **व्यक्तित्व** = स्वर और सहयोग।",
        "h4": "बदलाव 4: पहले पुष्टि",
        "c4": "टूल से पहले 1–2 दृश्य वाक्य: अनुरोध मिला, पहला कदम।",
        "h5": "बदलाव 5: रुकने के नियम",
        "c5": "खोज बजट (1 राउंड) + साक्ष्य पर्याप्त हो तो रुकें।",
        "h6": "बदलाव 6: 7-भाग ढाँचा",
        "c6_table": "| भाग | उद्देश्य |\n| --- | --- |\n| भूमिका | कार्य |\n| व्यक्तित्व | स्वर |\n| लक्ष्य | आउटपुट |\n| सफलता | पूर्ण |\n| बाधाएँ | सीमा |\n| आउटपुट | प्रारूप |\n| स्टॉप | कब रुकें |",
        "c6_note": "साधारण Q&A: अक्सर लक्ष्य+आउटपुट।",
        "h7": "बदलाव 7: प्रारूप",
        "c7": "`text.verbosity`, Structured Outputs; पुनर्लेखन में पहले क्या रखना है।",
        "h_mig": "माइग्रेशन: निम्न reasoning",
        "mig": "`reasoning.effort` पुनः जाँचें; low अक्सर पर्याप्त।",
        "h_sum": "सारांश",
        "sum_line": "**आप क्या चाहते हैं बताएँ—हर कदम नहीं।**",
        "sum_table": "| आयाम | पहले | GPT-5.5 |\n| --- | --- | --- |\n| प्रक्रिया | कदम | परिणाम |\n| स्वर | निरपेक्ष | केवल रेड लाइन |\n| भूमिका | लंबी | छोटी |\n| बहु-चरण | तुरंत | पुष्टि |\n| स्टॉप | अनुपस्थित | स्पष्ट |\n| संरचना | मुक्त | 7 भाग |\n| प्रारूप | डिफ़ॉल्ट | API+prompt |",
        "outro": "वास्तविक कार्यों पर परीक्षण करें, फिर LimaxAI पर GPT आज़माएँ।",
    },
    "fa": {
        "intro": "OpenAI راهنمای رسمی پرامپت GPT-5.5 را منتشر کرد. پرامپت‌های گام‌به‌گام مدل‌های قدیمی ممکن است عملکرد را محدود کند. ۷ تغییر کلیدی.",
        "keywords": "کلیدواژه‌ها: chatgpt، gpt 5.5، آموزش gpt.",
        "published": "تاریخ انتشار: ۲۲ مه ۲۰۲۶",
        "img_alt": "راهنمای پرامپت GPT 5.5",
        "h_bg": "پس‌زمینه: چرا پرامپت قدیمی را بازنویسی کنیم",
        "bg": "پرامپت‌های قدیمی اغلب **فرایند را بیش‌ازحد مشخص می‌کنند**. در GPT-5.5 این نویز است—**از صفر بنویسید**.",
        "h1": "تغییر ۱: از فرایند به نتیجه",
        "c1": "**قدیم:** A، B، استثنا، ابزار، توضیح هر گام.\n\n**جدید:** مسئله را حل کنید؛ با سیاست/داده عمل کنید؛ گزارش؛ یک سؤال حیاتی.\n\n**مقصد را بگویید، نه هر پیچ.**",
        "h2": "تغییر ۲: کمتر «باید/ممنوع»",
        "c2": "GPT-5.5 به دستورهای مطلق حساس است؛ قوانین متناقض شکست می‌خورند.",
        "tbl_h1": "موقعیت", "tbl_h2": "سبک",
        "tbl_r1": "امنیت، فیلدهای اجباری", "tbl_r1b": "همیشه/هرگز",
        "tbl_r2": "جستجو یا پرسش", "tbl_r2b": "شرطی",
        "c2_ex": "به‌جای «حتماً جستجو» — «اگر زمینه کافی است، بدون جستجو پاسخ بده».",
        "h3": "تغییر ۳: نقش کوتاه",
        "c3": "**نقش** ۱–۲ جمله؛ **شخصیت** = لحن و همکاری.",
        "h4": "تغییر ۴: تأیید قبل از اجرا",
        "c4": "قبل از ابزار: ۱–۲ جملهٔ قابل‌مشاهده درباره دریافت و گام اول.",
        "h5": "تغییر ۵: شرط توقف",
        "c5": "بودجه جستجو (۱ دور) + توقف وقتی شواهد کافی است.",
        "h6": "تغییر ۶: اسکلت ۷ بخشی",
        "c6_table": "| بخش | هدف |\n| --- | --- |\n| نقش | کارکرد |\n| شخصیت | لحن |\n| هدف | خروجی |\n| موفقیت | تمام |\n| محدودیت | مرز |\n| خروجی | قالب |\n| توقف | چه زمانی |",
        "c6_note": "سؤال ساده: اغلب هدف+خروجی کافی است.",
        "h7": "تغییر ۷: قالب",
        "c7": "`text.verbosity` و Structured Outputs؛ در بازنویسی اول «چه چیزی حفظ شود».",
        "h_mig": "مهاجرت: reasoning پایین",
        "mig": "`reasoning.effort` را بازبینی کنید؛ low اغلب کافی است.",
        "h_sum": "جمع‌بندی",
        "sum_line": "**بگویید چه می‌خواهید—نه هر گام اجرا.**",
        "sum_table": "| بعد | قبل | GPT-5.5 |\n| --- | --- | --- |\n| فرایند | گام | نتیجه |\n| لحن | مطلق | فقط خط قرمز |\n| نقش | بلند | کوتاه |\n| چندگام | فوری | تأیید |\n| توقف | حذف | صریح |\n| ساختار | آزاد | ۷ بخش |\n| قالب | پیش‌فرض | API+prompt |",
        "outro": "روی کار واقعی آزمایش کنید و از دکمه زیر GPT را در LimaxAI امتحان کنید.",
    },
}
