# Full section translations aligned with zh-cn / en article depth.
# Used by generate_gpt55_prompt_blog.py for all locales except zh-cn (and en uses LOCALES body).

def _en():
    return {
        "intro": "When GPT-5.5 launched, OpenAI published an official prompting guide. If you still write step-by-step \"micromanagement\" prompts from older models, you may be narrowing what the model can do. This article turns the seven most important shifts into practical guidance.",
        "keywords": "Keywords: chatgpt, gpt 5.5, gpt tutorial.",
        "published": "Published: May 22, 2026",
        "img_alt": "OpenAI GPT 5.5 prompt guide seven key changes",
        "h_bg": "Background: why legacy prompts need a rewrite",
        "bg": "The docs are explicit: older prompts often **over-specify the process** because earlier models needed more guardrails to stay on track. With GPT-5.5, that detail can become noise, shrink the search space, and produce mechanical answers.\n\nDjango co-creator Simon Willison noted that OpenAI recommends **rewriting from scratch** rather than assuming tuned legacy prompts still work. If you are moving to GPT-5.5 (or trying similar capabilities on LimaxAI), treat prompts as a new product design—not a model-name swap.",
        "h1": "Change 1: from hand-holding to outcome-first",
        "c1": "**Old style (process-first):**\n\n> Check A, then B, compare fields one by one, reason through every exception, decide which tool to call, then explain the whole process to the user.\n\n**New style (outcome-first):**\n\n> Fully resolve the user's issue. Use policy and account data to decide what to do first, then report what was done and what remains. Ask only the single most critical question if information is missing.\n\nIn one line: **describe the destination, not every turn on the map.** GPT-5.5 plans its own path; a rigid script can block better routes.",
        "h2": "Change 2: fewer absolutes—reserve them for real red lines",
        "c2": "Guardrails like \"always JSON,\" \"never exceed 500 words,\" or \"must search before answering\" were common. GPT-5.5 is **highly sensitive to absolutes**—when two conflicting \"must\" rules appear, the model may try to satisfy both and fail both.",
        "tbl_h1": "Situation", "tbl_h2": "Recommended style",
        "tbl_r1": "Safety rules, required fields, hard bans", "tbl_r1b": "Use always/never",
        "tbl_r2": "Whether to search or ask the user", "tbl_r2b": "Use conditional rules",
        "c2_ex": "Example: replace \"must search before answering\" with \"After receiving the question, check whether existing context is enough to answer; if yes, reply directly without searching.\"",
        "h3": "Change 3: roles return—but stay short",
        "c3": "Long résumé personas (\"you are a top analyst with 20 years of experience…\") are low ROI on GPT-5.5. The official **seven-part skeleton** still starts with **Role** and **Personality**, but the form changed:\n\n- **Role:** 1–2 sentences on function and context.\n- **Personality:** tone, warmth, and collaboration style—not a CV.\n\nTwo personality templates from the guide:\n\n- **Steady:** a reliable collaborator—calm, direct; assume the user is capable; advance work without unnecessary check-ins.\n- **Expressive:** conversational, curious, appropriately witty; ask when ambiguous, decide when context is enough.\n\n**Personality** is how it sounds; **collaboration style** is how it acts (guess vs. clarify on vague asks)—write them separately.",
        "h4": "Change 4: acknowledge multi-step work before executing",
        "c4": "On complex tasks the model may reason silently for a while with no visible output—users think it froze. Add a **preamble** rule in the prompt:\n\n> On multi-step tasks, before calling any tool, send a short user-visible update confirming receipt and what the first step will be—keep it to one or two sentences.\n\nProducts like Codex already use this pattern (e.g. \"Analyzing your codebase, starting with test files\") for APIs and long ChatGPT tasks alike.",
        "h5": "Change 5: define stop conditions",
        "c5": "If you only say \"search for relevant information, then answer\" without defining when to stop, the model may loop retrieval—tokens rise while answers get scattered.\n\nTwo common strategies:\n\n1. **Retrieval budget:** one search round by default for ordinary Q&A; answer if page-one evidence is enough. Open a second round only if page one lacks the answer, key data is missing, or the user wants exhaustive coverage.\n2. **Loop stop:** after each tool round, ask whether existing evidence can answer the user's core question; if yes, stop.",
        "h6": "Change 6: the official seven-part prompt skeleton",
        "c6_table": "| Section | Purpose |\n| --- | --- |\n| Role | 1–2 sentences: function and context |\n| Personality | Tone, style, collaboration |\n| Goal | User-visible deliverable |\n| Success | Definition of done |\n| Constraints | Safety, business, evidence, side effects |\n| Output | Format, length, voice |\n| Stop rules | When to retry, escalate, refuse, ask, or stop |",
        "c6_note": "Note: **you do not need all seven every time**. Simple Q&A may need only Goal + Output; multi-tool agents need the full set. OpenAI's developer console also offers an **Optimize** action to reshape existing prompts against this structure.",
        "h7": "Change 7: format control and concise defaults",
        "c7": "GPT-5.5 defaults to concise, direct answers. On the API side use `text.verbosity` (`medium` by default; try `low` for shorter replies); for complex formats prefer **Structured Outputs** instead of large JSON examples in the prompt.\n\nYou can also steer layout in prose, for example:\n\n> Default to natural paragraphs; use headings, bold, and lists only when they aid comprehension.\n\nFor rewrite tasks, state **what to preserve** before **how to edit**:\n\n> Keep the original structure, length, and voice; improve clarity only—do not add new claims or paragraphs unless the user asks.\n\nWithout preserve rules, the model often expands and restructures by default.",
        "h_mig": "Migration tip: tune reasoning effort from the low end",
        "mig": "Beyond prompts, re-evaluate **`reasoning.effort`**. GPT-5.5 defaults to `medium`; many tasks work at `low`. Higher is not automatically better—conflicting instructions or weak stop rules plus high effort can mean over-searching and detours. Run A/B tests on a fixed eval set; start with `low` / `medium`, then move to `high` / `xhigh` only when quality gains justify latency and cost.",
        "h_sum": "Summary: one line to remember",
        "sum_line": "**Say what you want—not how to do every step.**",
        "sum_table": "| Dimension | GPT-5.4 and earlier | GPT-5.5 |\n| --- | --- | --- |\n| Process | Detailed steps | Outcomes only |\n| Tone | Many absolutes | Absolutes for red lines; conditionals elsewhere |\n| Role | Long background | 1–2 sentences + personality |\n| Multi-step | Execute immediately | Preamble first |\n| Stopping | Often omitted | Should be explicit |\n| Structure | Free-form | Seven-part skeleton (trim as needed) |\n| Format | Defaults | API params + prompt guidance |",
        "outro": "After rewriting, run side-by-side tests on real tasks. To try GPT in chat, use the button below on LimaxAI with your preferred model.",
    }


def _zh_tw():
    e = _en()
    return {
        **e,
        "intro": "OpenAI 在 GPT-5.5 上線時同步發布了官方提示詞指南。若你仍用舊模型的「分步指揮」寫法，很可能已把模型的發揮空間壓窄。本文基於官方文件與社群實踐，整理 7 個最值得關注的變化，方便落地改寫 Prompt。",
        "keywords": "關鍵字：chatgpt、gpt 5.5、gpt教程。",
        "published": "發布日期：2026年5月22日",
        "img_alt": "OpenAI GPT 5.5 提示詞指南 7 個關鍵變化",
        "h_bg": "背景：為什麼舊 Prompt 要重寫",
        "bg": "官方文件寫得很直白：舊提示詞常**過度規定流程**，是因早期模型需要更多引導才能「不跑偏」。GPT-5.5 推理更強後，這類細節可能變成噪音，縮小搜尋空間，輸出也更機械。\n\nDjango 聯合創始人 Simon Willison 也提到：OpenAI 建議**從頭重寫**，而不是假設以前調好的 Prompt 還能直接沿用。若你準備遷移到 GPT-5.5（或在 LimaxAI 上體驗同類能力），建議把 Prompt 當成新產品重新設計，而不是簡單替換模型名。",
        "h1": "變化一：從「手把手」到「只描述結果」",
        "c1": "**舊寫法**（流程導向）：\n\n> 先檢查 A，再檢查 B，逐個欄位比對，想清楚所有異常，再決定呼叫哪個工具，調完工具把全過程解釋給用戶。\n\n**新寫法**（結果導向）：\n\n> 把用戶的問題徹底解決。根據現有政策與帳戶資料判斷，能做的事先做完再回覆，最後說明做了什麼、還有什麼沒解決。缺資訊就追問，只問最關鍵的那一個。\n\n核心就一句：**描述目的地，而不是規定每一步怎麼走。** GPT-5.5 會自己規劃路徑；你把路線寫死，反而可能擋住更優解。",
        "h2": "變化二：少用「必須」「禁止」，紅線才用絕對語氣",
        "c2": "過去常用「永遠 JSON」「絕對不超過 500 字」「必須先搜尋再回答」來約束模型。GPT-5.5 對絕對指令**非常敏感**——兩條互相矛盾的「必須」出現時，模型可能同時硬扛兩條，兩邊都做不好。",
        "tbl_h1": "情境", "tbl_h2": "建議寫法",
        "tbl_r1": "安全規則、必填欄位、絕對禁止的操作", "tbl_r1b": "用「永遠」「絕不」",
        "tbl_r2": "要不要搜尋、要不要追問用戶", "tbl_r2b": "用條件句",
        "c2_ex": "範例：把「回答前必須先搜尋」改成「收到問題後先判斷現有上下文能否直接回答；能就直接回覆，不用再搜。」",
        "h3": "變化三：角色定義回歸，但要短",
        "c3": "「你是一個擁有 20 年經驗的頂級分析師……」這種大段人設，在 GPT-5.5 上性價比不高。官方推薦的 **7 段式結構**裡，前兩段仍是「角色」和「人設」，但寫法變了：\n\n- **角色（Role）**：1～2 句話說清功能與上下文即可。\n- **人設（Personality）**：管語氣、溫度、協作風格，而不是堆履歷。\n\n官方給了兩種人設參考：\n\n- **穩重型**：靠譜協作者，沉穩直接，假設用戶有能力，能推進就別反覆確認。\n- **表達型**：對話感強，聰明好奇，問題模糊時多問，上下文夠了就果斷給建議。\n\n「人設」管怎麼說，「協作風格」管怎麼做（模糊需求是猜還是追問），建議分開寫。",
        "h4": "變化四：多步任務先「確認收到」，再動手",
        "c4": "複雜任務裡，模型可能先內部推理很久，介面上有一段時間沒有輸出，用戶容易以為卡住了。官方建議在提示詞裡加一條 **Preamble（開場確認）** 規則：\n\n> 處理多步任務時，在呼叫任何工具之前，先回覆一句簡短、用戶可見的更新，說明已收到請求以及第一步要做什麼，控制在一兩句話。\n\nCodex 等產品已在用類似模式（例如「正在分析你的程式庫，先從測試檔案開始」），對 API 和 ChatGPT 長任務都適用。",
        "h5": "變化五：必須寫「停止條件」",
        "c5": "只寫「搜尋相關資訊然後回答」，卻不定義何時停，模型可能反覆檢索，token 漲、答案卻更散。\n\n兩種常用策略：\n\n1. **檢索預算**：一般問答先搜一輪；首頁結果已能支撐答案就直接回答。只有首頁沒答案、缺關鍵資料或用戶要求全面覆蓋時，再開第二輪。\n2. **任務循環停止**：每完成一輪工具呼叫後自問——現有證據能否回答用戶核心問題？能就停。",
        "h6": "變化六：官方 7 段式提示詞骨架",
        "c6_table": "| 段落 | 說明 |\n| --- | --- |\n| 角色（Role） | 1～2 句，定義功能與上下文 |\n| 人設（Personality） | 語氣、風格、協作方式 |\n| 目標（Goal） | 用戶可見的最終產出 |\n| 成功標準（Success） | 什麼條件算完成 |\n| 約束（Constraints） | 安全、商業、證據、副作用邊界 |\n| 輸出（Output） | 格式、長度、語氣 |\n| 停止規則（Stop rules） | 何時重試、回退、拒絕、追問或停止 |",
        "c6_note": "注意：**不是每次都要寫滿 7 段**。簡單問答可能只要「目標 + 輸出」；多工具 Agent 才需要全套。OpenAI 開發者後台也提供了 **Optimize** 工具，可按該結構自動改寫現有 Prompt。",
        "h7": "變化七：格式控制與簡潔表達",
        "c7": "GPT-5.5 預設更簡潔直接。API 側可用 `text.verbosity`（預設 `medium`，需要短答可試 `low`）；複雜格式盡量用 **Structured Outputs**，少在 Prompt 裡堆 JSON 樣例。\n\n提示詞裡也可以直接約束版式，例如：\n\n> 預設用自然段落回覆；標題、加粗、列表只在幫助理解時使用。\n\n改寫類任務建議先說「保留什麼」，再說「怎麼改」：\n\n> 保留原文結構、長度和文風，在此基礎上提升清晰度；不要新增觀點或段落，除非用戶要求。\n\n不寫「保留項」時，模型容易預設擴寫、加戲。",
        "h_mig": "遷移時別忘了：推理強度從低檔試起",
        "mig": "除了 Prompt，**`reasoning.effort`** 也要重新評測。GPT-5.5 預設 `medium`，很多任務在 `low` 就夠；不是越強越好——指令衝突、停止條件模糊時，開太高可能過度搜尋、繞遠路。建議用固定測試集做 A/B，先 `low` / `medium`，有明確收益再升 `high` / `xhigh`。",
        "h_sum": "總結：一句話記住新寫法",
        "sum_line": "**說清楚你要什麼，別教它每一步怎麼做。**",
        "sum_table": "| 維度 | GPT-5.4 及之前 | GPT-5.5 |\n| --- | --- | --- |\n| 流程指定 | 詳細分步 | 只描述結果 |\n| 指令語氣 | 大量絕對指令 | 紅線用絕對，其餘用條件 |\n| 角色定義 | 大段背景 | 1～2 句功能 + 人設 |\n| 多步任務 | 直接執行 | 先確認再執行 |\n| 停止條件 | 常省略 | 建議明確寫出 |\n| 結構 | 自由發揮 | 7 段式骨架（按需裁剪） |\n| 格式控制 | 依賴預設 | API 參數 + Prompt 引導 |",
        "outro": "改完 Prompt 後，建議在真實任務上跑一輪對比測試。若你想直接體驗 GPT 對話能力，可透過下方按鈕進入 LimaxAI 聊天頁，選擇對應模型開始試用。",
    }


# Locale-specific overrides on top of English structure (same keys, translated content)
_LOCALE_OVERRIDES: dict[str, dict[str, str]] = {}

def _add(lang: str, **kwargs):
    _LOCALE_OVERRIDES[lang] = kwargs


_add("ja",
    intro="GPT-5.5 の公開と同時に、OpenAI は公式プロンプトガイドを公開しました。旧モデル向けの「手取り足取り」型プロンプトは、性能を狭めている可能性があります。公式ドキュメントとコミュニティの実践を踏まえ、重要な 7 つの変化を実務向けに整理します。",
    keywords="キーワード：chatgpt、gpt 5.5、gptチュートリアル。",
    published="公開日：2026年5月22日",
    img_alt="OpenAI GPT 5.5 プロンプトガイド 7つの変化",
    h_bg="背景：旧プロンプトを書き直す理由",
    bg="公式ドキュメントは明確です。旧プロンプトは**手順を過剰に指定**しがちで、これは以前のモデルが軌道から外れないよう支援するためでした。GPT-5.5 ではその詳細がノイズになり、探索空間を狭め、機械的な回答につながります。\n\nDjango 共同創設者の Simon Willison も、OpenAI が**一から書き直す**ことを推奨しており、調整済みの旧プロンプトがそのまま使えると仮定しないよう指摘しています。GPT-5.5 に移行する（または LimaxAI で同様の能力を試す）場合は、モデル名の差し替えではなく、プロンプトを新製品として設計し直してください。",
    h1="変化1：手順指定から結果記述へ",
    c1="**旧スタイル（プロセス重視）：**\n\n> A を確認し、次に B を確認し、フィールドを一つずつ比較し、すべての例外を考慮し、どのツールを呼ぶか決め、完了後に全手順をユーザーに説明する。\n\n**新スタイル（結果重視）：**\n\n> ユーザーの問題を完全に解決する。ポリシーとアカウントデータに基づき判断し、できることを先に実行してから報告し、実施内容と未解決事項を説明する。情報が足りない場合は、最も重要な質問を 1 つだけ行う。\n\n要するに：**目的地を書き、経路の全ステップは書かない。** GPT-5.5 は自ら経路を計画する。ルートを固定すると、より良い解が阻害されることがあります。",
    h2="変化2：「必ず/禁止」は本当の赤線だけ",
    c2="「常に JSON」「500 字を絶対に超えない」「回答前に必ず検索」などの制約が一般的でした。GPT-5.5 は**絶対表現に非常に敏感**で、矛盾する 2 つの「必ず」があると、両方を満たそうとして失敗しやすくなります。",
    tbl_h1="場面", tbl_h2="推奨",
    tbl_r1="安全ルール、必須フィールド、厳格な禁止", tbl_r1b="always/never（常に/決して）",
    tbl_r2="検索するか、ユーザーに聞くか", tbl_r2b="条件文",
    c2_ex="例：「回答前に必ず検索」を「質問受信後、既存コンテキストで答えられるか判断；答えられるなら検索せずに返答」に変更。",
    h3="変化3：ロールは復活、ただし短く",
    c3="「20 年の経験を持つトップアナリスト…」のような長いペルソナは GPT-5.5 では費用対効果が低い。公式の**7 部構成**では依然として **Role** と **Personality** から始まりますが、形式が変わりました：\n\n- **Role：** 機能とコンテキストを 1～2 文で。\n- **Personality：** 口調、温度感、協働スタイル——履歴書ではない。\n\nガイドの 2 つのペルソナ例：\n\n- **安定型：** 信頼できる協作者——落ち着いて直接的；ユーザーの意図は善意と仮定；不要な確認を避けて前進。\n- **表現型：** 会話的で好奇心旺盛、適宜ウィット；曖昧なら質問、コンテキストが足りれば果断に提案。\n\n**Personality** は「どう話すか」、**協働スタイル** は「どう動くか」（曖昧時に推測か確認か）——分けて書く。",
    h4="変化4：多段タスクは先に受領確認",
    c4="複雑なタスクでは、しばらく内部推論のみで画面に出力がなく、ユーザーはフリーズしたと思いがちです。プロンプトに **Preamble（前置き）** ルールを追加：\n\n> 多段タスクでは、ツール呼び出し前に、受領と最初のステップを示す短いユーザー向け更新を 1～2 文で送る。\n\nCodex などは既に「コードベースを分析中、まずテストファイルから」といったパターンを使っており、API と長い ChatGPT タスクに有効です。",
    h5="変化5：停止条件を必ず定義",
    c5="「関連情報を検索してから回答」とだけ書き、停止条件がないと、検索がループしトークンが増える一方で回答が散漫になります。\n\n2 つの一般的な戦略：\n\n1. **検索予算：** 通常の Q&A はデフォルト 1 ラウンド；1 ページ目の証拠で足りれば回答。2 ラウンド目は、答えがない・重要データ不足・ユーザーが網羅を求める場合のみ。\n2. **ループ停止：** 各ツールラウンド後、既存証拠で核心質問に答えられるか自問；答えられるなら停止。",
    h6="変化6：公式 7 部構成の骨格",
    c6_table="| 部 | 目的 |\n| --- | --- |\n| Role | 機能とコンテキスト（1～2 文） |\n| Personality | 口調・スタイル・協働 |\n| Goal | ユーザーに見える成果物 |\n| Success | 完了の定義 |\n| Constraints | 安全・ビジネス・証拠・副作用の境界 |\n| Output | 形式・長さ・トーン |\n| Stop | 再試行・エスカレーション・拒否・質問・停止のタイミング |",
    c6_note="注意：**毎回 7 部すべては不要**。単純な Q&A は Goal + Output で十分；マルチツール Agent は全套が必要。OpenAI 開発者コンソールの **Optimize** で既存プロンプトをこの構造に合わせて整形できます。",
    h7="変化7：形式制御と簡潔さ",
    c7="GPT-5.5 はデフォルトで簡潔・直接的。API では `text.verbosity`（デフォルト `medium`、短答は `low` を試す）；複雑な形式はプロンプト内の巨大 JSON ではなく **Structured Outputs** を優先。\n\n文体はプロンプトで指定可能，例：\n\n> デフォルトは自然な段落；見出し・太字・リストは理解に役立つときだけ。\n\nリライトでは**何を残すか**を先に、**どう直すか**を後に：\n\n> 元の構造・長さ・文体を保ち、明瞭さのみ向上；ユーザーが求めない限り新論点や段落を追加しない。\n\n残す項目を書かないと、モデルは拡張・再構成しがちです。",
    h_mig="移行のヒント：reasoning は低めから",
    mig="プロンプト以外に **`reasoning.effort`** も再評価。GPT-5.5 のデフォルトは `medium`；多くのタスクは `low` で十分。高くても必ずしも良くない——指示の矛盾や停止条件の曖昧さと高 effort は過剰検索や遠回りの原因。固定評価セットで A/B；`low`/`medium` から始め、品質向上が latency/cost を正当化するときだけ `high`/`xhigh` へ。",
    h_sum="まとめ：覚えておく一言",
    sum_line="**何が欲しいかを書き、全手順は書かない。**",
    sum_table="| 観点 | 以前 | GPT-5.5 |\n| --- | --- | --- |\n| 手順 | 詳細なステップ | 結果のみ |\n| トーン | 絶対表現が多い | 赤線のみ絶対、他は条件 |\n| ロール | 長い経歴 | 1～2 文 + ペルソナ |\n| 多段 | 即実行 | 先に確認 |\n| 停止 | しばしば省略 | 明示推奨 |\n| 構造 | 自由 | 7 部構成（必要に応じて削減） |\n| 形式 | デフォルト | API + プロンプト |",
    outro="書き直したら実タスクで比較テストを。GPT を試すには下のボタンから LimaxAI チャットへ。",
)

_add("ko",
    intro='GPT-5.5 출시와 함께 OpenAI가 공식 프롬프트 가이드를 공개했습니다. 구형 모델의 «단계별 지시» 프롬프트는 모델의 발휘를 좁힐 수 있습니다. 가장 중요한 7가지 변화를 실무 가이드로 정리합니다.',
    keywords='키워드: chatgpt, gpt 5.5, gpt 튜토리얼.',
    published='게시일: 2026년 5월 22일',
    img_alt='OpenAI GPT 5.5 프롬프트 가이드 7가지 핵심 변화',
    h_bg='배경: 왜 기존 프롬프트를 다시 써야 하나',
    bg='공식 문서는 분명합니다. 이전 프롬프트는 **절차를 과도하게 지정**하는 경우가 많았고, 초기 모델이 궤도를 벗어나지 않도록 돕기 위함이었습니다. GPT-5.5에서는 그 세부가 노이즈가 되어 탐색 공간을 줄이고 기계적인 답을 만듭니다.\n\nDjango 공동 창시자 Simon Willison은 OpenAI가 튜닝된 레거시 프롬프트가 그대로 통할 것이라 가정하지 말고 **처음부터 다시 쓰라**고 권한다고 지적했습니다. GPT-5.5로 이전하거나 LimaxAI에서 비슷한 기능을 쓸 때 프롬프트를 모델 이름 교체가 아닌 새 제품 설계로 보세요.',
    h1='변화 1: 손잡이식 지시에서 결과 중심으로',
    c1='**구 스타일(절차 우선)**\n\n> A를 확인하고 B를 확인한 뒤, 필드를 하나씩 비교하고, 모든 예외를 따져 어떤 도구를 호출할지 정하고, 끝나면 전 과정을 사용자에게 설명한다.\n\n**신 스타일(결과 우선)**\n\n> 사용자 문제를 완전히 해결한다. 정책과 계정 데이터로 무엇을 먼저 할지 정하고, 한 뒤 무엇을 했고 무엇이 남았는지 보고한다. 정보가 부족하면 가장 중요한 질문 하나만 한다.\n\n한 줄로: **목적지를 설명하고, 지도의 모든 굴곡은 쓰지 않는다.** GPT-5.5는 스스로 경로를 계획한다. 경로를 고정하면 더 나은 해법을 막을 수 있다.',
    h2='변화 2: 절대 표현은 줄이고, 진짜 레드라인에만',
    c2='«항상 JSON», «500자를 절대 넘기지 마», «답하기 전에 반드시 검색» 같은 가드레일이 흔했습니다. GPT-5.5는 **절대 표현에 매우 민감**합니다—서로 충돌하는 «반드시» 두 개가 있으면 둘 다 만족하려다 둘 다 실패할 수 있습니다.',
    tbl_h1='상황',
    tbl_h2='권장 스타일',
    tbl_r1='안전 규칙, 필수 필드, 엄격한 금지',
    tbl_r1b='always/never(항상/절대)',
    tbl_r2='검색할지, 사용자에게 물을지',
    tbl_r2b='조건문',
    c2_ex='예: «답변 전 반드시 검색»을 «질문을 받은 뒤 기존 맥락만으로 답할 수 있는지 판단하고, 가능하면 검색 없이 바로 답한다»로 바꾼다.',
    h3='변화 3: 역할은 다시 중요하지만 짧게',
    c3='«20년 경력의 최고 애널리스트…» 같은 긴 이력서형 페르소나는 GPT-5.5에서 ROI가 낮습니다. 공식 **7단 골격**은 여전히 **Role**과 **Personality**로 시작하지만 형태가 바뀌었습니다:\n\n- **Role:** 기능과 맥락을 1~2문장으로.\n- **Personality:** 톤, 온도, 협업 스타일—이력서가 아님.\n\n가이드의 두 가지 페르소나 예:\n\n- **Steady:** 믿을 만한 협업자—차분하고 직접적; 사용자는 유능하다고 가정; 불필요한 확인 없이 일을 진행.\n- **Expressive:** 대화적이고 호기심 많으며 적절히 위트; 모호하면 묻고, 맥락이 충분하면 결단.\n\n**Personality**는 «어떻게 말하는지», **협업 스타일**은 «어떻게 행동하는지」(모호한 요청에서 추측 vs. 확인)—따로 쓰세요.',
    h4='변화 4: 다단계 작업은 실행 전에 확인',
    c4='복잡한 작업에서 모델은 한동안 내부 추론만 하고 화면에 출력이 없어 사용자가 멈춘 것으로 착각하기 쉽습니다. 프롬프트에 **Preamble(서두 확인)** 규칙을 넣으세요:\n\n> 다단계 작업에서 도구를 호출하기 전에, 요청을 받았고 첫 단계가 무엇인지 알리는 짧은 사용자용 업데이트를 1~2문장으로 보낸다.\n\nCodex 같은 제품은 이미 «코드베이스를 분석 중이며, 테스트 파일부터 시작합니다» 같은 패턴을 쓰며, API와 긴 ChatGPT 작업 모두에 유효합니다.',
    h5='변화 5: 중단 조건을 정의하라',
    c5='«관련 정보를 검색한 뒤 답한다»만 쓰고 언제 멈출지 정하지 않으면 검색이 반복되고 토큰은 늘며 답은 산만해집니다.\n\n두 가지 흔한 전략:\n\n1. **검색 예산:** 일반 Q&A는 기본 1라운드; 1페이지 증거로 충분하면 답한다. 2라운드는 1페이지에 답이 없거나, 핵심 데이터가 빠지거나, 사용자가 전면 커버를 원할 때만.\n2. **루프 중단:** 각 도구 라운드 후 기존 증거로 핵심 질문에 답할 수 있는지 스스로 묻고, 가능하면 멈춘다.',
    h6='변화 6: 공식 7단 프롬프트 골격',
    c6_table='| 구간 | 목적 |\n| --- | --- |\n| Role | 기능·맥락(1~2문장) |\n| Personality | 톤·스타일·협업 |\n| Goal | 사용자에게 보이는 산출물 |\n| Success | 완료 정의 |\n| Constraints | 안전·비즈니스·증거·부작용 경계 |\n| Output | 형식·길이·목소리 |\n| Stop rules | 재시도·에스컬레이션·거절·질문·중단 시점 |',
    c6_note='참고: **매번 7단을 다 쓸 필요는 없습니다**. 단순 Q&A는 Goal+Output만으로 충분할 수 있고, 다중 도구 에이전트는 전체가 필요합니다. OpenAI 개발자 콘솔의 **Optimize**로 기존 프롬프트를 이 구조에 맞게 다듬을 수 있습니다.',
    h7='변화 7: 형식 제어와 간결한 기본값',
    c7='GPT-5.5는 기본적으로 간결하고 직접적입니다. API에서는 `text.verbosity`(`medium` 기본, 더 짧게는 `low` 시도); 복잡한 형식은 프롬프트에 큰 JSON 예시 대신 **Structured Outputs**를 쓰세요.\n\n문체는 프롬프트로도 지정할 수 있습니다. 예:\n\n> 기본은 자연스러운 단락; 제목·굵게·목록은 이해에 도움이 될 때만.\n\n리라이트는 **무엇을 유지할지**를 **어떻게 고칠지**보다 먼저:\n\n> 원문 구조·길이·문체를 유지하고 명료성만 높인다—사용자가 요청하지 않는 한 새 주장·단락을 추가하지 않는다.\n\n유지 규칙이 없으면 모델은 기본적으로 확장·재구성하기 쉽습니다.',
    h_mig='이전 팁: reasoning effort는 낮은 쪽부터',
    mig='프롬프트 외에 **`reasoning.effort`**도 재평가하세요. GPT-5.5 기본은 `medium`이고 많은 작업은 `low`로 충분합니다. 높을수록 항상 좋은 것은 아닙니다—충돌 지시나 약한 중단 규칙에 높은 effort는 과도한 검색·우회를 낳을 수 있습니다. 고정 평가 세트로 A/B를 돌리고 `low`/`medium`부터 시작해, 품질 이득이 지연·비용을 정당화할 때만 `high`/`xhigh`로 올리세요.',
    h_sum='요약: 한 줄로 기억하기',
    sum_line='**원하는 것을 말하고, 모든 실행 단계는 가르치지 마라.**',
    sum_table='| 차원 | GPT-5.4 이전 | GPT-5.5 |\n| --- | --- | --- |\n| 절차 | 상세 단계 | 결과만 |\n| 어조 | 절대 표현 다수 | 레드라인만 절대, 나머지는 조건 |\n| 역할 | 긴 배경 | 1~2문장+페르소나 |\n| 다단계 | 즉시 실행 | 먼저 확인 |\n| 중단 | 자주 생략 | 명시 권장 |\n| 구조 | 자유 | 7단 골격(필요 시 축소) |\n| 형식 | 기본값 | API 매개변수+프롬프트 |',
    outro='다시 쓴 뒤 실제 작업에서 나란히 테스트하세요. 채팅으로 GPT를 쓰려면 아래 LimaxAI 버튼에서 원하는 모델을 선택하세요.',
)

_add("es",
    intro='When GPT-5.5 launched, OpenAI published an official prompting guide. If you still write step-by-step "micromanagement" prompts from older models, you may be narrowing what the model can do. This article turns the seven most important shifts into practical guidance.',
    keywords='Keywords: chatgpt, gpt 5.5, gpt tutorial.',
    published='Published: May 22, 2026',
    img_alt='OpenAI GPT 5.5 prompt guide seven key changes',
    h_bg='Background: why legacy prompts need a rewrite',
    bg='\n\nDjango co-creator Simon Willison noted that OpenAI recommends **rewriting from scratch** rather than assuming tuned legacy prompts still work. If you are moving to GPT-5.5 (or trying similar capabilities on LimaxAI), treat prompts as a new product design—not a model-name swap.',
    h1='Change 1: from hand-holding to outcome-first',
    c1='**Estilo antiguo (proceso primero):**\n\n> Comprueba A, luego B, compara campos uno a uno, razona cada excepción, decide qué herramienta llamar y explica todo el proceso al usuario.\n\n**Estilo nuevo (resultado primero):**\n\n> Resuelve por completo el problema del usuario. Usa política y datos de cuenta para decidir qué hacer primero; informa qué se hizo y qué queda. Si falta información, haz solo la pregunta más crítica.\n\n**Describe el destino, no cada giro del mapa.** GPT-5.5 planifica su propio camino; un guion rígido puede bloquear mejores rutas.',
    h2='Change 2: fewer absolutes—reserve them for real red lines',
    c2='Guardrails like "always JSON," "never exceed 500 words," or "must search before answering" were common. GPT-5.5 is **highly sensitive to absolutes**—when two conflicting "must" rules appear, the model may try to satisfy both and fail both.',
    tbl_h1='Situation',
    tbl_h2='Recommended style',
    tbl_r1='Safety rules, required fields, hard bans',
    tbl_r1b='Use always/never',
    tbl_r2='Whether to search or ask the user',
    tbl_r2b='Use conditional rules',
    c2_ex='Example: replace "must search before answering" with "After receiving the question, check whether existing context is enough to answer; if yes, reply directly without searching."',
    h3='Change 3: roles return—but stay short',
    c3='\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Change 4: acknowledge multi-step work before executing',
    c4='\n\nProducts like Codex already use this pattern (e.g. "Analyzing your codebase, starting with test files") for APIs and long ChatGPT tasks alike.',
    h5='Change 5: define stop conditions',
    c5='Si solo dices «busca información relevante y responde» sin definir cuándo parar, el modelo puede entrar en bucles de recuperación.\n\nDos estrategias habituales:\n\n1. **Presupuesto de búsqueda:** una ronda por defecto en Q&A normal; responde si la evidencia de la primera página basta. Segunda ronda solo si la primera no tiene la respuesta, faltan datos clave o el usuario pide cobertura exhaustiva.\n2. **Parada de bucle:** tras cada ronda de herramientas, pregúntate si la evidencia actual responde la pregunta central; si sí, para.',
    h6='Change 6: the official seven-part prompt skeleton',
    c6_table='| Section | Purpose |\n| --- | --- |\n| Role | 1–2 sentences: function and context |\n| Personality | Tone, style, collaboration |\n| Goal | User-visible deliverable |\n| Success | Definition of done |\n| Constraints | Safety, business, evidence, side effects |\n| Output | Format, length, voice |\n| Stop rules | When to retry, escalate, refuse, ask, or stop |',
    c6_note='OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Change 7: format control and concise defaults',
    c7='GPT-5.5 responde de forma concisa y directa por defecto. En la API usa `text.verbosity` (`medium` por defecto; prueba `low` para respuestas más cortas); para formatos complejos prioriza **Structured Outputs**.\n\nEjemplo:\n\n> Por defecto párrafos naturales; títulos, negrita y listas solo cuando ayuden a comprender.\n\nEn reescrituras, indica **qué conservar** antes de **cómo editar**:\n\n> Conserva estructura, longitud y voz originales; mejora solo la claridad—sin nuevas afirmaciones o párrafos salvo petición del usuario.\n\nSin reglas de conservación, el modelo suele expandir y reestructurar por defecto.',
    h_mig='Migration tip: tune reasoning effort from the low end',
    mig='Beyond prompts, re-evaluate **`reasoning.effort`**. GPT-5.5 defaults to `medium`; many tasks work at `low`. Higher is not automatically better—conflicting instructions or weak stop rules plus high effort can mean over-searching and detours. Run A/B tests on a fixed eval set; start with `low` / `medium`, then move to `high` / `xhigh` only when quality gains justify latency and cost.',
    h_sum='Summary: one line to remember',
    sum_line='**Say what you want—not how to do every step.**',
    sum_table='| Dimension | GPT-5.4 and earlier | GPT-5.5 |\n| --- | --- | --- |\n| Process | Detailed steps | Outcomes only |\n| Tone | Many absolutes | Absolutes for red lines; conditionals elsewhere |\n| Role | Long background | 1–2 sentences + personality |\n| Multi-step | Execute immediately | Preamble first |\n| Stopping | Often omitted | Should be explicit |\n| Structure | Free-form | Seven-part skeleton (trim as needed) |\n| Format | Defaults | API params + prompt guidance |',
    outro='After rewriting, run side-by-side tests on real tasks. To try GPT in chat, use the button below on LimaxAI with your preferred model.',
)

_add("fr",
    intro='Avec le lancement de GPT-5.5, OpenAI a publié un guide officiel de prompting. Si vous écrivez encore des prompts « pas à pas » des anciens modèles, vous limitez peut-être le modèle. Cet article transforme les sept changements les plus importants en conseils pratiques.',
    keywords='Mots-clés : chatgpt, gpt 5.5, tutoriel gpt.',
    published='Publié le 22 mai 2026',
    img_alt='Guide de prompts OpenAI GPT 5.5 sept changements clés',
    h_bg='Contexte : pourquoi réécrire les anciens prompts',
    bg="La documentation est claire : les anciens prompts **sur-spécifient souvent le processus**, car les modèles précédents avaient besoin de plus de garde-fous. Avec GPT-5.5, ce détail devient du bruit, réduit l'espace de recherche et produit des réponses mécaniques.\n\nSimon Willison, co-créateur de Django, a noté qu'OpenAI recommande de **réécrire from scratch** plutôt que de supposer que d'anciens prompts ajustés fonctionnent encore. Si vous migrez vers GPT-5.5 (ou testez des capacités similaires sur LimaxAI), traitez les prompts comme une nouvelle conception produit, pas un simple changement de nom de modèle.",
    h1="Changement 1 : de la main dans la main au résultat d'abord",
    c1="**Ancien style (processus d'abord)**\n\n> Vérifier A, puis B, comparer champ par champ, raisonner sur chaque exception, choisir l'outil, puis expliquer tout le processus à l'utilisateur.\n\n**Nouveau style (résultat d'abord)**\n\n> Résoudre entièrement le problème de l'utilisateur. S'appuyer sur la politique et les données de compte pour décider quoi faire en premier, puis indiquer ce qui a été fait et ce qui reste. Une seule question critique si une information manque.\n\nEn une ligne : **décrivez la destination, pas chaque virage sur la carte.** GPT-5.5 planifie son propre chemin ; un script rigide peut bloquer de meilleures routes.",
    h2="Changement 2 : moins d'absolus—réservez-les aux vraies lignes rouges",
    c2='Des garde-fous comme « toujours JSON », « ne jamais dépasser 500 mots » ou « doit chercher avant de répondre » étaient courants. GPT-5.5 est **très sensible aux absolus** : deux règles « doit » contradictoires peuvent faire échouer les deux.',
    tbl_h1='Cas',
    tbl_h2='Style recommandé',
    tbl_r1='Sécurité, champs requis, interdictions strictes',
    tbl_r1b='toujours/jamais',
    tbl_r2="Chercher ou demander à l'utilisateur",
    tbl_r2b='règles conditionnelles',
    c2_ex='Exemple : remplacez « doit chercher avant de répondre » par « Après la question, vérifier si le contexte existant suffit ; si oui, répondre sans chercher ».',
    h3='Changement 3 : le rôle revient—mais reste court',
    c3="Les longues personas CV (« analyste top avec 20 ans d'expérience… ») ont un faible ROI sur GPT-5.5. Le **squelette officiel en sept parties** commence toujours par **Role** et **Personality**, mais la forme a changé :\n\n- **Role:** 1–2 phrases sur la fonction et le contexte.\n- **Personality:** ton, chaleur et style de collaboration—pas un CV.\n\nDeux modèles de personnalité du guide :\n\n- **Steady:** collaborateur fiable—calme, direct ; suppose que l'utilisateur est capable ; avance sans confirmations inutiles.\n- **Expressive:** conversationnel, curieux, spirituel quand c'est pertinent ; demande si c'est ambigu, décide si le contexte suffit.\n\n**Personality** = comment ça sonne ; **style de collaboration** = comment ça agit (deviner vs. clarifier sur des demandes vagues)—écrivez-les séparément.",
    h4="Changement 4 : accuser réception avant d'exécuter",
    c4="Sur des tâches complexes, le modèle peut raisonner en silence sans sortie visible ; l'utilisateur croit qu'il est bloqué. Ajoutez une règle de **préambule** :\n\n> Sur les tâches multi-étapes, avant tout appel d'outil, envoyer une courte mise à jour visible confirmant la réception et la première action—une ou deux phrases.\n\nDes produits comme Codex utilisent déjà ce schéma (p. ex. « Analyse de votre dépôt, en commençant par les tests ») pour l'API et les longues tâches ChatGPT.",
    h5="Changement 5 : définir les conditions d'arrêt",
    c5="Si vous écrivez seulement « chercher puis répondre » sans définir quand s'arrêter, le modèle peut boucler la récupération : les tokens montent et les réponses se dispersent.\n\nDeux stratégies courantes :\n\n1. **Budget de recherche:** une ronde par défaut en Q&R ordinaire ; répondre si la première page suffit. Deuxième ronde seulement si la première page n'a pas la réponse, données clés manquantes ou demande exhaustive de l'utilisateur.\n2. **Arrêt de boucle:** après chaque ronde d'outils, se demander si les preuves actuelles répondent à la question centrale ; si oui, arrêter.",
    h6='Changement 6 : le squelette officiel en sept parties',
    c6_table='| Partie | Rôle |\n| --- | --- |\n| Role | Fonction et contexte (1–2 phrases) |\n| Personality | Ton, style, collaboration |\n| Goal | Livrable visible |\n| Success | Définition du terminé |\n| Constraints | Sécurité, business, preuves, effets |\n| Output | Format, longueur, voix |\n| Stop rules | Quand réessayer, escalader, refuser, demander ou arrêter |',
    c6_note="Note : **vous n'avez pas besoin des sept à chaque fois**. Q&R simple : Goal + Output ; agents multi-outils : ensemble complet. La console développeur OpenAI propose aussi **Optimize** pour adapter les prompts existants.",
    h7='Changement 7 : format et concision par défaut',
    c7="GPT-5.5 répond de façon concise et directe par défaut. Côté API, `text.verbosity` (`medium` par défaut ; essayez `low` pour plus court) ; pour les formats complexes, préférez **Structured Outputs** plutôt que de gros exemples JSON dans le prompt.\n\nVous pouvez aussi guider la mise en page en prose, par exemple :\n\n> Par défaut des paragraphes naturels ; titres, gras et listes seulement s'ils aident la compréhension.\n\nPour les réécritures, indiquez **quoi préserver** avant **comment éditer** :\n\n> Conserver structure, longueur et voix d'origine ; améliorer seulement la clarté—pas de nouvelles affirmations ou paragraphes sauf demande de l'utilisateur.\n\nSans règles de préservation, le modèle tend à développer et restructurer par défaut.",
    h_mig='Astuce migration : régler reasoning effort depuis le bas',
    mig="Au-delà des prompts, réévaluez **`reasoning.effort`**. GPT-5.5 est en `medium` par défaut ; beaucoup de tâches suffisent en `low`. Plus haut n'est pas automatiquement mieux : instructions conflictuelles ou règles d'arrêt faibles + effort élevé = sur-recherche et détours. Faites des A/B sur un jeu d'éval fixe ; commencez `low`/`medium`, puis `high`/`xhigh` seulement si le gain qualité justifie latence et coût.",
    h_sum='Résumé : une ligne à retenir',
    sum_line='**Dites ce que vous voulez—pas comment faire chaque étape.**',
    sum_table="| Dimension | GPT-5.4 et avant | GPT-5.5 |\n| --- | --- | --- |\n| Processus | Étapes détaillées | Résultats seulement |\n| Ton | Beaucoup d'absolus | Absolus pour lignes rouges ; conditionnels ailleurs |\n| Rôle | Long parcours | 1–2 phrases + personnalité |\n| Multi-étapes | Exécuter tout de suite | Préambule d'abord |\n| Arrêt | Souvent omis | Doit être explicite |\n| Structure | Libre | Squelette 7 parties (rogner si besoin) |\n| Format | Défauts | Paramètres API + prompt |",
    outro='Après réécriture, testez côte à côte sur de vraies tâches. Pour essayer GPT en chat, utilisez le bouton ci-dessous sur LimaxAI avec le modèle de votre choix.',
)

_add("de",
    intro='When GPT-5.5 launched, OpenAI published an official prompting guide. If you still write step-by-step "micromanagement" prompts from older models, you may be narrowing what the model can do. This article turns the seven most important shifts into practical guidance.',
    keywords='Keywords: chatgpt, gpt 5.5, gpt tutorial.',
    published='Published: May 22, 2026',
    img_alt='OpenAI GPT 5.5 prompt guide seven key changes',
    h_bg='Background: why legacy prompts need a rewrite',
    bg='\n\nDjango-Mitgründer Simon Willison wies darauf hin, dass OpenAI empfiehlt, **von Grund auf neu zu schreiben**, statt anzunehmen, dass getunte Legacy-Prompts noch funktionieren. Wenn Sie zu GPT-5.5 wechseln (oder ähnliche Fähigkeiten auf LimaxAI testen), behandeln Sie Prompts als neues Produktdesign—not a model swap.',
    h1='Change 1: from hand-holding to outcome-first',
    c1='**Alter Stil (Prozess zuerst):**\n\n> Prüfe A, dann B, vergleiche Felder einzeln, durchdenke alle Ausnahmen, wähle ein Tool und erkläre danach den gesamten Ablauf.\n\n**Neuer Stil (Ergebnis zuerst):**\n\n> Löse das Anliegen des Nutzers vollständig. Nutze Richtlinien und Kontodaten, um die Priorität zu setzen, berichte, was erledigt ist und was offen bleibt. Stelle bei fehlenden Infos nur die wichtigste Frage.\n\n**Beschreibe das Ziel, nicht jeden Schritt auf der Karte.** GPT-5.5 plant den Weg selbst; ein starres Skript blockiert bessere Routen.',
    h2='Change 2: fewer absolutes—reserve them for real red lines',
    c2='Guardrails like "always JSON," "never exceed 500 words," or "must search before answering" were common. GPT-5.5 is **highly sensitive to absolutes**—when two conflicting "must" rules appear, the model may try to satisfy both and fail both.',
    tbl_h1='Situation',
    tbl_h2='Recommended style',
    tbl_r1='Safety rules, required fields, hard bans',
    tbl_r1b='Use always/never',
    tbl_r2='Whether to search or ask the user',
    tbl_r2b='Use conditional rules',
    c2_ex='Example: replace "must search before answering" with "After receiving the question, check whether existing context is enough to answer; if yes, reply directly without searching."',
    h3='Change 3: roles return—but stay short',
    c3='\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Change 4: acknowledge multi-step work before executing',
    c4='\n\nProdukte wie Codex nutzen dieses Muster bereits (z. B. «Analysiere deine Codebasis, beginne mit Testdateien») für API und lange ChatGPT-Aufgaben.',
    h5='Change 5: define stop conditions',
    c5='Wenn nur «suche relevante Informationen und antworte» steht, ohne Stopp, kann das Modell in Suchschleifen geraten.\n\nZwei gängige Strategien:\n\n1. **Suchbudget:** standardmäßig eine Runde bei normaler Q&A; antworten, wenn Seite eins reicht. Zweite Runde nur ohne Antwort auf Seite eins, fehlende Schlüsseldaten oder Wunsch nach Vollständigkeit.\n2. **Schleifenstopp:** nach jeder Tool-Runde prüfen, ob die vorhandenen Belege die Kernfrage beantworten; wenn ja, stoppen.',
    h6='Change 6: the official seven-part prompt skeleton',
    c6_table='| Section | Purpose |\n| --- | --- |\n| Role | 1–2 sentences: function and context |\n| Personality | Tone, style, collaboration |\n| Goal | User-visible deliverable |\n| Success | Definition of done |\n| Constraints | Safety, business, evidence, side effects |\n| Output | Format, length, voice |\n| Stop rules | When to retry, escalate, refuse, ask, or stop |',
    c6_note='OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Change 7: format control and concise defaults',
    c7='GPT-5.5 antwortet standardmäßig knapp und direkt. API: `text.verbosity` (Standard `medium`, kürzer mit `low`); komplexe Formate über **Structured Outputs**.\n\nBeispiel für Layout:\n\n> Standardmäßig natürliche Absätze; Überschriften, Fett und Listen nur bei Mehrwert für Verständnis.\n\nBei Umschreibungen zuerst **was bleibt**, dann **wie editieren**:\n\n> Struktur, Länge und Stimme beibehalten; nur Klarheit verbessern—keine neuen Behauptungen oder Absätze ohne Nutzerwunsch.\n\nOhne Erhaltungsregeln expandiert das Modell oft standardmäßig.',
    h_mig='Migration tip: tune reasoning effort from the low end',
    mig='Beyond prompts, re-evaluate **`reasoning.effort`**. GPT-5.5 defaults to `medium`; many tasks work at `low`. Higher is not automatically better—conflicting instructions or weak stop rules plus high effort can mean over-searching and detours. Run A/B tests on a fixed eval set; start with `low` / `medium`, then move to `high` / `xhigh` only when quality gains justify latency and cost.',
    h_sum='Summary: one line to remember',
    sum_line='**Say what you want—not how to do every step.**',
    sum_table='| Dimension | GPT-5.4 and earlier | GPT-5.5 |\n| --- | --- | --- |\n| Process | Detailed steps | Outcomes only |\n| Tone | Many absolutes | Absolutes for red lines; conditionals elsewhere |\n| Role | Long background | 1–2 sentences + personality |\n| Multi-step | Execute immediately | Preamble first |\n| Stopping | Often omitted | Should be explicit |\n| Structure | Free-form | Seven-part skeleton (trim as needed) |\n| Format | Defaults | API params + prompt guidance |',
    outro='After rewriting, run side-by-side tests on real tasks. To try GPT in chat, use the button below on LimaxAI with your preferred model.',
)

_add("pt",
    intro='When GPT-5.5 launched, OpenAI published an official prompting guide. If you still write step-by-step "micromanagement" prompts from older models, you may be narrowing what the model can do. This article turns the seven most important shifts into practical guidance.',
    keywords='Keywords: chatgpt, gpt 5.5, gpt tutorial.',
    published='Published: May 22, 2026',
    img_alt='OpenAI GPT 5.5 prompt guide seven key changes',
    h_bg='Background: why legacy prompts need a rewrite',
    bg='\n\nO cofundador do Django Simon Willison observou que a OpenAI recomenda **reescrever do zero** em vez de assumir que prompts legados ainda funcionam. Ao migrar para GPT-5.5 (ou testar capacidades semelhantes no LimaxAI), trate os prompts como um novo design de produto—not a troca de nome do modelo.',
    h1='Change 1: from hand-holding to outcome-first',
    c1='**Estilo antigo (processo primeiro):**\n\n> Verifique A, depois B, compare campos um a um, raciocine exceções, escolha a ferramenta e explique todo o processo ao usuário.\n\n**Estilo novo (resultado primeiro):**\n\n> Resolva completamente o problema do usuário. Use política e dados da conta para decidir o que fazer primeiro; informe o feito e o pendente. Uma só pergunta crítica se faltar informação.\n\n**Descreva o destino, não cada curva do mapa.** O GPT-5.5 planeja o caminho; um roteiro rígido pode bloquear rotas melhores.',
    h2='Change 2: fewer absolutes—reserve them for real red lines',
    c2='Guardrails like "always JSON," "never exceed 500 words," or "must search before answering" were common. GPT-5.5 is **highly sensitive to absolutes**—when two conflicting "must" rules appear, the model may try to satisfy both and fail both.',
    tbl_h1='Situation',
    tbl_h2='Recommended style',
    tbl_r1='Safety rules, required fields, hard bans',
    tbl_r1b='Use always/never',
    tbl_r2='Whether to search or ask the user',
    tbl_r2b='Use conditional rules',
    c2_ex='Example: replace "must search before answering" with "After receiving the question, check whether existing context is enough to answer; if yes, reply directly without searching."',
    h3='Change 3: roles return—but stay short',
    c3='\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Change 4: acknowledge multi-step work before executing',
    c4='\n\nProdutos como o Codex já usam este padrão (p. ex. «Analisando seu repositório, começando pelos testes») em API e tarefas longas do ChatGPT.',
    h5='Change 5: define stop conditions',
    c5='Só «busque informações relevantes e responda» sem parada pode gerar loops de busca.\n\nDuas estratégias comuns:\n\n1. **Orçamento de busca:** uma rodada por padrão em Q&A comum; responda se a primeira página bastar. Segunda rodada só sem resposta na primeira, dados-chave ausentes ou pedido exaustivo.\n2. **Parada de loop:** após cada rodada de ferramentas, pergunte se as evidências respondem à pergunta central; se sim, pare.',
    h6='Change 6: the official seven-part prompt skeleton',
    c6_table='| Section | Purpose |\n| --- | --- |\n| Role | 1–2 sentences: function and context |\n| Personality | Tone, style, collaboration |\n| Goal | User-visible deliverable |\n| Success | Definition of done |\n| Constraints | Safety, business, evidence, side effects |\n| Output | Format, length, voice |\n| Stop rules | When to retry, escalate, refuse, ask, or stop |',
    c6_note='OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Change 7: format control and concise defaults',
    c7='O GPT-5.5 é conciso por padrão. Na API use `text.verbosity` (`medium` padrão; `low` para respostas mais curtas) e **Structured Outputs** para formatos complexos.\n\nExemplo de layout:\n\n> Parágrafos naturais por padrão; títulos, negrito e listas só quando ajudarem a compreensão.\n\nEm reescritas, diga **o que preservar** antes de **como editar**:\n\n> Mantenha estrutura, extensão e voz; melhore só a clareza—sem novas afirmações ou parágrafos salvo pedido do usuário.\n\nSem regras de preservação, o modelo tende a expandir e reestruturar.',
    h_mig='Migration tip: tune reasoning effort from the low end',
    mig='Beyond prompts, re-evaluate **`reasoning.effort`**. GPT-5.5 defaults to `medium`; many tasks work at `low`. Higher is not automatically better—conflicting instructions or weak stop rules plus high effort can mean over-searching and detours. Run A/B tests on a fixed eval set; start with `low` / `medium`, then move to `high` / `xhigh` only when quality gains justify latency and cost.',
    h_sum='Summary: one line to remember',
    sum_line='**Say what you want—not how to do every step.**',
    sum_table='| Dimension | GPT-5.4 and earlier | GPT-5.5 |\n| --- | --- | --- |\n| Process | Detailed steps | Outcomes only |\n| Tone | Many absolutes | Absolutes for red lines; conditionals elsewhere |\n| Role | Long background | 1–2 sentences + personality |\n| Multi-step | Execute immediately | Preamble first |\n| Stopping | Often omitted | Should be explicit |\n| Structure | Free-form | Seven-part skeleton (trim as needed) |\n| Format | Defaults | API params + prompt guidance |',
    outro='After rewriting, run side-by-side tests on real tasks. To try GPT in chat, use the button below on LimaxAI with your preferred model.',
)

_add("it",
    intro='When GPT-5.5 launched, OpenAI published an official prompting guide. If you still write step-by-step "micromanagement" prompts from older models, you may be narrowing what the model can do. This article turns the seven most important shifts into practical guidance.',
    keywords='Keywords: chatgpt, gpt 5.5, gpt tutorial.',
    published='Published: May 22, 2026',
    img_alt='OpenAI GPT 5.5 prompt guide seven key changes',
    h_bg='Background: why legacy prompts need a rewrite',
    bg='\n\nIl co-creatore di Django Simon Willison ha notato che OpenAI consiglia di **riscrivere da zero** invece di assumere che i prompt legacy funzionino ancora. Migrando a GPT-5.5 (o provando capacità simili su LimaxAI), tratta i prompt come un nuovo design di prodotto—not a simple model rename.',
    h1='Change 1: from hand-holding to outcome-first',
    c1="**Stile vecchio (processo prima):**\n\n> Controlla A, poi B, confronta i campi uno a uno, ragiona su ogni eccezione, scegli lo strumento e spiega tutto il processo all'utente.\n\n**Stile nuovo (risultato prima):**\n\n> Risolvi completamente il problema dell'utente. Usa policy e dati account per decidere cosa fare prima; riporta fatto e restante. Una sola domanda critica se mancano dati.\n\n**Descrivi la destinazione, non ogni svolta sulla mappa.** GPT-5.5 pianifica il percorso; uno script rigido può bloccare strade migliori.",
    h2='Change 2: fewer absolutes—reserve them for real red lines',
    c2='Guardrails like "always JSON," "never exceed 500 words," or "must search before answering" were common. GPT-5.5 is **highly sensitive to absolutes**—when two conflicting "must" rules appear, the model may try to satisfy both and fail both.',
    tbl_h1='Situation',
    tbl_h2='Recommended style',
    tbl_r1='Safety rules, required fields, hard bans',
    tbl_r1b='Use always/never',
    tbl_r2='Whether to search or ask the user',
    tbl_r2b='Use conditional rules',
    c2_ex='Example: replace "must search before answering" with "After receiving the question, check whether existing context is enough to answer; if yes, reply directly without searching."',
    h3='Change 3: roles return—but stay short',
    c3='\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Change 4: acknowledge multi-step work before executing',
    c4='\n\nProdotti come Codex usano già questo schema (es. «Analisi del repository, partendo dai test») per API e lunghe attività ChatGPT.',
    h5='Change 5: define stop conditions',
    c5='Solo «cerca informazioni pertinenti e rispondi» senza stop può creare loop di retrieval.\n\nDue strategie comuni:\n\n1. **Budget di ricerca:** un giro di default in Q&A normale; rispondi se basta la prima pagina. Secondo giro solo senza risposta in pagina uno, dati chiave mancanti o richiesta esaustiva.\n2. **Stop del ciclo:** dopo ogni giro di tool chiediti se le prove bastano per la domanda centrale; se sì, fermati.',
    h6='Change 6: the official seven-part prompt skeleton',
    c6_table='| Section | Purpose |\n| --- | --- |\n| Role | 1–2 sentences: function and context |\n| Personality | Tone, style, collaboration |\n| Goal | User-visible deliverable |\n| Success | Definition of done |\n| Constraints | Safety, business, evidence, side effects |\n| Output | Format, length, voice |\n| Stop rules | When to retry, escalate, refuse, ask, or stop |',
    c6_note='OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Change 7: format control and concise defaults',
    c7='GPT-5.5 è conciso per impostazione. API: `text.verbosity` (default `medium`, prova `low`); formati complessi con **Structured Outputs**.\n\nEsempio di layout:\n\n> Paragrafi naturali di default; titoli, grassetto e elenchi solo se aiutano la comprensione.\n\nNelle riscritture indica **cosa preservare** prima di **come modificare**:\n\n> Mantieni struttura, lunghezza e voce; migliora solo chiarezza—niente nuove affermazioni o paragrafi salvo richiesta.\n\nSenza regole di preservazione il modello espande e ristruttura spesso.',
    h_mig='Migration tip: tune reasoning effort from the low end',
    mig='Beyond prompts, re-evaluate **`reasoning.effort`**. GPT-5.5 defaults to `medium`; many tasks work at `low`. Higher is not automatically better—conflicting instructions or weak stop rules plus high effort can mean over-searching and detours. Run A/B tests on a fixed eval set; start with `low` / `medium`, then move to `high` / `xhigh` only when quality gains justify latency and cost.',
    h_sum='Summary: one line to remember',
    sum_line='**Say what you want—not how to do every step.**',
    sum_table='| Dimension | GPT-5.4 and earlier | GPT-5.5 |\n| --- | --- | --- |\n| Process | Detailed steps | Outcomes only |\n| Tone | Many absolutes | Absolutes for red lines; conditionals elsewhere |\n| Role | Long background | 1–2 sentences + personality |\n| Multi-step | Execute immediately | Preamble first |\n| Stopping | Often omitted | Should be explicit |\n| Structure | Free-form | Seven-part skeleton (trim as needed) |\n| Format | Defaults | API params + prompt guidance |',
    outro='After rewriting, run side-by-side tests on real tasks. To try GPT in chat, use the button below on LimaxAI with your preferred model.',
)

_add("ru",
    intro='OpenAI опубликовал официальное руководство по промптам GPT-5.5. Пошаговые инструкции старых моделей могут сужать возможности модели. Ниже — 7 ключевых изменений.',
    keywords='Ключевые слова: chatgpt, gpt 5.5, урок gpt.',
    published='Дата: 22 мая 2026 г.',
    img_alt='Руководство по промптам GPT 5.5 OpenAI',
    h_bg='Контекст: зачем переписывать старые промпты',
    bg='Старые промпты часто **перегружают процесс** — раньше моделям нужны были жёсткие рельсы. С GPT-5.5 это шум: сужает пространство поиска и даёт механические ответы. **Перепишите с нуля**, не копируйте старые шаблоны.\n\nСооснователь Django Simon Willison отметил, что OpenAI рекомендует **переписать с нуля**, а не полагать, что старые промпты работают. При переходе на GPT-5.5 (или в LimaxAI) относитесь к промптам как к новому продукту.',
    h1='Изменение 1: от пошаговости к результату',
    c1='**Старый стиль (процесс):**\n\n> Проверь A, затем B, сравни поля по одному, обработай исключения, выбери инструмент и объясни пользователю весь процесс.\n\n**Новый стиль (результат):**\n\n> Полностью решите запрос пользователя. Опирайтесь на политику и данные аккаунта; сообщите, что сделано и что осталось. Один критический вопрос при нехватке данных.\n\n**Опишите пункт назначения, а не каждый поворот.** GPT-5.5 сам планирует путь; жёсткий сценарий мешает лучшим решениям.',
    h2='Изменение 2: меньше «обязательно» и «запрещено»',
    c2='GPT-5.5 чувствителен к абсолютным формулировкам; противоречивые «должен» ломают оба правила.',
    tbl_h1='Ситуация',
    tbl_h2='Стиль',
    tbl_r1='Безопасность, обязательные поля',
    tbl_r1b='всегда/никогда',
    tbl_r2='Искать или спрашивать',
    tbl_r2b='условия',
    c2_ex='Пример: вместо «перед ответом обязательно искать» — «если контекста достаточно, отвечай без поиска».',
    h3='Изменение 3: роль снова нужна, но коротко',
    c3='**Role** — 1–2 предложения о функции; **Personality** — тон и стиль совместной работы, не резюме на 20 лет.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Изменение 4: преамбула перед многошаговой работой',
    c4='Перед инструментами отправьте 1–2 видимых предложения: запрос принят, первый шаг — …\n\nПродукты вроде Codex уже используют этот шаблон (напр. «Анализирую кодовую базу, начну с тестов») для API и длинных задач ChatGPT.',
    h5='Изменение 5: явные условия остановки',
    c5='Фраза «найди информацию и ответь» без стопа ведёт к циклам поиска.\n\nДве стратегии:\n\n1. **Бюджет поиска:** по умолчанию один раунд; отвечайте, если хватает первой страницы. Второй раунд — только если на первой нет ответа, нет ключевых данных или нужна полнота.\n2. **Стоп цикла:** после каждого инструмента спросите, хватает ли доказательств на главный вопрос; если да — стоп.',
    h6='Изменение 6: скелет из 7 блоков',
    c6_table='| Блок | Назначение |\n| --- | --- |\n| Role | Функция |\n| Personality | Тон |\n| Goal | Результат |\n| Success | Готово |\n| Constraints | Границы |\n| Output | Формат |\n| Stop | Когда остановиться |',
    c6_note='Для простых вопросов достаточно Goal + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Изменение 7: формат и краткость',
    c7='GPT-5.5 по умолчанию краток. В API — `text.verbosity` (по умолчанию `medium`, для короче — `low`) и **Structured Outputs**.\n\nПример оформления:\n\n> Естественные абзацы по умолчанию; заголовки и списки — только для ясности.\n\nПри переписывании сначала **что сохранить**:\n\n> Сохраняйте структуру, длину и голос; улучшайте ясность — без новых тезисов без запроса.\n\nБез правил сохранения модель часто расширяет текст.',
    h_mig='Миграция: reasoning с низкого уровня',
    mig='Пересмотрите `reasoning.effort`: по умолчанию medium, часто хватает low. Повышайте только по метрикам качества.',
    h_sum='Итог',
    sum_line='**Скажите, что нужно — не каждый шаг выполнения.**',
    sum_table='| Измерение | Раньше | GPT-5.5 |\n| --- | --- | --- |\n| Процесс | Подробные шаги | Результат |\n| Тон | Много абсолютов | Абсолюты только для красных линий |\n| Роль | Длинные био | Коротко |\n| Многошаг | Сразу в работу | Сначала преамбула |\n| Стоп | Часто нет | Явно |\n| Структура | Свободно | 7 блоков |\n| Формат | По умолчанию | API + промпт |',
    outro='Протестируйте на реальных задачах, затем попробуйте GPT на LimaxAI кнопкой ниже.',
)

_add("uk",
    intro='OpenAI опублікував офіційний гайд із промптів GPT-5.5. Покрокові інструкції старих моделей можуть обмежувати модель. Ось 7 ключових змін.',
    keywords='Ключові слова: chatgpt, gpt 5.5, урок gpt.',
    published='Дата: 22 травня 2026',
    img_alt='Гайд промптів GPT 5.5 OpenAI',
    h_bg='Контекст: навіщо переписувати старі промпти',
    bg='Старі промпти часто **перевантажують процес**. З GPT-5.5 це шум — **перепишіть з нуля**.\n\nСпівзасновник Django Simon Willison зазначив, що OpenAI радить **переписати з нуля**. Переходячи на GPT-5.5 (або тестуючи в LimaxAI), ставтеся до промптів як до нового продукту.',
    h1='Зміна 1: від покроковості до результату',
    c1='**Старий стиль (процес):**\n\n> Перевір A, потім B, порівняй поля, оброби винятки, обери інструмент і поясни весь процес.\n\n**Новий стиль (результат):**\n\n> Повністю виріші запит користувача. Дій за політикою та даними; повідом, що зроблено і що лишилось. Одне критичне питання за потреби.\n\n**Опишіть пункт призначення, не кожен поворот.** GPT-5.5 сам планує шлях; жорсткий сценарій заважає кращим рішенням.',
    h2="Зміна 2: менше «обов'язково»",
    c2='GPT-5.5 чутливий до абсолютів; суперечливі правила ламаються.',
    tbl_h1='Ситуація',
    tbl_h2='Стиль',
    tbl_r1="Безпека, обов'язкові поля",
    tbl_r1b='завжди/ніколи',
    tbl_r2='Шукати чи питати',
    tbl_r2b='умови',
    c2_ex="Замість «обов'язково шукати» — «якщо контексту достатньо, відповідай без пошуку».",
    h3='Зміна 3: коротка роль',
    c3='**Role** 1–2 речення; **Personality** — тон і співпраця.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Зміна 4: преамбула',
    c4='Перед інструментами — 1–2 видимі речення про прийом запиту та перший крок.\n\nПродукти на кшталт Codex уже використовують цей шаблон для API та довгих задач ChatGPT.',
    h5='Зміна 5: умови зупинки',
    c5='«Знайди інформацію і відповідай» без стопу веде до циклів пошуку.\n\nДві стратегії:\n\n1. **Бюджет пошуку:** за замовчуванням один раунд; відповідай, якщо вистачає першої сторінки.\n2. **Стоп циклу:** після кожного інструмента — чи вистачає доказів на головне питання.',
    h6='Зміна 6: скелет із 7 блоків',
    c6_table='| Блок | Призначення |\n| --- | --- |\n| Role | Функція |\n| Personality | Тон |\n| Goal | Результат |\n| Success | Готово |\n| Constraints | Межі |\n| Output | Формат |\n| Stop | Зупинка |',
    c6_note='Простим запитам часто вистачає Goal + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Зміна 7: формат',
    c7='GPT-5.5 стислий за замовчуванням. API: `text.verbosity`, **Structured Outputs**.\n\n> Природні абзаци за замовчуванням.\n\n> Зберігайте структуру, довжину й голос; покращуйте ясність без нових тез без запиту.',
    h_mig='Міграція: reasoning з низького',
    mig='Перегляньте `reasoning.effort`; часто вистачає low.',
    h_sum='Підсумок',
    sum_line='**Скажіть, що потрібно — не кожен крок.**',
    sum_table='| Вимір | Раніше | GPT-5.5 |\n| --- | --- | --- |\n| Процес | Кроки | Результат |\n| Тон | Абсолюти | Лише червоні лінії |\n| Роль | Довго | Коротко |\n| Багатокрок | Одразу | Преамбула |\n| Стоп | Немає | Явно |\n| Структура | Вільно | 7 блоків |\n| Формат | За замовч. | API+prompt |',
    outro='Протестуйте на реальних задачах і спробуйте GPT на LimaxAI.',
)

_add("pl",
    intro='OpenAI opublikował oficjalny przewodnik promptów GPT-5.5. Prompty krok po kroku ze starych modeli mogą ograniczać wyniki. Oto 7 kluczowych zmian.',
    keywords='Słowa kluczowe: chatgpt, gpt 5.5, samouczek gpt.',
    published='Data: 22 maja 2026',
    img_alt='Przewodnik promptów GPT 5.5',
    h_bg='Tło: dlaczego przepisać stare prompty',
    bg='Stare prompty **nadmiernie opisują proces**. Przy GPT-5.5 to szum — **przepisz od zera**.\n\nWspółtwórca Django Simon Willison zauważył, że OpenAI zaleca **pisać od zera**. Przechodząc na GPT-5.5 (lub testując w LimaxAI), traktuj prompty jak nowy produkt.',
    h1='Zmiana 1: z procesu na wynik',
    c1='**Stary styl (proces):**\n\n> Sprawdź A, potem B, porównaj pola, rozważ wyjątki, wybierz narzędzie i wyjaśnij cały proces.\n\n**Nowy styl (wynik):**\n\n> Rozwiąż problem użytkownika w całości. Działaj wg polityki i danych; podaj, co zrobiono i co zostało. Jedno kluczowe pytanie przy braku danych.\n\n**Opisz cel, nie każdy krok.** GPT-5.5 sam planuje trasę.',
    h2='Zmiana 2: mniej absolutów',
    c2='GPT-5.5 jest wrażliwy na «musi/zawsze»; sprzeczne reguły zawodzą.',
    tbl_h1='Sytuacja',
    tbl_h2='Styl',
    tbl_r1='Bezpieczeństwo, pola wymagane',
    tbl_r1b='zawsze/nigdy',
    tbl_r2='Szukać czy pytać',
    tbl_r2b='warunki',
    c2_ex='Zamiast «musi szukać» — «jeśli kontekst wystarcza, odpowiedz bez szukania».',
    h3='Zmiana 3: krótka rola',
    c3='**Rola** 1–2 zdania; **osobowość** = ton i współpraca.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Zmiana 4: preambuła',
    c4='Przed narzędziami: 1–2 widoczne zdania o przyjęciu zadania i pierwszym kroku.\n\nProdukty takie jak Codex już stosują ten wzorzec (np. analiza repozytorium, zaczynając od testów) w API i długich zadaniach ChatGPT.',
    h5='Zmiana 5: warunki stopu',
    c5='Samo «wyszukaj i odpowiedz» bez stopu tworzy pętle.\n\n1. **Budżet wyszukiwania:** domyślnie jedna runda.\n2. **Stop pętli:** po każdym narzędziu — czy dowody wystarczają.',
    h6='Zmiana 6: szkielet 7 części',
    c6_table='| Część | Cel |\n| --- | --- |\n| Rola | Funkcja |\n| Osobowość | Ton |\n| Cel | Deliverable |\n| Sukces | Gotowe |\n| Ograniczenia | Granice |\n| Wyjście | Format |\n| Stop | Kiedy przestać |',
    c6_note='Proste Q&A: często Cel + Wyjście. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Zmiana 7: format',
    c7='GPT-5.5 jest zwięzły. API: `text.verbosity`, **Structured Outputs**.\n\n> Naturalne akapity domyślnie.\n\n> Zachowaj strukturę, długość i głos; popraw tylko jasność.',
    h_mig='Migracja: reasoning od niskiego',
    mig='Sprawdź `reasoning.effort`; często wystarczy low.',
    h_sum='Podsumowanie',
    sum_line='**Powiedz, czego chcesz — nie każdego kroku.**',
    sum_table='| Wymiar | Wcześniej | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Kroki | Wynik |\n| Ton | Absoluty | Tylko czerwone linie |\n| Rola | Długo | Krótko |\n| Wieloetap | Od razu | Preambuła |\n| Stop | Brak | Jawny |\n| Struktura | Wolna | 7 części |\n| Format | Domyślny | API+prompt |',
    outro='Przetestuj na realnych zadaniach i wypróbuj GPT na LimaxAI.',
)

_add("nl",
    intro='OpenAI publiceerde de officiële GPT-5.5-promptgids. Stap-voor-stap-prompts van oudere modellen kunnen prestaties beperken. Zeven belangrijke wijzigingen.',
    keywords='Trefwoorden: chatgpt, gpt 5.5, gpt tutorial.',
    published='Gepubliceerd: 22 mei 2026',
    img_alt='GPT 5.5 promptgids OpenAI',
    h_bg='Achtergrond: waarom opnieuw schrijven',
    bg='Oude prompts **specificeren het proces te veel**. Bij GPT-5.5 is dat ruis—**schrijf opnieuw**.\n\nDjango-medegrondlegger Simon Willison merkte op dat OpenAI adviseert **from scratch te herschrijven**. Bij GPT-5.5 (of LimaxAI) is prompts een nieuw productontwerp.',
    h1='Wijziging 1: van proces naar resultaat',
    c1='**Oude stijl (proces eerst):**\n\n> Check A, dan B, vergelijk velden, redeneer over uitzonderingen, kies een tool en leg alles uit.\n\n**Nieuwe stijl (resultaat eerst):**\n\n> Los het probleem volledig op. Gebruik beleid en accountdata; rapporteer gedaan en openstaand. Eén kritische vraag bij ontbrekende info.\n\n**Beschrijf de bestemming, niet elke stap.**',
    h2='Wijziging 2: minder absoluten',
    c2='GPT-5.5 is gevoelig voor moet/altijd; tegenstrijdige regels falen.',
    tbl_h1='Situatie',
    tbl_h2='Stijl',
    tbl_r1='Veiligheid, verplichte velden',
    tbl_r1b='altijd/nooit',
    tbl_r2='Zoeken of vragen',
    tbl_r2b='voorwaarden',
    c2_ex='Vervang «moet zoeken» door «antwoord zonder zoeken als context volstaat».',
    h3='Wijziging 3: korte rol',
    c3='**Rol** in 1–2 zinnen; **persoonlijkheid** = toon en samenwerking.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Wijziging 4: preambule',
    c4='Vóór tools: 1–2 zichtbare zinnen over ontvangst en eerste actie.\n\nProducten zoals Codex gebruiken dit patroon al (bijv. codebase analyseren, beginnend met tests) voor API en lange ChatGPT-taken.',
    h5='Wijziging 5: stopregels',
    c5='Alleen «zoek en antwoord» zonder stop kan zoekloops geven.\n\n1. **Zoekbudget:** standaard één ronde.\n2. **Loopstop:** stop als bewijs de kernvraag beantwoordt.',
    h6='Wijziging 6: zevendelig skelet',
    c6_table='| Deel | Doel |\n| --- | --- |\n| Rol | Functie |\n| Persoonlijkheid | Toon |\n| Doel | Output |\n| Succes | Klaar |\n| Beperkingen | Grenzen |\n| Output | Formaat |\n| Stop | Wanneer stoppen |',
    c6_note='Eenvoudige Q&A: vaak Doel + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Wijziging 7: formaat',
    c7="GPT-5.5 is standaard beknopt. API: `text.verbosity`, **Structured Outputs**.\n\n> Natuurlijke alinea's standaard.\n\n> Behoud structuur, lengte en stem bij herschrijven.",
    h_mig='Migratie: reasoning laag',
    mig='Herzie `reasoning.effort`; vaak volstaat low.',
    h_sum='Samenvatting',
    sum_line='**Zeg wat je wilt—niet elke stap.**',
    sum_table='| Dimensie | Voorheen | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Stappen | Resultaat |\n| Toon | Absoluten | Alleen rode lijnen |\n| Rol | Lang | Kort |\n| Multi-step | Direct | Preambule |\n| Stop | Ontbreekt | Expliciet |\n| Structuur | Vrij | 7 delen |\n| Formaat | Default | API+prompt |',
    outro='Test op echte taken en probeer GPT via LimaxAI.',
)

_add("sv",
    intro='OpenAI publicerade den officiella GPT-5.5-promptguiden. Steg-för-steg-prompts från äldre modeller kan begränsa modellen. Sju viktiga förändringar.',
    keywords='Nyckelord: chatgpt, gpt 5.5, gpt guide.',
    published='Publicerad: 22 maj 2026',
    img_alt='GPT 5.5 promptguide',
    h_bg='Bakgrund: varför skriva om',
    bg='Äldre prompts **överspecificerar processen**. Med GPT-5.5 blir det brus—**skriv om från scratch**.\n\nDjango-medskaparen Simon Willison noterade att OpenAI rekommenderar **skriva om från scratch**. Vid GPT-5.5 (eller LimaxAI) är prompts en ny produktdesign.',
    h1='Förändring 1: från process till resultat',
    c1='**Gammal stil (process först):**\n\n> Kontrollera A, sedan B, jämför fält, hantera undantag, välj verktyg och förklara allt.\n\n**Ny stil (resultat först):**\n\n> Lös användarens problem helt. Använd policy och data; rapportera gjort och kvarstående. En kritisk fråga vid behov.\n\n**Beskriv målet, inte varje steg.**',
    h2='Förändring 2: färre absoluta regler',
    c2='GPT-5.5 är känslig för måste/alltid; motstridiga regler misslyckas.',
    tbl_h1='Situation',
    tbl_h2='Stil',
    tbl_r1='Säkerhet, obligatoriska fält',
    tbl_r1b='alltid/aldrig',
    tbl_r2='Söka eller fråga',
    tbl_r2b='villkor',
    c2_ex='Byt «måste söka» mot «svara utan sök om kontext räcker».',
    h3='Förändring 3: kort roll',
    c3='**Roll** 1–2 meningar; **personlighet** = ton och samarbete.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Förändring 4: preamble',
    c4='Före verktyg: 1–2 synliga meningar om mottagande och första steg.\n\nProdukter som Codex använder redan detta mönster (t.ex. analyserar kodbasen, börjar med testfiler) för API och långa ChatGPT-uppgifter.',
    h5='Förändring 5: stoppregler',
    c5='Bara «sök och svara» utan stopp kan loopa.\n\n1. **Sökbudget:** en runda som standard.\n2. **Loopstopp:** stopp när evidens räcker.',
    h6='Förändring 6: sju delar',
    c6_table='| Del | Syfte |\n| --- | --- |\n| Roll | Funktion |\n| Personlighet | Ton |\n| Mål | Leverans |\n| Framgång | Klart |\n| Begränsningar | Gränser |\n| Output | Format |\n| Stopp | När stoppa |',
    c6_note='Enkel Q&A: ofta Mål + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Förändring 7: format',
    c7='GPT-5.5 är kortfattad som standard. API: `text.verbosity`, **Structured Outputs**.\n\n> Naturliga stycken som standard.\n\n> Behåll struktur, längd och röst vid omskrivning.',
    h_mig='Migration: reasoning lågt',
    mig='Utvärdera `reasoning.effort`; low räcker ofta.',
    h_sum='Sammanfattning',
    sum_line='**Säg vad du vill—inte varje steg.**',
    sum_table='| Dimension | Före | GPT-5.5 |\n| --- | --- | --- |\n| Process | Steg | Resultat |\n| Ton | Absolut | Röda linjer |\n| Roll | Lång | Kort |\n| Flersteg | Direkt | Preamble |\n| Stopp | Saknas | Tydlig |\n| Struktur | Fri | 7 delar |\n| Format | Default | API+prompt |',
    outro='Testa på riktiga uppgifter och prova GPT på LimaxAI.',
)

_add("ro",
    intro='OpenAI a publicat ghidul oficial de prompturi GPT-5.5. Prompturile pas cu pas ale modelelor vechi pot limita performanța. 7 schimbări cheie.',
    keywords='Cuvinte cheie: chatgpt, gpt 5.5, tutorial gpt.',
    published='Publicat: 22 mai 2026',
    img_alt='Ghid prompturi GPT 5.5',
    h_bg='Context: de ce rescrii',
    bg='Prompturile vechi **supraspecifică procesul**. Cu GPT-5.5 e zgomot — **rescrie de la zero**.\n\nCo-fondatorul Django Simon Willison a observat că OpenAI recomandă **rescriere de la zero**. La GPT-5.5 (sau LimaxAI), prompturile sunt un produs nou.',
    h1='Schimbarea 1: de la proces la rezultat',
    c1='**Stil vechi (proces):**\n\n> Verifică A, apoi B, compară câmpuri, gestionează excepții, alege tool-ul și explică tot.\n\n**Stil nou (rezultat):**\n\n> Rezolvă complet problema utilizatorului. Folosește politica și datele; raportează ce s-a făcut și ce rămâne. O singură întrebare critică.\n\n**Descrie destinația, nu fiecare pas.**',
    h2='Schimbarea 2: mai puține absolute',
    c2='GPT-5.5 e sensibil la trebuie/întotdeauna; reguli conflictuale eșuează.',
    tbl_h1='Situație',
    tbl_h2='Stil',
    tbl_r1='Siguranță, câmpuri obligatorii',
    tbl_r1b='mereu/niciodată',
    tbl_r2='Căutare sau întrebare',
    tbl_r2b='condițional',
    c2_ex='Înlocuie «trebuie să caute» cu «răspunde fără căutare dacă contextul ajunge».',
    h3='Schimbarea 3: rol scurt',
    c3='**Rol** 1–2 propoziții; **personalitate** = ton și colaborare.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Schimbarea 4: preamble',
    c4='Înainte de tool-uri: 1–2 propoziții vizibile despre primire și primul pas.\n\nProduse precum Codex folosesc deja acest model (ex. analizez codebase-ul, încep cu testele) pentru API și sarcini ChatGPT lungi.',
    h5='Schimbarea 5: reguli de oprire',
    c5='Doar «caută și răspunde» fără oprire poate crea bucle.\n\n1. **Buget căutare:** o rundă implicit.\n2. **Oprire buclă:** oprește când dovada răspunde.',
    h6='Schimbarea 6: schelet în 7 părți',
    c6_table='| Parte | Rol |\n| --- | --- |\n| Rol | Funcție |\n| Personalitate | Ton |\n| Obiectiv | Livrabil |\n| Succes | Gata |\n| Constrângeri | Limite |\n| Output | Format |\n| Stop | Când oprești |',
    c6_note='Q&A simplu: adesea Obiectiv + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Schimbarea 7: format',
    c7='GPT-5.5 e concis implicit. API: `text.verbosity`, **Structured Outputs**.\n\n> Paragrafe naturale implicit.\n\n> Păstrează structura, lungimea și vocea.',
    h_mig='Migrație: reasoning jos',
    mig='Reevaluează `reasoning.effort`; low e des suficient.',
    h_sum='Rezumat',
    sum_line='**Spune ce vrei—nu fiecare pas.**',
    sum_table='| Dimensiune | Înainte | GPT-5.5 |\n| --- | --- | --- |\n| Proces | Pași | Rezultat |\n| Ton | Absolut | Linii roșii |\n| Rol | Lung | Scurt |\n| Multi-pas | Imediat | Preamble |\n| Stop | Omis | Explicit |\n| Structură | Liber | 7 părți |\n| Format | Default | API+prompt |',
    outro='Testează pe sarcini reale și încearcă GPT pe LimaxAI.',
)

_add("ar",
    intro='نشرت OpenAI دليل المطالبات الرسمي مع GPT-5.5. المطالبات خطوة بخطوة للنماذج القديمة قد تحد الأداء. إليك 7 تغييرات عملية.',
    keywords='الكلمات المفتاحية: chatgpt، gpt 5.5، دليل gpt.',
    published='تاريخ النشر: 22 مايو 2026',
    img_alt='دليل مطالبات GPT 5.5 من OpenAI',
    h_bg='الخلفية: لماذا إعادة كتابة المطالبات القديمة',
    bg='المطالبات القديمة **تحدد العملية أكثر من اللازم**. مع GPT-5.5 يصبح ذلك ضوضاء—**أعد الكتابة من الصفر**.\n\nشارك مؤسس Django Simon Willison في الإشارة إلى أن OpenAI توصي **بإعادة الكتابة من الصفر**. عند GPT-5.5 (أو LimaxAI)، عامل المطالبات كمنتج جديد.',
    h1='التغيير 1: من الخطوات إلى النتيجة',
    c1='**الأسلوب القديم (العملية أولاً):**\n\n> تحقق من A ثم B، قارن الحقول، عالج الاستثناءات، اختر الأداة واشرح كل الخطوات.\n\n**الأسلوب الجديد (النتيجة أولاً):**\n\n> حل مشكلة المستخدم بالكامل. استخدم السياسة والبيانات؛ أبلغ بما تم وما تبقى. سؤال حرج واحد عند النقص.\n\n**صف الوجهة، وليس كل منعطف.**',
    h2='التغيير 2: أقل من «يجب» و«ممنوع»',
    c2='GPT-5.5 حساس للصياغة المطلقة؛ القواعد المتعارضة تفشل.',
    tbl_h1='الحالة',
    tbl_h2='الأسلوب',
    tbl_r1='الأمان، الحقول الإلزامية',
    tbl_r1b='دائمًا/أبدًا',
    tbl_r2='البحث أو السؤال',
    tbl_r2b='شروط',
    c2_ex='مثال: بدل «يجب البحث قبل الإجابة» — «إن كفى السياق، أجب دون بحث».',
    h3='التغيير 3: دور قصير',
    c3='**الدور** في جملتين؛ **الشخصية** = النبرة وأسلوب التعاون.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='التغيير 4: مقدمة قبل التنفيذ',
    c4='قبل الأدوات: جملتان مرئيتان تؤكدان الاستلام وأول إجراء.\n\nمنتجات مثل Codex تستخدم هذا النمط بالفعل (مثل «أحلل قاعدة الشيفرة، أبدأ بملفات الاختبار») لـ API ومهام ChatGPT الطويلة.',
    h5='التغيير 5: شروط التوقف',
    c5='«ابحث ثم أجب» دون توقف قد يخلق حلقات بحث.\n\n1. **ميزانية البحث:** جولة واحدة افتراضياً.\n2. **توقف الحلقة:** توقف عند كفاية الأدلة.',
    h6='التغيير 6: هيكل من 7 أجزاء',
    c6_table='| الجزء | الغرض |\n| --- | --- |\n| الدور | الوظيفة |\n| الشخصية | النبرة |\n| الهدف | المخرجات |\n| النجاح | الاكتمال |\n| القيود | الحدود |\n| المخرج | التنسيق |\n| التوقف | متى تتوقف |',
    c6_note='الأسئلة البسيطة: غالبًا الهدف + المخرج فقط. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='التغيير 7: التنسيق والإيجاز',
    c7='GPT-5.5 مختصر افتراضياً. API: `text.verbosity` و**Structured Outputs**.\n\n> فقرات طبيعية افتراضياً.\n\n> احفظ البنية والطول والصوت عند إعادة الصياغة.',
    h_mig='الترحيل: reasoning منخفض',
    mig='أعد تقييم `reasoning.effort`؛ غالبًا يكفي low.',
    h_sum='الخلاصة',
    sum_line='**قل ماذا تريد—لا كل خطوة تنفيذ.**',
    sum_table='| البعد | سابقًا | GPT-5.5 |\n| --- | --- | --- |\n| العملية | خطوات | نتيجة |\n| النبرة | مطلق | خطوط حمراء فقط |\n| الدور | طويل | قصير |\n| متعدد الخطوات | فوري | مقدمة |\n| التوقف | غائب | صريح |\n| الهيكل | حر | 7 أجزاء |\n| التنسيق | افتراضي | API+prompt |',
    outro='اختبر على مهام حقيقية ثم جرّب GPT عبر LimaxAI بالزر أدناه.',
)

_add("id",
    intro='OpenAI merilis panduan prompt resmi GPT-5.5. Prompt langkah demi langkah model lama bisa membatasi kinerja. Berikut 7 perubahan penting.',
    keywords='Kata kunci: chatgpt, gpt 5.5, tutorial gpt.',
    published='Tanggal: 22 Mei 2026',
    img_alt='Panduan prompt GPT 5.5',
    h_bg='Latar: mengapa menulis ulang prompt lama',
    bg='Prompt lama sering **terlalu menjabarkan proses**. Di GPT-5.5 itu menjadi noise—**tulis ulang dari awal**.\n\nCo-creator Django Simon Willison mencatat OpenAI menyarankan **menulis ulang dari awal**. Saat GPT-5.5 (atau di LimaxAI), perlakukan prompt sebagai desain produk baru.',
    h1='Perubahan 1: dari proses ke hasil',
    c1='**Gaya lama (proses dulu):**\n\n> Periksa A, lalu B, bandingkan field, tangani pengecualian, pilih tool, jelaskan semua langkah.\n\n**Gaya baru (hasil dulu):**\n\n> Selesaikan masalah pengguna sepenuhnya. Gunakan kebijakan dan data; laporkan yang selesai dan tersisa. Satu pertanyaan kritis jika kurang info.\n\n**Gambarkan tujuan, bukan setiap langkah.**',
    h2='Perubahan 2: lebih sedikit absolut',
    c2='GPT-5.5 sensitif pada harus/selalu; aturan bentrok gagal.',
    tbl_h1='Situasi',
    tbl_h2='Gaya',
    tbl_r1='Keamanan, field wajib',
    tbl_r1b='selalu/tidak pernah',
    tbl_r2='Cari atau tanya',
    tbl_r2b='bersyarat',
    c2_ex='Ganti «harus cari dulu» dengan «jika konteks cukup, jawab tanpa cari».',
    h3='Perubahan 3: peran singkat',
    c3='**Peran** 1–2 kalimat; **kepribadian** = nada dan kolaborasi.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Perubahan 4: preamble',
    c4='Sebelum tool: 1–2 kalimat terlihat tentang penerimaan dan langkah pertama.\n\nProduk seperti Codex sudah memakai pola ini (mis. «Menganalisis codebase, mulai dari file tes») untuk API dan tugas ChatGPT panjang.',
    h5='Perubahan 5: aturan berhenti',
    c5='Hanya «cari lalu jawab» tanpa stop bisa loop.\n\n1. **Anggaran pencarian:** satu putaran default.\n2. **Stop loop:** berhenti jika bukti cukup.',
    h6='Perubahan 6: kerangka 7 bagian',
    c6_table='| Bagian | Fungsi |\n| --- | --- |\n| Peran | Fungsi |\n| Kepribadian | Nada |\n| Tujuan | Output |\n| Sukses | Selesai |\n| Batasan | Limit |\n| Output | Format |\n| Stop | Kapan berhenti |',
    c6_note='Q&A sederhana: sering Tujuan + Output saja. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Perubahan 7: format',
    c7='GPT-5.5 ringkas secara default. API: `text.verbosity`, **Structured Outputs**.\n\n> Paragraf natural sebagai default.\n\n> Pertahankan struktur, panjang, dan suara saat menulis ulang.',
    h_mig='Migrasi: reasoning rendah',
    mig='Evaluasi ulang `reasoning.effort`; low sering cukup.',
    h_sum='Ringkasan',
    sum_line='**Katakan apa yang Anda mau—bukan setiap langkah.**',
    sum_table='| Dimensi | Dulu | GPT-5.5 |\n| --- | --- | --- |\n| Proses | Langkah | Hasil |\n| Nada | Absolut | Garis merah saja |\n| Peran | Panjang | Pendek |\n| Multi-langkah | Langsung | Preamble |\n| Stop | Absen | Eksplisit |\n| Struktur | Bebas | 7 bagian |\n| Format | Default | API+prompt |',
    outro='Uji pada tugas nyata lalu coba GPT di LimaxAI lewat tombol di bawah.',
)

_add("ms",
    intro='OpenAI melancarkan panduan prompt rasmi GPT-5.5. Prompt langkah demi langkah model lama boleh mengehadkan prestasi. 7 perubahan utama.',
    keywords='Kata kunci: chatgpt, gpt 5.5, tutorial gpt.',
    published='Tarikh: 22 Mei 2026',
    img_alt='Panduan prompt GPT 5.5',
    h_bg='Latar: mengapa tulis semula prompt lama',
    bg='Prompt lama sering **terlalu memperincikan proses**. Pada GPT-5.5 ia menjadi hingar—**tulis semula dari awal**.\n\nPengasas bersama Django Simon Willison menyatakan OpenAI mengesyorkan **tulis semula dari awal**. Untuk GPT-5.5 (atau LimaxAI), prompt ialah reka bentuk produk baharu.',
    h1='Perubahan 1: proses ke hasil',
    c1='**Gaya lama (proses dulu):**\n\n> Semak A, kemudian B, bandingkan medan, urus pengecualian, pilih alat, terangkan setiap langkah.\n\n**Gaya baharu (hasil dulu):**\n\n> Selesaikan masalah pengguna sepenuhnya. Gunakan dasar dan data; laporkan siap dan baki. Satu soalan kritikal jika kurang maklumat.\n\n**Gambarkan destinasi, bukan setiap langkah.**',
    h2='Perubahan 2: kurang absolut',
    c2='GPT-5.5 sensitif pada mesti/sentiasa; peraturan bercanggah gagal.',
    tbl_h1='Situasi',
    tbl_h2='Gaya',
    tbl_r1='Keselamatan, medan wajib',
    tbl_r1b='sentiasa/tidak',
    tbl_r2='Cari atau tanya',
    tbl_r2b='bersyarat',
    c2_ex='Ganti «mesti cari» dengan «jika konteks mencukupi, jawab tanpa cari».',
    h3='Perubahan 3: peranan pendek',
    c3='**Peranan** 1–2 ayat; **personaliti** = nada dan kerjasama.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Perubahan 4: preamble',
    c4='Sebelum alat: 1–2 ayat kelihatan tentang penerimaan dan langkah pertama.\n\nProduk seperti Codex sudah menggunakan corak ini (cth. «Menganalisis codebase, bermula dengan fail ujian») untuk API dan tugas ChatGPT panjang.',
    h5='Perubahan 5: peraturan henti',
    c5='«Cari kemudian jawab» tanpa henti boleh gelung.\n\n1. **Bajet carian:** satu pusingan lalai.\n2. **Henti gelung:** berhenti jika bukti mencukupi.',
    h6='Perubahan 6: rangka 7 bahagian',
    c6_table='| Bahagian | Fungsi |\n| --- | --- |\n| Peranan | Fungsi |\n| Personaliti | Nada |\n| Matlamat | Output |\n| Kejayaan | Siap |\n| Kekangan | Had |\n| Output | Format |\n| Henti | Bila berhenti |',
    c6_note='Q&A mudah: sering Matlamat + Output. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Perubahan 7: format',
    c7='GPT-5.5 ringkas secara lalai. API: `text.verbosity`, **Structured Outputs**.\n\n> Perenggan semula jadi sebagai lalai.\n\n> Kekalkan struktur, panjang dan suara.',
    h_mig='Migrasi: reasoning rendah',
    mig='Nilai semula `reasoning.effort`; low sering mencukupi.',
    h_sum='Ringkasan',
    sum_line='**Katakan apa yang anda mahu—bukan setiap langkah.**',
    sum_table='| Dimensi | Dulu | GPT-5.5 |\n| --- | --- | --- |\n| Proses | Langkah | Hasil |\n| Nada | Mutlak | Garisan merah |\n| Peranan | Panjang | Pendek |\n| Berbilang langkah | Terus | Preamble |\n| Henti | Tiada | Jelas |\n| Struktur | Bebas | 7 bahagian |\n| Format | Lalai | API+prompt |',
    outro='Uji pada tugas sebenar kemudian cuba GPT di LimaxAI.',
)

_add("vi",
    intro='OpenAI phát hành hướng dẫn prompt chính thức GPT-5.5. Prompt từng bước của model cũ có thể hạn chế hiệu suất. 7 thay đổi quan trọng.',
    keywords='Từ khóa: chatgpt, gpt 5.5, hướng dẫn gpt.',
    published='Ngày đăng: 22 tháng 5 năm 2026',
    img_alt='Hướng dẫn prompt GPT 5.5',
    h_bg='Bối cảnh: vì sao viết lại prompt cũ',
    bg='Prompt cũ thường **mô tả quy trình quá chi tiết**. Với GPT-5.5 đó là nhiễu—**viết lại từ đầu**.\n\nĐồng sáng lập Django Simon Willison lưu ý OpenAI khuyên **viết lại từ đầu**. Với GPT-5.5 (hoặc LimaxAI), coi prompt là thiết kế sản phẩm mới.',
    h1='Thay đổi 1: từ quy trình sang kết quả',
    c1='**Kiểu cũ (quy trình trước):**\n\n> Kiểm A, rồi B, so khớp trường, xử lý ngoại lệ, chọn tool, giải thích từng bước.\n\n**Kiểu mới (kết quả trước):**\n\n> Giải quyết triệt để vấn đề người dùng. Dùng chính sách và dữ liệu; báo đã làm và còn lại. Một câu hỏi then chốt nếu thiếu thông tin.\n\n**Mô tả đích đến, không phải từng bước.**',
    h2='Thay đổi 2: ít tuyệt đối hơn',
    c2='GPT-5.5 nhạy với phải/luôn; quy tắc mâu thuẫn dễ hỏng.',
    tbl_h1='Tình huống',
    tbl_h2='Kiểu',
    tbl_r1='An toàn, trường bắt buộc',
    tbl_r1b='luôn/không bao giờ',
    tbl_r2='Tìm hay hỏi',
    tbl_r2b='điều kiện',
    c2_ex='Thay «phải tìm trước» bằng «nếu ngữ cảnh đủ, trả lời không cần tìm».',
    h3='Thay đổi 3: vai trò ngắn',
    c3='**Vai trò** 1–2 câu; **tính cách** = giọng và cách hợp tác.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Thay đổi 4: xác nhận trước',
    c4='Trước tool: 1–2 câu hiển thị về đã nhận yêu cầu và bước đầu.\n\nSản phẩm như Codex đã dùng mẫu này (vd. «Đang phân tích codebase, bắt đầu từ file test») cho API và tác vụ ChatGPT dài.',
    h5='Thay đổi 5: điều kiện dừng',
    c5='Chỉ «tìm rồi trả lời» không có điểm dừng dễ lặp.\n\n1. **Ngân sách tìm:** mặc định một vòng.\n2. **Dừng vòng:** dừng khi bằng chứng đủ.',
    h6='Thay đổi 6: khung 7 phần',
    c6_table='| Phần | Mục đích |\n| --- | --- |\n| Vai trò | Chức năng |\n| Tính cách | Giọng |\n| Mục tiêu | Đầu ra |\n| Thành công | Xong |\n| Ràng buộc | Giới hạn |\n| Đầu ra | Định dạng |\n| Dừng | Khi nào dừng |',
    c6_note='Hỏi đáp đơn giản: thường chỉ Mục tiêu + Đầu ra. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Thay đổi 7: định dạng',
    c7='GPT-5.5 mặc định ngắn gọn. API: `text.verbosity`, **Structured Outputs**.\n\n> Đoạn tự nhiên mặc định.\n\n> Giữ cấu trúc, độ dài và giọng khi viết lại.',
    h_mig='Di chuyển: reasoning thấp',
    mig='Đánh giá lại `reasoning.effort`; low thường đủ.',
    h_sum='Tóm tắt',
    sum_line='**Nói bạn muốn gì—không phải từng bước.**',
    sum_table='| Chiều | Trước | GPT-5.5 |\n| --- | --- | --- |\n| Quy trình | Bước | Kết quả |\n| Giọng | Tuyệt đối | Chỉ vạch đỏ |\n| Vai trò | Dài | Ngắn |\n| Đa bước | Ngay | Xác nhận |\n| Dừng | Thiếu | Rõ |\n| Cấu trúc | Tự do | 7 phần |\n| Định dạng | Mặc định | API+prompt |',
    outro='Kiểm thử trên tác vụ thật rồi dùng GPT trên LimaxAI qua nút bên dưới.',
)

_add("th",
    intro='OpenAI เปิดตัวคู่มือพรอมต์ GPT-5.5 อย่างเป็นทางการ พรอมต์ทีละขั้นของโมเดลเก่าอาจจำกัดประสิทธิภาพ สรุป 7 การเปลี่ยนแปลงสำคัญ',
    keywords='คำสำคัญ: chatgpt, gpt 5.5, บทช่วยสอน gpt',
    published='เผยแพร่: 22 พฤษภาคม 2026',
    img_alt='คู่มือพรอมต์ GPT 5.5',
    h_bg='พื้นหลัง: ทำไมต้องเขียนพรอมต์ใหม่',
    bg='พรอมต์เก่ามัก **ระบุขั้นตอนละเอียดเกินไป** กับ GPT-5.5 กลายเป็นสัญญาณรบกวน—**เขียนใหม่ตั้งแต่ต้น**\n\nSimon Willison ผู้ร่วมก่อตั้ง Django ชี้ว่า OpenAI แนะนำ **เขียนใหม่ตั้งแต่ต้น** เมื่อใช้ GPT-5.5 (หรือ LimaxAI) ให้มองพรอมต์เป็นการออกแบบผลิตภัณฑ์ใหม่',
    h1='การเปลี่ยนแปลง 1: จากขั้นตอนสู่ผลลัพธ์',
    c1='**สไตล์เก่า (ขั้นตอนก่อน):**\n\n> ตรวจ A แล้ว B เปรียบเทียบฟิลด์ จัดการข้อยกเว้น เลือกเครื่องมือ อธิบายทุกขั้น\n\n**สไตล์ใหม่ (ผลลัพธ์ก่อน):**\n\n> แก้ปัญหาผู้ใช้ให้จบ ใช้นโยบายและข้อมูล รายงานสิ่งที่ทำและคงค้าง ถามคำถามสำคัญหนึ่งข้อหากขาดข้อมูล\n\n**บอกจุดหมาย ไม่ใช่ทุกเลี้ยว**',
    h2='การเปลี่ยนแปลง 2: ลดคำสั่งแบบสัมบูรณ์',
    c2='GPT-5.5 ไวต่อ must/never กฎขัดแย้งมักล้มเหลว',
    tbl_h1='สถานการณ์',
    tbl_h2='สไตล์',
    tbl_r1='ความปลอดภัย ฟิลด์บังคับ',
    tbl_r1b='เสมอ/ไม่เคย',
    tbl_r2='ค้นหาหรือถาม',
    tbl_r2b='เงื่อนไข',
    c2_ex='เปลี่ยน «ต้องค้นหาก่อน» เป็น «ถ้าบริบทพอ ตอบโดยไม่ค้นหา»',
    h3='การเปลี่ยนแปลง 3: บทบาทสั้น',
    c3='**บทบาท** 1–2 ประโยค **บุคลิก** = น้ำเสียงและการทำงานร่วม\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='การเปลี่ยนแปลง 4: ยืนยันก่อนทำ',
    c4='ก่อนเรียกเครื่องมือ: 1–2 ประโยคที่ผู้ใช้เห็น ยืนยันรับคำขอและขั้นแรก\n\nผลิตภัณฑ์อย่าง Codex ใช้รูปแบบนี้แล้ว (เช่น «กำลังวิเคราะห์ codebase เริ่มจากไฟล์ทดสอบ») สำหรับ API และงาน ChatGPT ยาว',
    h5='การเปลี่ยนแปลง 5: เงื่อนไขหยุด',
    c5='แค่ «ค้นหาแล้วตอบ» โดยไม่กำหนดจุดหยุดอาจวนซ้ำ\n\n1. **งบค้นหา:** ค่าเริ่มต้นหนึ่งรอบ\n2. **หยุดลูป:** หยุดเมื่อหลักฐานเพียงพอ',
    h6='การเปลี่ยนแปลง 6: โครง 7 ส่วน',
    c6_table='| ส่วน | วัตถุประสงค์ |\n| --- | --- |\n| บทบาท | หน้าที่ |\n| บุคลิก | น้ำเสียง |\n| เป้าหมาย | ผลลัพธ์ |\n| สำเร็จ | เสร็จ |\n| ข้อจำกัด | ขอบเขต |\n| เอาต์พุต | รูปแบบ |\n| หยุด | เมื่อไหร่หยุด |',
    c6_note='คำถามง่าย: มักแค่เป้าหมาย+เอาต์พุต OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='การเปลี่ยนแปลง 7: รูปแบบ',
    c7='GPT-5.5 กระชับโดยค่าเริ่มต้น ใช้ `text.verbosity` และ **Structured Outputs**\n\n> ย่อหน้าธรรมชาติเป็นค่าเริ่มต้น\n\n> คงโครงสร้าง ความยาว และน้ำเสียงเมื่อเขียนใหม่',
    h_mig='ย้ายระบบ: reasoning ต่ำ',
    mig='ปรับ `reasoning.effort` ใหม่ หลายงาน low พอ',
    h_sum='สรุป',
    sum_line='**บอกว่าต้องการอะไร—ไม่ใช่ทุกขั้นตอน**',
    sum_table='| มิติ | ก่อน | GPT-5.5 |\n| --- | --- | --- |\n| กระบวนการ | ขั้น | ผลลัพธ์ |\n| น้ำเสียง | สัมบูรณ์ | เฉพาะเส้นแดง |\n| บทบาท | ยาว | สั้น |\n| หลายขั้น | ทันที | ยืนยันก่อน |\n| หยุด | ไม่มี | ชัด |\n| โครงสร้าง | อิสระ | 7 ส่วน |\n| รูปแบบ | ค่าเริ่ม | API+prompt |',
    outro='ทดสอบงานจริงแล้วลอง GPT บน LimaxAI ผ่านปุ่มด้านล่าง',
)

_add("tr",
    intro='OpenAI, GPT-5.5 ile resmi istem kılavuzunu yayınladı. Eski modellerin adım adım istemleri performansı sınırlayabilir. 7 kritik değişiklik.',
    keywords='Anahtar kelimeler: chatgpt, gpt 5.5, gpt eğitimi.',
    published='Yayın: 22 Mayıs 2026',
    img_alt='GPT 5.5 istem kılavuzu',
    h_bg='Arka plan: neden yeniden yazmalı',
    bg="Eski istemler **süreci fazla tarif eder**. GPT-5.5'te bu gürültü—**sıfırdan yazın**.\n\nDjango kurucu ortağı Simon Willison, OpenAI'nin **sıfırdan yazmayı** önerdiğini belirtti. GPT-5.5 (veya LimaxAI) için istemleri yeni ürün tasarımı sayın.",
    h1='Değişiklik 1: süreçten sonuca',
    c1="**Eski stil (süreç önce):**\n\n> A'yı kontrol et, B'yi kontrol et, alanları karşılaştır, istisnaları düşün, aracı seç, tüm süreci açıkla.\n\n**Yeni stil (sonuç önce):**\n\n> Kullanıcı sorununu tamamen çöz. Politika ve veriyle önceliği belirle; yapılan ve kalanı bildir. Eksikte tek kritik soru.\n\n**Varış noktasını yaz, her virajı değil.**",
    h2='Değişiklik 2: daha az mutlak',
    c2='GPT-5.5 must/asla ifadelerine duyarlı; çelişen kurallar bozar.',
    tbl_h1='Durum',
    tbl_h2='Stil',
    tbl_r1='Güvenlik, zorunlu alanlar',
    tbl_r1b='her zaman/asla',
    tbl_r2='Ara veya sor',
    tbl_r2b='koşullu',
    c2_ex='«Önce ara» yerine «bağlam yeterliyse aramadan yanıtla».',
    h3='Değişiklik 3: kısa rol',
    c3='**Rol** 1–2 cümle; **kişilik** = ton ve iş birliği.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='Değişiklik 4: ön onay',
    c4='Araçlardan önce: alındı ve ilk adım hakkında 1–2 görünür cümle.\n\nCodex gibi ürünler bu kalıbı zaten kullanıyor (ör. «Kod tabanınızı analiz ediyorum, test dosyalarıyla başlıyorum») API ve uzun ChatGPT görevleri için.',
    h5='Değişiklik 5: durma kuralları',
    c5='Sadece «ara ve yanıtla» durma kuralı olmadan döngü oluşabilir.\n\n1. **Arama bütçesi:** varsayılan bir tur.\n2. **Döngü durması:** kanıt yeterliyse dur.',
    h6='Değişiklik 6: 7 parçalı iskelet',
    c6_table='| Parça | Amaç |\n| --- | --- |\n| Rol | İşlev |\n| Kişilik | Ton |\n| Hedef | Çıktı |\n| Başarı | Bitti |\n| Kısıt | Sınır |\n| Çıktı | Biçim |\n| Dur | Ne zaman |',
    c6_note='Basit S&C: çoğu zaman Hedef+Çıktı yeter. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='Değişiklik 7: biçim',
    c7='GPT-5.5 varsayılan olarak özdür. API: `text.verbosity`, **Structured Outputs**.\n\n> Doğal paragraflar varsayılan.\n\n> Yeniden yazımda yapı, uzunluk ve sesi koru.',
    h_mig='Geçiş: düşük reasoning',
    mig='`reasoning.effort` yeniden değerlendir; low çoğu iş için yeter.',
    h_sum='Özet',
    sum_line='**Ne istediğini söyle—her adımı değil.**',
    sum_table='| Boyut | Önce | GPT-5.5 |\n| --- | --- | --- |\n| Süreç | Adım | Sonuç |\n| Ton | Mutlak | Kırmızı çizgi |\n| Rol | Uzun | Kısa |\n| Çok adım | Hemen | Ön onay |\n| Dur | Yok | Açık |\n| Yapı | Serbest | 7 parça |\n| Biçim | Varsayılan | API+prompt |',
    outro="Gerçek görevlerde test edin, ardından LimaxAI'da GPT'yi deneyin.",
)

_add("hi",
    intro='OpenAI ने GPT-5.5 के साथ आधिकारिक प्रॉम्प्ट गाइड जारी की। पुराने मॉडल के स्टेप-बाय-स्टेप प्रॉम्प्ट प्रदर्शन सीमित कर सकते हैं। 7 महत्वपूर्ण बदलाव।',
    keywords='कीवर्ड: chatgpt, gpt 5.5, gpt ट्यूटोरियल।',
    published='प्रकाशन: 22 मई 2026',
    img_alt='GPT 5.5 प्रॉम्प्ट गाइड',
    h_bg='पृष्ठभूमि: पुराने प्रॉम्प्ट क्यों बदलें',
    bg='पुराने प्रॉम्प्ट अक्सर **प्रक्रिया को ज़्यादा बताते हैं**। GPT-5.5 पर यह शोर है—**शुरू से लिखें**।\n\nDjango के सह-निर्माता Simon Willison ने OpenAI के **शुरू से लिखने** की सलाह दी। GPT-5.5 (या LimaxAI) पर प्रॉम्प्ट को नए उत्पाद डिज़ाइन की तरह देखें।',
    h1='बदलाव 1: प्रक्रिया से परिणाम',
    c1='**पुरानी शैली (प्रक्रिया पहले):**\n\n> A जाँचो, फिर B, फ़ील्ड तुलना करो, अपवाद सोचो, टूल चुनो, पूरी प्रक्रिया समझाओ।\n\n**नई शैली (परिणाम पहले):**\n\n> उपयोगकर्ता की समस्या पूरी हल करो। नीति और डेटा से पहले क्या करना है तय करो; क्या हुआ और क्या बाकी बताओ। जानकारी कम हो तो एक महत्वपूर्ण सवाल।\n\n**मंज़िल बताओ, हर मोड़ नहीं।**',
    h2='बदलाव 2: कम निरपेक्ष निर्देश',
    c2='GPT-5.5 must/never के प्रति संवेदनशील; विरोधाभासी नियम विफल।',
    tbl_h1='स्थिति',
    tbl_h2='शैली',
    tbl_r1='सुरक्षा, अनिवार्य फ़ील्ड',
    tbl_r1b='हमेशा/कभी नहीं',
    tbl_r2='खोजें या पूछें',
    tbl_r2b='शर्तें',
    c2_ex='«पहले खोज अनिवार्य» की जगह «संदर्भ पर्याप्त हो तो बिना खोज जवाब दें»।',
    h3='बदलाव 3: छोटी भूमिका',
    c3='**भूमिका** 1–2 वाक्य; **व्यक्तित्व** = स्वर और सहयोग।\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='बदलाव 4: पहले पुष्टि',
    c4='टूल से पहले 1–2 दृश्य वाक्य: अनुरोध मिला, पहला कदम।\n\nCodex जैसे उत्पाद पहले से यह पैटर्न उपयोग करते हैं (जैसे «कोडबेस का विश्लेषण, टेस्ट फ़ाइलों से शुरू») API और लंबे ChatGPT कार्यों के लिए।',
    h5='बदलाव 5: रुकने के नियम',
    c5='सिर्फ «खोजो फिर जवाब दो» बिना रुकने पर लूप हो सकता है।\n\n1. **खोज बजट:** डिफ़ॉल्ट एक राउंड।\n2. **लूप स्टॉप:** साक्ष्य पर्याप्त हो तो रुको।',
    h6='बदलाव 6: 7-भाग ढाँचा',
    c6_table='| भाग | उद्देश्य |\n| --- | --- |\n| भूमिका | कार्य |\n| व्यक्तित्व | स्वर |\n| लक्ष्य | आउटपुट |\n| सफलता | पूर्ण |\n| बाधाएँ | सीमा |\n| आउटपुट | प्रारूप |\n| स्टॉप | कब रुकें |',
    c6_note='साधारण Q&A: अक्सर लक्ष्य+आउटपुट। OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='बदलाव 7: प्रारूप',
    c7='GPT-5.5 डिफ़ॉल्ट में संक्षिप्त। API: `text.verbosity`, **Structured Outputs**।\n\n> स्वाभाविक पैराग्राफ डिफ़ॉल्ट।\n\n> पुनर्लेखन में संरचना, लंबाई, स्वर बनाए रखें।',
    h_mig='माइग्रेशन: निम्न reasoning',
    mig='`reasoning.effort` पुनः जाँचें; low अक्सर पर्याप्त।',
    h_sum='सारांश',
    sum_line='**आप क्या चाहते हैं बताएँ—हर कदम नहीं।**',
    sum_table='| आयाम | पहले | GPT-5.5 |\n| --- | --- | --- |\n| प्रक्रिया | कदम | परिणाम |\n| स्वर | निरपेक्ष | केवल रेड लाइन |\n| भूमिका | लंबी | छोटी |\n| बहु-चरण | तुरंत | पुष्टि |\n| स्टॉप | अनुपस्थित | स्पष्ट |\n| संरचना | मुक्त | 7 भाग |\n| प्रारूप | डिफ़ॉल्ट | API+prompt |',
    outro='वास्तविक कार्यों पर परीक्षण करें, फिर LimaxAI पर GPT आज़माएँ।',
)

_add("fa",
    intro='OpenAI راهنمای رسمی پرامپت GPT-5.5 را منتشر کرد. پرامپت\u200cهای گام\u200cبه\u200cگام مدل\u200cهای قدیمی ممکن است عملکرد را محدود کند. ۷ تغییر کلیدی.',
    keywords='کلیدواژه\u200cها: chatgpt، gpt 5.5، آموزش gpt.',
    published='تاریخ انتشار: ۲۲ مه ۲۰۲۶',
    img_alt='راهنمای پرامپت GPT 5.5',
    h_bg='پس\u200cزمینه: چرا پرامپت قدیمی را بازنویسی کنیم',
    bg='پرامپت\u200cهای قدیمی اغلب **فرایند را بیش\u200cازحد مشخص می\u200cکنند**. در GPT-5.5 این نویز است—**از صفر بنویسید**.\n\nهم\u200cبنیان\u200cگذار Django، Simon Willison، گفت OpenAI **از صفر بنویسید**. برای GPT-5.5 (یا LimaxAI)، پرامپت را طراحی محصول جدید بدانید.',
    h1='تغییر ۱: از فرایند به نتیجه',
    c1='**سبک قدیم (فرایند اول):**\n\n> A را بررسی کن، بعد B، فیلدها را مقایسه کن، استثناها را بسنج، ابزار را انتخاب کن و کل فرایند را توضیح بده.\n\n**سبک جدید (نتیجه اول):**\n\n> مسئله کاربر را کامل حل کن. با سیاست و داده اولویت را تعیین کن؛ گزارش انجام\u200cشده و باقی\u200cمانده. یک سؤال حیاتی در صورت کمبود اطلاعات.\n\n**مقصد را بگو، نه هر پیچ.**',
    h2='تغییر ۲: کمتر «باید/ممنوع»',
    c2='GPT-5.5 به دستورهای مطلق حساس است؛ قوانین متناقض شکست می\u200cخورند.',
    tbl_h1='موقعیت',
    tbl_h2='سبک',
    tbl_r1='امنیت، فیلدهای اجباری',
    tbl_r1b='همیشه/هرگز',
    tbl_r2='جستجو یا پرسش',
    tbl_r2b='شرطی',
    c2_ex='به\u200cجای «حتماً جستجو» — «اگر زمینه کافی است، بدون جستجو پاسخ بده».',
    h3='تغییر ۳: نقش کوتاه',
    c3='**نقش** ۱–۲ جمله؛ **شخصیت** = لحن و همکاری.\n\n- **Steady:** reliable collaborator—calm, direct; advance without unnecessary check-ins.\n- **Expressive:** conversational, curious; ask when ambiguous, decide when context is enough.',
    h4='تغییر ۴: تأیید قبل از اجرا',
    c4='قبل از ابزار: ۱–۲ جملهٔ قابل\u200cمشاهده درباره دریافت و گام اول.\n\nمحصولاتی مانند Codex از همین الگو استفاده می\u200cکنند (مثلاً «در حال تحلیل codebase، از فایل\u200cهای تست») برای API و کارهای طولانی ChatGPT.',
    h5='تغییر ۵: شرط توقف',
    c5='فقط «جستجو کن و پاسخ بده» بدون توقف می\u200cتواند حلقه بسازد.\n\n1. **بودجه جستجو:** پیش\u200cفرض یک دور.\n2. **توقف حلقه:** وقتی شواهد کافی است توقف.',
    h6='تغییر ۶: اسکلت ۷ بخشی',
    c6_table='| بخش | هدف |\n| --- | --- |\n| نقش | کارکرد |\n| شخصیت | لحن |\n| هدف | خروجی |\n| موفقیت | تمام |\n| محدودیت | مرز |\n| خروجی | قالب |\n| توقف | چه زمانی |',
    c6_note='سؤال ساده: اغلب هدف+خروجی کافی است. OpenAI developer console also offers **Optimize** to reshape prompts to this structure.',
    h7='تغییر ۷: قالب',
    c7='GPT-5.5 به\u200cطور پیش\u200cفرض مختصر است. API: `text.verbosity` و **Structured Outputs**.\n\n> پاراگراف\u200cهای طبیعی پیش\u200cفرض.\n\n> در بازنویسی ساختار، طول و لحن را حفظ کن.',
    h_mig='مهاجرت: reasoning پایین',
    mig='`reasoning.effort` را بازبینی کنید؛ low اغلب کافی است.',
    h_sum='جمع\u200cبندی',
    sum_line='**بگویید چه می\u200cخواهید—نه هر گام اجرا.**',
    sum_table='| بعد | قبل | GPT-5.5 |\n| --- | --- | --- |\n| فرایند | گام | نتیجه |\n| لحن | مطلق | فقط خط قرمز |\n| نقش | بلند | کوتاه |\n| چندگام | فوری | تأیید |\n| توقف | حذف | صریح |\n| ساختار | آزاد | ۷ بخش |\n| قالب | پیش\u200cفرض | API+prompt |',
    outro='روی کار واقعی آزمایش کنید و از دکمه زیر GPT را در LimaxAI امتحان کنید.',
)

def build_sections(lang: str) -> dict:
    if lang == "zh-tw":
        return _zh_tw()
    base = _en()
    if lang in _LOCALE_OVERRIDES:
        base.update(_LOCALE_OVERRIDES[lang])
    return base


FULL_SECTIONS = {lang: build_sections(lang) for lang in [
    "zh-tw", "ja", "ko", "es", "fr", "de", "pt", "it", "ru", "uk", "pl",
    "nl", "sv", "ro", "ar", "id", "ms", "vi", "th", "tr", "hi", "fa",
]}
